### ISSUE TITLE
Restart on updates fails when using two ore more php version's via php7X-php-pfm

### ISSUE THREAD

**Issue by tuxmaster** [remicollet/remirepo#100]
Hello,
when using two or more php version's at the same time from the remi- save repo, then the automatic restart of the fpm daemon fails after an update.
Scenario:
CentOS 7.4
PHP packages: php71-php-fpm php72-php-fpm

When an update comes, then one of both will fail on restart, because both packages contains an default config for 127.0.0.1:9000.

An possible solution will be, use for every php version another default port. For example 9001 for 7.1
and 9002 for 7.2 and so on. Or switch from tcp to unix sockets and let the socket live under:
/var/opt/remi/php7X/run/php-fpm/www.socket

**Comment by remicollet** [comment]
Additional info: only port 9000 works out of the box, other ports don't work with SELinux default policy

**Comment by tuxmaster** [comment]
Another solution will be comment out the default config,
So that both demons can start.
In my case I have added for both version multiple configs, because I need multiple sockets for very php version.

**Comment by remicollet** [comment]
Again, I don't understand, if 2 services are running (so properly configured), I don't see how restart may fail.

**Comment by tuxmaster** [comment]
Because every time when an update is installed, the two configs comes again with the same tcp port.
And one of both will fail to restart. 
So deliver the php updates automatic is not possible. Because after every update I must remove one www.conf file per hand. And restart the failed fpm process.

**Comment by remicollet** [comment]
> Because after every update I must remove one www.conf file per hand.

Here is the explanation.
Don't "delete" the file, but keep it empty, and if won't be restored during update (default RPM behavior)
