### ISSUE TITLE
Unable to install remi-release-7 with yum4 on CentOS7

### ISSUE THREAD

**Issue by athompso** [remicollet/remirepo#101]
When attempting to install remi-release-7 on a CentOS 7 system that has the Yum4 test repo enabled, it is not possible to proceed:

```
[root@atlas ~]# lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.4.1708 (Core) 
Release:	7.4.1708
Codename:	Core
[root@atlas ~]# 
[root@atlas ~]# dnf install http://rpms.remirepo.net/enterprise/remi-release-7.rpm
Using metadata from Sat Mar 17 20:11:08 2018
Error: package remi-release-7.4-1.el7.remi.noarch requires yum, but none of the providers can be installed
[root@atlas ~]# rpm -q dnf-yum
dnf-yum-0.6.4-2.el7.noarch
```

Manually downloading the repo file into /etc/yum.repos.d/ appears to succeed.

Since EL systems can now have dnf, I suggest in remi-release-el.spec on the "el" branch, you replace
```
Requires:       yum
```
with (approximately, I do not know the correct syntax for this)
```
Requires:       yum || dnf
```

Yes, the _correct_ solution would be for dnf-yum to declare
```
Provides: yum
```
but in the meantime - this is an easy fix on your end, too.

Thanks,
-Adam

**Comment by athompso** [comment]
Also opened the reciprocal bug at https://bugzilla.redhat.com/show_bug.cgi?id=1558181

**Comment by remicollet** [comment]
The dependency is only there to ensure proper ownership of /etc/yum.repos.d

The proper fix will be to require (as for Fedora) this directory

`Requires: /etc/yum.repos.d`

Sadly this is not provided by the dnf package (it is provided by fedora-repos on Fedora).

So can't fix for now.

> `Requires:       yum || dnf`

Rich dependency are not supported here

**Comment by remicollet** [comment]
BTW, I dont really understand the issue, as you can install `dnf` and keep `yum`.

**Comment by remicollet** [comment]
Fixed by https://git.remirepo.net/cgit/rpms/uwsgi/uwsgi-plugin-php.git/commit/?id=f60f4c1d21cb2ef5ce86de15ce21dd27f00a3020

**Comment by remicollet** [comment]
Version 2.0.16 is now available in the repository.

Feedback welcome

**Comment by remicollet** [comment]
Sorry for the noise... I commented the wrong issue./

**Comment by athompso** [comment]
If you're using the CentOS Yum4 repo, no, you can't install dnf while keeping yum - at least not in my experience; following the instructions at https://wiki.centos.org/SpecialInterestGroup/ConfigManagementSIG/YUM4 either uninstalled/replaced yum, or in at least one case, would not continue until I manually removed yum using rpm -e.
(And when using PHP & python for web dev, the dnf resolver is SO much more useful that not using just isn't an option.)

I also recall that yum conflicts with dnf-yum no matter what; not sure how to best resolve.

(Workaround is easy: drop the .repo file in by hand, but now it's not versioned/tracked.)

**Comment by remicollet** [comment]
> If you're using the CentOS Yum4 repo, no, you can't install dnf while keeping yum 

I just install dnf, without removing yum.
Both (seems to) work without issue.

**Comment by athompso** [comment]
Hmm, two sysadmins across ~10 VMs all ran into the same issue with dnf* vs yum* RPMs.  There must be something peculiar to our setup or process, then.
In which case this is an FYI - *some* people who followed the CentOS Yum4/dnf instructions will not be able to follow the "easy path" to getting your RPMs installed.
Thank you for providing clear documentation on alternates.  (Although --force options would have succeeded eventually!)

**Comment by remicollet** [comment]
Fixed by https://git.remirepo.net/cgit/rpms/remi-release.git/commit/?id=0b3a8f9d610a587a99c2288a890347d2b79ec3a6
