### ISSUE TITLE
php*-uwsgi-plugin-php: Conflicts with newer uwsgi-2.0.16 from EPEL

### ISSUE THREAD

**Issue by klada** [remicollet/remirepo#102]
Hi,

I am hosting a bunch of PHP sites using these packages from your repository on my EL7 servers:

php70-uwsgi-plugin-php.x86_64    2.0.15-1.el7.remi
php71-uwsgi-plugin-php.x86_64    2.0.15-1.el7.remi

There is a newer version of uwsgi in EPEL (2.0.16) which creates dependency conflicts on my systems. Could you please rebuild your packages against uwsgi 2.0.16?

**Comment by remicollet** [comment]
I was waiting for 2.0.16 to be pushed in stable repository (which happens this week-end), so will update shortly

**Comment by klada** [comment]
Okay, I did not notice that uwsgi-2.0.16 is not in stable yet. I must check my repo sync scripts then (I am using a local moderated repo).

Thanks for keeping track of this and sorry for the noise.

**Comment by remicollet** [comment]
> Okay, I did not notice that uwsgi-2.0.16 is not in stable yet.

It is, since the last week-end

https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2018-50566f0a39

**Comment by remicollet** [comment]
Fixed by https://git.remirepo.net/cgit/rpms/uwsgi/uwsgi-plugin-php.git/commit/?id=f60f4c1d21cb2ef5ce86de15ce21dd27f00a3020

Version 2.0.16 is now available in the repository.

Feedback welcome

**Comment by klada** [comment]
That was quick, thanks. I started to move my servers to uwsgi 2.0.16 and PHP with uwsgi is working like expected. You may close this issue now.

**Comment by remicollet** [comment]
Thanks for the feedback
