### ISSUE TITLE
CentOS 7.5 update fails during dependency problem (php71-php-pecl-krb5)

### ISSUE THREAD

**Issue by tuxmaster** [remicollet/remirepo#103]
Error: Package: php71-php-pecl-krb5-1.1.2-1.el7.remi.x86_64 (@remi-safe)
           Requires: libkadm5clnt_mit.so.8()(64bit)
           Removing: libkadm5-1.15.1-8.el7.x86_64 (@base)
               libkadm5clnt_mit.so.8()(64bit)
           Updated By: libkadm5-1.15.1-19.el7.x86_64 (updates)
              ~libkadm5clnt_mit.so.11()(64bit)
Error: Package: php71-php-pecl-krb5-1.1.2-1.el7.remi.x86_64 (@remi-safe)
           Requires: libkadm5clnt_mit.so.8(kadm5clnt_mit_8_MIT)(64bit)
           Removing: libkadm5-1.15.1-8.el7.x86_64 (@base)
               libkadm5clnt_mit.so.8(kadm5clnt_mit_8_MIT)(64bit)
           Updated By: libkadm5-1.15.1-19.el7.x86_64 (updates)
              ~libkadm5clnt_mit.so.11(kadm5clnt_mit_11_MIT)(64bit)

The same will happens with php70-php

**Comment by remicollet** [comment]
Thanks for the notice.

**Comment by remicollet** [comment]
Fixed by a simple rebuild:
https://git.remirepo.net/cgit/rpms/php/pecl/php-pecl-krb5.git/commit/?id=373ef14d2e33fe3ada5b2b30cc87e6c2438462dc

Just uploaded version 1.1.2-3 to the repository (should be on all mirrors in a few hours)

**Comment by remicollet** [comment]
Also update in EPEL for official PHP stack
https://bodhi.fedoraproject.org/updates/php-pecl-krb5-1.1.2-2.el7

**Comment by tuxmaster** [comment]
Hi, now the dependency's can resolved again.
