### ISSUE TITLE
no valid certificate on https://cdn.remirepo.net

### ISSUE THREAD

**Issue by prupert** [remicollet/remirepo#108]
There is no valid SSL certificate on https://cdn.remirepo.net, the domain on which mirrorlists are hosted. We would like to use HTTPS with certificate validation.

```
# curl https://cdn.remirepo.net
curl: (51) Unable to communicate securely with peer: requested domain name does not match the server's certificate.
```

**Comment by remicollet** [comment]
By design, as cdn is hosted on various servers, there is no SSL.

This cdn only serve the mirror list

If you want SSL for everything use
`mirrorlist=https://rpms.remirepo.net/enterprise/VERSION/remi/httpsmirror`
