### ISSUE TITLE
[FEATURE] MaxMind-DB-Reader C Extension

### ISSUE THREAD

**Issue by billionaire** [remicollet/remirepo#110]
Hello.
MaxMind has [announced](https://support.maxmind.com/geolite-legacy-discontinuation-notice/) that they will stop updating GeoLite Legacy databases by January 2, 2019.
Instead, it is proposed to use database in GeoLite2 format. For this there is a php-library or [the extension](https://github.com/maxmind/MaxMind-DB-Reader-php#optional-php-c-extension).
Will you have opportunity to add packages with official php-extension for reading databases in GeoLite2 format?
Thank you.
Sincerely.

**Comment by remicollet** [comment]
Despite I usually prefer extension available in PECL forge, this one make sense.

**Comment by remicollet** [comment]
Fixed in
https://git.remirepo.net/cgit/rpms/php/php-maxminddb.git/commit/?id=ca9bb84e31ec16cfc2cc27397c65a202573fd3b4

Added on the extension list
https://blog.remirepo.net/pages/PECL-extensions-RPM-status#c7770

Added in the repository for PHP 5.4 to 7.3 (base and SCL)

Announced
https://twitter.com/RemiRepository/status/1060140395500355586

Feedback welcome

**Comment by remicollet** [comment]
Also have open 

* https://github.com/maxmind/MaxMind-DB-Reader-php/pull/73
* https://github.com/maxmind/MaxMind-DB-Reader-php/pull/74

Will see how upstream is open

**Comment by remicollet** [comment]
@oschwald For you rinformation

**Comment by remicollet** [comment]
Running `examples/benchmark.php`

Without the extension
`Requests per second: 1964,0619570276`

With the extension
`Requests per second: 90743,375391592`

45 time faster :)

**Comment by billionaire** [comment]
Hey. You did a great job. Thank you very much.
Some comparative tests:
```
Requests per second ($reader->get; constructor inside of the loop; applicable for situations where country definition is used 1 time per script operation): 6439.7551903521
Requests per second ($reader->get; constructor outside of the loop): 128366.6723796
Requests per second (geoip_country_code_by_name): 41579.840096755
```
In any case, it is many times faster than using the php library.
Good luck to you.

**Comment by remicollet** [comment]
Thanks for the feedback.

**Comment by remicollet** [comment]
I also add the library, so now, you have 2 packages

php-maxmind-db-reader = the library (name as php-<packagist_vendor>-<packagist_project>)
php-maxminddb=  the extension (name as php-<extensionname>)
