### ISSUE TITLE
modular repository for EL-7

### ISSUE THREAD

**Issue by remicollet** [remicollet/remirepo#112]
Requested on https://twitter.com/jdashton/status/1103848270147870721

**Comment by remicollet** [comment]
Repository createed
https://git.remirepo.net/cgit/web/rpms.git/commit/?id=8193cf03485df70351585fc00e1c61ebec6aac3e

Repository definition added in remi-release-7.6-2
https://git.remirepo.net/cgit/rpms/remi-release.git/commit/?id=65a88e88a7b92dba8451b4054b75acfdd6f0a3cc


Notice: the repository is disabled by default, to avoid issue for most users (yum) so you need to enable it

    yum-config-manager --enable remi-modular

Of course you need dnf 4 (from centos-extras)

    yum install dnf

Then you can play with it

    dnf module install php:remi-7.3

Available modules:

- php
    - remi-7.1
    - remi-7.2
    - remi-7.3
- glpi
    - 9.2
    - 9.3
    - 9.4
- redis
    - remi-5.0

**Comment by remicollet** [comment]
Notice: you may need to add, in /etc/os-release

     PLATFORM_ID="platform:el7"

**Comment by remicollet** [comment]
Sadly, `dnf module list` segfaults...

**Comment by jdashton** [comment]
Thanks for trying!

**Comment by remicollet** [comment]
Upstream bugs:
* https://bugs.centos.org/view.php?id=15903
* https://bugzilla.redhat.com/1687453 - segfaults during "dnf module list"
* https://bugzilla.redhat.com/1687455 - always reinstalling the kernel in "dnf update"

**Comment by remicollet** [comment]
Closing, the repo is available, and works, but dnf bugs need to be fixed to be really usable
