### ISSUE TITLE
php5.6 minor patch

### ISSUE THREAD

**Issue by leagueofsoups** [remicollet/remirepo#114]
Hi, Remi! Add this patch to php5.6 package, please.
https://github.com/leagueofsoups/php5.6-segfault-fix/

**Comment by remicollet** [comment]
Hi,

As explain PHP 5.6 is EOL upstream and maintained here on a best effort way, and ONLY security fix are backported from maintained version.

BTW, as this change is quite minor, and self-content, and fix an annoying segfault, It will be included in next build.

Fix in 
- php-5.6.40-6 : https://git.remirepo.net/cgit/rpms/php/php56.git/commit/?id=d07b0a64c3ea35ee0043e148520c25786371967f
- php56-php-5.6.40-6 : https://git.remirepo.net/cgit/rpms/scl-php56/php.git/commit/?id=1208d792b6aad201e6f156ae5f483774ee25c873
- php-7.0.33-6: https://git.remirepo.net/cgit/rpms/php/php70.git/commit/?id=78460d5d55b62c2a2ed3d46d7027d8496e27e249
- php70-php-7.0.33-6: https://git.remirepo.net/cgit/rpms/scl-php70/php.git/commit/?id=d4b35588f862a753d994f613c512886a6e9cb345

Only build for EL-7
- **php-5.6.40-6** in "remi-php56"
- php-7.0.33-6 in "remi-php70-test"'
- **php56-php-5.6.40-6** and **php70-php-7.0.33-6** in "remi-test"

If you are using another distro, please tell me which package you need, so I can provide a test build.

Feedback welcome;

**Comment by remicollet** [comment]
Notice, that patch applied is sightly different from linked one, as it also includes the upstream test, and another commit to fix the test.

**Comment by leagueofsoups** [comment]
This is perfect, thank you!

**Comment by remicollet** [comment]
Version 5.6.40-7 now includes this patch for all distros / versions
