### ISSUE TITLE
Remi configuration wizard is producing http URLs

### ISSUE THREAD

**Issue by ferdnyc** [remicollet/remirepo#118]
Before I figured out that it was PHP-centric (and so, not really what I needed), I ran through the [Configuration Wizard](https://rpms.remirepo.net/wizard/) and it produced a repo-package URL of  http://rpms.remirepo.net/fedora/remi-release-30.rpm.

The server supports HTTPS (I was able to install just fine from https://rpms.remirepo.net/fedora/remi-release-30.rpm), it would be good if the wizard made use of it.

**Comment by remicollet** [comment]
Fixed by https://git.remirepo.net/cgit/web/rpms.git/commit/?id=d2afbc910bea2492b888a92e64f0296eb40240c3
