### ISSUE TITLE
SRPMs?

### ISSUE THREAD

**Issue by ferdnyc** [remicollet/remirepo#119]
I noticed that SRPMs don't appear to be available for any of the packages in the Fedora repos — would it be possible to make those available as well?

Sometimes a package needs to be tweaked some for local use, or other times it's just helpful to see how others have already solved the same problems we're encountering.

Thanks!

**Comment by remicollet** [comment]
See links at the bottom of the home pahe of the repository
=> https://rpms.remirepo.net/SRPMS/repoview/

The same SRPM is used for all distro / branches.

**Comment by ferdnyc** [comment]
> See links at the bottom of the home pahe of the repository
> => https://rpms.remirepo.net/SRPMS/repoview/

Not sure how I missed that, sorry! Thanks for the quick response.

> The same SRPM is used for all distro / branches.

Yeah, I see... I was next going to ask if it'd be possible to enable a `[remi-source]` repo in the `/etc/yum.repo.d/remi.conf` file (so it can be automatically activated with `dnf download --source`), but since the SRPMs don't exactly correspond to the built versions, `dnf` would refuse to pull them in anyway. Eh, the web version is fine. Neeeeever mind! :grin:
