### ISSUE TITLE
LibRaw soname bump

### ISSUE THREAD

**Issue by remicollet** [remicollet/remirepo#123]
In RHEL 7.7, LibRaw was updated to 0.19.2, with a new soname (5 => 19)

This breaks dependency of ImageMagick 6 and 7 in the repository

See https://forum.remirepo.net/viewtopic.php?id=3873

**Comment by remicollet** [comment]
Workaround:

* **ImageMagick6**-6.9.10.59-2 and **ImageMagick7**-7.0.8.59-2 rebuild against LibRaw 0.19.2-1 from RHEL-7.7
* **LibRaw**-0.19.2-0 available for CentOS 7.6 users

TODO: remove LibRaw from the repository when CentOS 7.7 will be released

**Comment by remicollet** [comment]
https://git.remirepo.net/cgit/rpms/lib/libRaw.git/commit/?id=c119a40f63cf7aa38e85f809e691d6af7085bfe2

**Comment by remicollet** [comment]
Also https://forum.remirepo.net/viewtopic.php?id=3875

=> Package: libkdcraw-4.10.5-5.el7.x86_64 (@base)

**Comment by remicollet** [comment]
libkdcraw-4.10.5-6.el7.remi temporarily available in the repo

https://git.remirepo.net/cgit/rpms/lib/libkdcraw.git/commit/?id=3769388ca5f8a3537804efe42d7c593ac25d2944

**Comment by schroedr** [comment]
I've encountered the same broken dependency issue with shotwell.
Starting point is CentOS 7.5, Remi php 7.2, shotwell 0.24
Wanted to update to CentOS 7.6 shotwell 0.28.
The conflict was libraw.so.5 vs libraw.so.19.
Ultimately I uninstalled shotwell and got the yum update to work (without needing --exclude or --skip-broken)

**Comment by AdelR5** [comment]
> I've encountered the same broken dependency issue with shotwell.
> Starting point is CentOS 7.5, Remi php 7.2, shotwell 0.24
> Wanted to update to CentOS 7.6 shotwell 0.28.
> The conflict was libraw.so.5 vs libraw.so.19.
> Ultimately I uninstalled shotwell and got the yum update to work (without needing --exclude or --skip-broken)

I have the same problem, Can you please list down the steps so that a user like me know how to do it (am new to using CentOS 7). Thank you in advance

**Comment by AdelR5** [comment]
Package | Description | Status | Source
-- | -- | -- | --
  | LibRaw | Library for reading RAW files obtained from digital photo cameras | New version 0.19.2-0.el7.remi | Remi-safe
  | libkdcraw | A C++ interface around LibRaw library | New version 4.10.5-6.el7.remi | Remi-safe
  | libkdcraw-devel | Development files for libkdcraw | New version 4.10.5-6.el7.remi | Remi-safe
  | xorgxrdp | Implementation of xrdp backend as Xorg modules | New version 0.2.10-4.el7 | Epel

**Comment by remicollet** [comment]
@AdelR5 please post full yum output

**Comment by remicollet** [comment]
xorgxrdp issue is not related to my repository, see my comment on https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2019-8ef2ec6dd4

**Comment by AdelR5** [comment]
> @AdelR5 please post full yum output

Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirrors.isu.net.sa
 * epel: epel.scopesky.iq
 * extras: mirrors.isu.net.sa
 * nux-dextop: li.nux.ro
 * remi-safe: mirror.awanti.com
 * updates: mirrors.isu.net.sa
Resolving Dependencies
--> Running transaction check
---> Package LibRaw.x86_64 0:0.14.8-5.el7.20120830git98d925 will be updated
--> Processing Dependency: libraw.so.5()(64bit) for package: shotwell-0.28.4-1.el7.x86_64
---> Package LibRaw.x86_64 0:0.19.2-0.el7.remi will be an update
---> Package libkdcraw.x86_64 0:4.10.5-5.el7 will be updated
---> Package libkdcraw.x86_64 0:4.10.5-6.el7.remi will be an update
---> Package libkdcraw-devel.x86_64 0:4.10.5-5.el7 will be updated
---> Package libkdcraw-devel.x86_64 0:4.10.5-6.el7.remi will be an update
---> Package xorgxrdp.x86_64 0:0.2.10-1.el7 will be updated
---> Package xorgxrdp.x86_64 0:0.2.10-4.el7 will be an update
--> Processing Dependency: xorg-x11-server-Xorg(x86-64) = 1.20.4 for package: xorgxrdp-0.2.10-4.el7.x86_64
--> Finished Dependency Resolution
Error: Package: shotwell-0.28.4-1.el7.x86_64 (@anaconda)
           Requires: libraw.so.5()(64bit)
           Removing: LibRaw-0.14.8-5.el7.20120830git98d925.x86_64 (@anaconda)
               libraw.so.5()(64bit)
           Updated By: LibRaw-0.19.2-0.el7.remi.x86_64 (remi-safe)
              ~libraw.so.19()(64bit)
Error: Package: xorgxrdp-0.2.10-4.el7.x86_64 (epel)
           Requires: xorg-x11-server-Xorg(x86-64) = 1.20.4
           Installed: xorg-x11-server-Xorg-1.20.1-5.6.el7_6.x86_64 (@updates)
               xorg-x11-server-Xorg(x86-64) = 1.20.1-5.6.el7_6
           Available: xorg-x11-server-Xorg-1.20.1-3.el7.x86_64 (base)
               xorg-x11-server-Xorg(x86-64) = 1.20.1-3.el7
           Available: xorg-x11-server-Xorg-1.20.1-5.el7.x86_64 (updates)
               xorg-x11-server-Xorg(x86-64) = 1.20.1-5.el7
           Available: xorg-x11-server-Xorg-1.20.1-5.1.el7.x86_64 (updates)
               xorg-x11-server-Xorg(x86-64) = 1.20.1-5.1.el7
           Available: xorg-x11-server-Xorg-1.20.1-5.2.el7_6.x86_64 (updates)
               xorg-x11-server-Xorg(x86-64) = 1.20.1-5.2.el7_6
           Available: xorg-x11-server-Xorg-1.20.1-5.3.el7_6.x86_64 (updates)
               xorg-x11-server-Xorg(x86-64) = 1.20.1-5.3.el7_6
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by remicollet** [comment]
AFAIK, 7.7 package should be in CR repo in a few days (Monday ?) and will fix this issue.

**Comment by remicollet** [comment]
The CR repository is now populated with 7.7 packages, so this issue should not exists when CR is enabled.

**Comment by remicollet** [comment]
CentOS 7.7.1908 is now released
https://blog.centos.org/2019/09/release-for-centos-linux-7-1908-on-the-x86_64architecture/

So closing.

**Comment by mwkohler** [comment]
I'm facing this issue on CentOS 7.5.1804 when running `yum update`

**Comment by remicollet** [comment]
@mwkohler check ImageMagick verion used, and see https://github.com/remicollet/remirepo/issues/144
