### ISSUE TITLE
Single Version PHP 7.3 setup on RHEL 8 does not work...

### ISSUE THREAD

**Issue by Lockhead** [remicollet/remirepo#124]
That's all I get:
```
[root@metis]# dnf module install remi-php:7.3
Updating Subscription Management repositories.
Extra Packages for Enterprise Linux 8 - x86_64
Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)
Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)
Remi's Modular repository for Enterprise Linux 8 - x86_64
Safe Remi's RPM repository for Enterprise Linux 8 - x86_64
Error: Problems in request:
missing groups or modules: remi-php:7.3
```

If I search for php, it shows all different versions packages...

**Comment by remicollet** [comment]
for is **php:remi-7.3**, not **remi-php:7.3**

See `dnf module list`

**Comment by remicollet** [comment]
Indeed, Wizard instructions are wrong.
Fixed by https://git.remirepo.net/cgit/web/rpms.git/commit/?id=4619dde8f77b0d662c3b58852f500189e83b92e5

**Comment by Lockhead** [comment]
Shouldn't the wizard say
`dnf module enable php:remi-7.3`
instead of
`dnf module install php:remi-7.3`

For me, i only work with php-cli and don't want to install nginx and all this stuff. But rest assured it's working now, thx for the fast help/fix.

**Comment by remicollet** [comment]
Thanks for the feedback.

If you only want php-cli, and not the web env, simply select the "minimal" profile (default is "common", and "devel" also exists)

` dnf module install php:remi-7.3/minimal`
