### ISSUE TITLE
unable to install php-devel on CentOS 8

### ISSUE THREAD

**Issue by ryanho** [remicollet/remirepo#126]
```
$ yum install php-devel
Last metadata expiration check: 0:03:49 ago on Wed Sep 25 13:24:07 2019.
Error:
 Problem: cannot install the best candidate for the job
  - nothing provides libedit-devel(x86-64) needed by php-devel-7.3.10-1.el8.remi.x86_64
```
It seems like libedit-devel(x86-64) was provided by rhel codeready linux builder repo?

**Comment by remicollet** [comment]
You need to enable the PowerTools repository (equiv. of upstream CodeReady Linux Builder channel) which provide most of the developer stuff.
