### ISSUE TITLE
Packages missing in EPEL-8

### ISSUE THREAD

**Issue by remicollet** [remicollet/remirepo#128]
Tracker for packages needed by PHP stack, usually found in EPEL, and missing in EPEL-8

These packages are temporarily available in "remi" to avoid broken dependencies.

We need to also have them in "remi-safe", and removed when available in EPEL:

- **djvulibre**-3.5.27-10.el8.remi => [#1739168](https://bugzilla.redhat.com/show_bug.cgi?id=1739168)
- **glyphicons-halflings-fonts**-3.1.0-9.20140211git728067b.el8.remi => [#1756967](https://bugzilla.redhat.com/show_bug.cgi?id=1756967)
- **libircclient**-1.8-13.el8.remi => [#1756999](https://bugzilla.redhat.com/show_bug.cgi?id=1756999)
- **liblqr-1**-0.4.2-11.el8.remi => [#1755389](https://bugzilla.redhat.com/show_bug.cgi?id=1755389)
- **mpdecimal**-2.4.2-10.el8.remi => [#1757014](https://bugzilla.redhat.com/show_bug.cgi?id=1757014)

Now in **epel-testing** (kept in "remi")

- none

Now in **epel-playground** (kept in "remi" for now)

- none

Now in **epel** (removed from "remi")

- **cmark**-0.28.3-4.el8.rem => cmark-0.28.3-4.el8, see [#1756572](https://bugzilla.redhat.com/show_bug.cgi?id=1756572)
- **compat-lua**-5.1.5-11.el8.remi => compat-lua-5.1.5-15.el8, see [#1756958](https://bugzilla.redhat.com/show_bug.cgi?id=1756958)
- **cppzmq-devel**-4.1.6-10.el8.remi => cppzmq-devel-4.4.1-1.el8, see [#1756960](https://bugzilla.redhat.com/show_bug.cgi?id=1756960)
- **diffmark**-0.10-18.el8.remi => diffmark-0.10-20.el8
- **fann**-2.2.0-15.el8.remi => fann-2.2.0-6.el8, see [#1756961](https://bugzilla.redhat.com/show_bug.cgi?id=1756961)
- **fastlz**-0.1.0-0.10.20070619svnrev12.el8.remi => fastlz-0.1.0-0.12.20070619svnrev12.el8
- **freetds**-1.00.38-6.el8.remi => 1.1.20-1.el8, see [#1755660](https://bugzilla.redhat.com/show_bug.cgi?id=1755660)
- **gearmand**-1.1.18-6.el8.remi => gearmand-1.1.18-10.el8, see [#1756966](https://bugzilla.redhat.com/show_bug.cgi?id=1756966)
- **GeoIP**-1.6.12-4.el8.remi => GeoIP-1.6.12-7.epel8
- **GeoIP-GeoLite-data**-2018.06-2.el8.remi => GeoIP-GeoLite-data-2018.06-5.epel8
- **gperftools**-2.7-3.el8.remi => gperftools-2.7-6.el8, see [#1756968](https://bugzilla.redhat.com/show_bug.cgi?id=1756968)
- **hiredis**-0.13.3-9.el8.remi => hiredis-0.13.3-9.el8; see [#1756992](https://bugzilla.redhat.com/show_bug.cgi?id=1756992)
- **jemalloc**-5.1.0-3.el8.remi => jemalloc-5.2.1-2.el8, see [#1756993](https://bugzilla.redhat.com/show_bug.cgi?id=1756993)
- **leveldb**-1.20-3.el8.remi => 1.22-1.el8  [#1756994](https://bugzilla.redhat.com/show_bug.cgi?id=1756994)
- **libharu**-2.3.0-5.el8.remi => libharu-2.3.0-7.el8
- **liblzf**-3.6-16.el8.remi => liblzf-3.6-16.el8, see  [#1753674](https://bugzilla.redhat.com/show_bug.cgi?id=1753674)
- **libraqm**-0.7.0-1.el8 => libraqm-0.7.0-4.el8, see [#1755388](https://bugzilla.redhat.com/show_bug.cgi?id=1755388)
- **libssh2**-1.9.0-3.el8.remi => 1.9.0-5.el8 [#1792625](https://bugzilla.redhat.com/show_bug.cgi?id=1792625)
- **libwebsockets**-2.4.2-1.el8.remi =>  libwebsockets-4.0.1-2.el8 , see [#1757005](https://bugzilla.redhat.com/show_bug.cgi?id=1757005)
- **libxmp**-4.4.1-7.el8.remi => libxmp-4.4.1-9.el8, see  [#1757008](https://bugzilla.redhat.com/show_bug.cgi?id=1757008)
- **matio**-1.5.15-2.el8.remi => 1.5.17-3.el8, see  [#1757289](https://bugzilla.redhat.com/show_bug.cgi?id=1757289)
- **mosquitto**-1.5.4-1.el8.remi => 1.6.9-2.el8, see  [#1757010](https://bugzilla.redhat.com/show_bug.cgi?id=1757010)
- **openpgm**-5.2.122-14.el8.remi => openpgm-5.2.122-1.el8, see [#1757018](https://bugzilla.redhat.com/show_bug.cgi?id=1757018)
- **openslide**-3.4.1-11.el8.remi => openslide-3.4.1-17.el8, see [#1757019](https://bugzilla.redhat.com/show_bug.cgi?id=1757019)
- **ssdeep**-2.14.1-5.el8.remi => ssdeep-2.14.1-7.el8
- **t1lib**-5.1.2-23.el8.remi => t1lib-5.1.2-28.el8, see  [#1757030](https://bugzilla.redhat.com/show_bug.cgi?id=1757030)
- **tidy**-5.6.0-4.el8.remi => tidy-5.6.0-5.el8, see [#1749908](https://bugzilla.redhat.com/show_bug.cgi?id=1749908)
- **zeromq**-4.1.6-10.el8.remi => zeromq-4.3.2-1.el8, see  [#1756680](https://bugzilla.redhat.com/show_bug.cgi?id=1756680)
- **zstd**-1.4.0-1.el8.remi => zstd-1.4.2-1.el8 (EPEL) => zstd-1.4.2-2.el8 (RHEL 8.2) => zstd-1.4.4-1.el8 (RHEL 8.3) 

This list is not yet exhaustive, please comment for missing ones

**Comment by kleisauke** [comment]
fwiw, HDF5 seems now be available in EPEL-8 ([#1738844](https://bugzilla.redhat.com/show_bug.cgi?id=1738844)).
```bash
$ dnf update
Error:
 Problem 1: package matio-1.5.7-9.el8.remi.x86_64 requires libhdf5.so.10()(64bit), but none of the providers can be installed
  - package matio-1.5.7-9.el8.remi.x86_64 requires hdf5 = 1.8.20, but none of the providers can be installed
  - cannot install both hdf5-1.10.5-4.el8.x86_64 and hdf5-1.8.20-4.el8.remi.x86_64
  - cannot install the best update candidate for package matio-1.5.7-9.el8.remi.x86_64
  - cannot install the best update candidate for package hdf5-1.8.20-4.el8.remi.x86_64
 Problem 2: cannot install both hdf5-1.10.5-4.el8.x86_64 and hdf5-1.8.20-4.el8.remi.x86_64
  - package vips-full-8.8.3-2.el8.remi.x86_64 requires libhdf5.so.10()(64bit), but none of the providers can be installed
  - package hdf5-devel-1.10.5-4.el8.x86_64 requires libhdf5.so.103()(64bit), but none of the providers can be installed
  - package hdf5-devel-1.10.5-4.el8.x86_64 requires libhdf5_hl.so.100()(64bit), but none of the providers can be installed
  - package hdf5-devel-1.10.5-4.el8.x86_64 requires libhdf5_cpp.so.103()(64bit), but none of the providers can be installed
  - package hdf5-devel-1.10.5-4.el8.x86_64 requires libhdf5_fortran.so.102()(64bit), but none of the providers can be installed
  - package hdf5-devel-1.10.5-4.el8.x86_64 requires libhdf5_hl_cpp.so.100()(64bit), but none of the providers can be installed
  - package hdf5-devel-1.10.5-4.el8.x86_64 requires libhdf5hl_fortran.so.100()(64bit), but none of the providers can be installed
  - package hdf5-devel-1.10.5-4.el8.x86_64 requires hdf5(x86-64) = 1.10.5-4.el8, but none of the providers can be installed
  - cannot install the best update candidate for package vips-full-8.8.3-2.el8.remi.x86_64
  - cannot install the best update candidate for package hdf5-devel-1.8.20-4.el8.remi.x86_64
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

**Comment by remicollet** [comment]
@kleisauke thanks for the report.

**matio** added to the list, and rebuild against **hdf5** frrom EPEL
**vips** also rebuild.

**Comment by der-eismann** [comment]
I tried installing `php73-php-pecl-mongodb` today, but I was unable to find `zstd` anywhere. Was it removed from EPEL?

**Comment by der-eismann** [comment]
Alright, just found this issue:
https://bugzilla.redhat.com/show_bug.cgi?id=1806759
This is highly problematic als CentOS 8 users are unable to install any of the extensions until CentOS 8.2 is released. Switching to Stream or downloading the Stream RPMs is not really an alternative.

**Comment by remicollet** [comment]
Indeed, **zstd** have been removed from EPEL as it is now part of **RHEL 8.2**

So, waiting for **CentOS 8.2** I have uploaded zstd-1.4.2-1 to the repositoy (by design with a lower version than RHEL which have 1.4.2-2)

**Comment by der-eismann** [comment]
That's awesome, thanks!

**Comment by LanmanGroup** [comment]
I'm on Oracle Linux 8, I already have `epel-modular`, `remi-modular` and `remi-safe` installed and enabled, but I'm getting these errors:
```
$ sudo yum install php-imap
....
Error: 
 Problem: cannot install the best candidate for the job
  - nothing provides libc-client.so.2007()(64bit) needed by php-imap-7.4.16-1.el8.remi.x86_64
```

```
$ sudo yum install php-tidy
....
Error: 
 Problem: cannot install the best candidate for the job
  - nothing provides libtidy.so.5()(64bit) needed by php-tidy-7.4.16-1.el8.remi.x86_64
```

**Comment by remicollet** [comment]
@LanmanGroup you need [uw-imap](https://rpms.remirepo.net/rpmphp/zoom.php?rpm=uw-imap) which is in EPEL.

**Comment by LanmanGroup** [comment]
> @LanmanGroup you need [uw-imap](https://rpms.remirepo.net/rpmphp/zoom.php?rpm=uw-imap) which is in EPEL.
> 
> P.S. and probably out-of-topic on this issue

I found this thread: https://forum.remirepo.net/viewtopic.php?id=3906  and next this issue. 
I have the same problem but with php 7.4. Is it out of topic?

**Comment by remicollet** [comment]
When I say out of topic, it is because this issue is for missing packages, and uw-imap is really in EPEL, so not missing.

As already said, you need "**epel**" repository to be enabled (not only "**epel-modular**").
Such issue won't happen following the [wizard](https://rpms.remirepo.net/wizard/) instructions...

**Comment by LanmanGroup** [comment]
The problem wasn't `uw-imap` or missing packages (**epel** was enabled). I solved with
```
sudo yum clean all
sudo rpm --rebuilddb
```

**Comment by sergiomb2** [comment]
you should use dnf instead yum

**Comment by remicollet** [comment]
Closing as not really anymore activity on EL-8 side
