### ISSUE TITLE
Why dropped support Argon2 on PHP 7.4 package?

### ISSUE THREAD

**Issue by fetus-hina** [remicollet/remirepo#132]
Thank you for providing a very useful project.

I using Argon2i/id password hashing algorithm in my application.
After upgrade to PHP 7.4 (remi-safe), my app stopped work (can't log in to the app).
I looked into it, and it seems that PHP 7.4 is not built with Argon2.

```
# CentOS 7 x64

$ scl enable php73 -- php -r 'var_dump(PHP_VERSION, PASSWORD_ARGON2I);'
string(6) "7.3.12"
int(2)

$ scl enable php74 -- php -r 'var_dump(PHP_VERSION, PASSWORD_ARGON2I);'
PHP Warning:  Use of undefined constant PASSWORD_ARGON2I - assumed 'PASSWORD_ARGON2I' (this will throw an Error in a future version of PHP) in Command line code on line 1
string(5) "7.4.0"
string(16) "PASSWORD_ARGON2I"
```

According to Git history, it appears `--without-argon2` was added in commit `18689b6` ("update to 7.4.0RC1").

Have you any plans to support Argon2 again?

**Comment by remicollet** [comment]
Install php-sodium package

argon2 password can be provides by both standard and sodium extension
sodium extension  is better (faster) and reduce dependency

**Comment by remicollet** [comment]
Additionnal notice:

On Fedora and EL-8, this extension is automatically pulled (Recommends)
EL 6 and 7 don't support weak depdencies

**Comment by fetus-hina** [comment]
Thanks a lot!
It working after install the extension!
