### ISSUE TITLE
redis 6.0

### ISSUE THREAD

**Issue by remicollet** [remicollet/remirepo#133]
Redis **6.0-RC1** is released

Read the [Release Notes](https://raw.githubusercontent.com/antirez/redis/6.0-rc1/00-RELEASENOTES)

**Comment by remicollet** [comment]
Package version 6.0~RC1 are available

* Fedora, RHEL / CentOS 6 or 7: in the **remi-test** repository

```
yum --enablerepo=remi-test update redis
```


* RHEL / CendOS 8: in the **remi-modular-test** repository, in the new **redis:remi-6.0** stream

```
dnf module reset redis
dnf --enablerepo=remi-modular-test module enable redis:remi-6.0
dnf --enablerepo=remi-modular-test update
```

**Comment by Venorcis** [comment]
Awesome! However, one of the main new features is TLS support, which does not seem enabled in this build :( See https://redis.io/topics/encryption and e.g. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=951255

**Comment by remicollet** [comment]
Good catch, indeed, I missed the needed change

Fixed by https://git.remirepo.net/cgit/rpms/redis.git/commit/?id=1460f8a9f4258e12056f7d36e8431217ae2d3839

Version **6.0~RC1-2** will be soon in the _testing_ repository

**Comment by remicollet** [comment]
As this feature requires `openssl >= 1.0.2`, it won't be available on **EL-6** (which is close to its EOL)

Version **6.0~RC1-2** is now in the _testing_ repository

**Comment by Venorcis** [comment]
Great! The SSL config options indeed work now.

I am, however, having some problem running this Redis 6 as a service on CentOS 8. Running it from the command line works fine (i.e. /usr/bin/redis-server /etc/redis.conf), but running it as a service (i.e. systemctl start redis) always gives the following error: "systemd[1]: redis.service: Failed with result 'protocol'." There is nothing of interest in the Redis logs (besides just "Received SIGTERM scheduling shutdown" right after "Ready to accept connections").

I do not get this error using the latest Redis 5 and a nearly identical configuration.

**Comment by remicollet** [comment]
Sadly I cannot reproduce on C8, using stock configuration:

```
[root@centos8 ~]# service redis start
Redirecting to /bin/systemctl start redis.service
[root@centos8 ~]# service redis status
Redirecting to /bin/systemctl status redis.service
● redis.service - Redis persistent key-value database
   Loaded: loaded (/usr/lib/systemd/system/redis.service; disabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/redis.service.d
           └─limit.conf
   Active: active (running) since Tue 2020-03-03 15:13:38 CET; 1s ago
 Main PID: 3139 (redis-server)
   Status: "Ready to accept connections"
    Tasks: 5 (limit: 26213)
   Memory: 7.3M
   CGroup: /system.slice/redis.service
           └─3139 /usr/bin/redis-server 127.0.0.1:6379

mars 03 15:13:38 centos8 systemd[1]: Starting Redis persistent key-value database...
mars 03 15:13:38 centos8 systemd[1]: Started Redis persistent key-value database.
[root@centos8 ~]# redis-cli 
127.0.0.1:6379> info server
# Server
redis_version:5.9.101
...
```

You should try with SElinux in permissive mode to detect any AVC raised

**Comment by Venorcis** [comment]
It seems that setting 'daemonize yes' is the culprit. It's probably not even needed, but still strange that this behaviour changed from Redis 5>6 in combination with systemd only.

**Comment by remicollet** [comment]
hmm..., this option should be ignored, as run with  `--supervised systemd`

**Comment by Venorcis** [comment]
> hmm..., this option should be ignored, as run with `--supervised systemd`

It seems that their default systemd service file has changed a bit, explicitly setting --daemonize no in combination with the supervised flag. See https://github.com/antirez/redis/blob/6.0/utils/systemd-redis_server.service

**Comment by remicollet** [comment]
Fixed by https://git.remirepo.net/cgit/rpms/redis.git/commit/?id=eb5141ea19f580d806fc0e0fe3ef079c82339301

BTW, this should not be needed, daemonize + supervised doesn't make sense.... should be checked by redis-server... perhaps worth an upstream bug report.

**Comment by Venorcis** [comment]
I did some tests and everything seems to be working fine now for me 😁 Thanks for the super-quick updates!

**Comment by remicollet** [comment]
Packages version **6.0~RC2** are available

**Comment by remicollet** [comment]
Packages version **6.0~RC3** are available

**Comment by remicollet** [comment]
Packages version **6.0~RC4** are available

Should be the latest RC before GA in 2 weeks

**Comment by remicollet** [comment]
Packages version **6.0.0** are available in **stable** repository.

**Comment by vaibhaw-** [comment]
@remicollet Remi, there is a new version out on May 22 which says that the Redis version is 6.0.4. However, the latest Redis release is still 6.0.3 from May 16th as seen by the branches and release notes at https://github.com/antirez/redis/tree/6.0

What is the diff between the releases you did on May 16 and May 22 then?
Thanks.

**Comment by remicollet** [comment]
Indeed, very strange.
6.0.4 was tagged on May 22th, but was deleted later...

**Comment by remicollet** [comment]
6.0.4 removed from the repo, 6.0.3 is back

**Comment by vaibhaw-** [comment]
@remicollet Thanks much! :) 

Looks like these guys are stilling discussing the merits of whatever they were doing on May 22 - https://github.com/antirez/redis/pull/7320

Thanks again. 👍

**Comment by vaibhaw-** [comment]
@remicollet Remi,

For your reference -

1. The redis-sentinel service in the present form is currently broken on 6.0.x. See https://github.com/antirez/redis/issues/7284 So unless the Redis guys chose to fix it, please consider setting the type to simple in redis-sentinel.service.

2. From the Redis code, it seems that the start behavior for the replicas (slaves) has changed as well. Replicas (slaves) notify systemd when:
1) a partial resync request has been accepted (this should be fairly quick)
2) Or if the full resync from the master is complete and the system is not ready to accept connections. 

Case #2 will take time on large systems so it makes sense to have reasonably long timeouts in the config file now. The Redis guys seem to be setting it to infinity on their setup. https://github.com/antirez/redis/blob/6.0/utils/systemd-redis_server.service

They also have a warning now when they see that the setup is being supervised by systemd -
`9441:X 27 May 2020 14:00:24.017 # WARNING supervised by systemd - you MUST set appropriate values for TimeoutStartSec and TimeoutStopSec in your service unit.`


I haven't tested this slave full resync case yet but from the code, it looks like it might be a problem.

Thanks.

**Comment by remicollet** [comment]
@vaibhaw- great thanks for the links 

BTW, can you please avoid comment on closed issue, and prefer new one so the bug will be properly tracked ?

**Comment by vaibhaw-** [comment]
Sure, will do. Thanks.

**Comment by remicollet** [comment]
btw, 6.0.3-3 should fix the sentinel issue

As "infinity" value seems crazy, I simply add some comment in the limit.conf file, which is under admin control.

**Comment by vaibhaw-** [comment]
Wow, you fixed it! Thanks. 😄 
Fair value of the timeout too. 

Meanwhile, in the last 30 mins - 6.0.4 is out - https://groups.google.com/forum/#!topic/redis-db/khX1rRYLZog  🙄

**Comment by remicollet** [comment]
And 6.0.4 is already in the repo ;)
https://git.remirepo.net/cgit/rpms/redis.git/commit/?id=e7797a5096db493b6e971a92a1bc5f89ac92b3ac

**Comment by vaibhaw-** [comment]
You da man! 🙏 😄
