### ISSUE TITLE
rebuild php74-php-pecl-gearman to latest master

### ISSUE THREAD

**Issue by prupert** [remicollet/remirepo#139]
The current gearman PECL extension in the Remi repository (`php74-php-pecl-gearman-2.0.6-1.el7.remi.x86_64`) is causing segmentation faults on PHP 7.4 installations. 

The underlying bug has been fixed upstream, see https://github.com/wcgallego/pecl-gearman/pull/74

Please rebuild the extension with the latest fixes from the master branch on https://github.com/wcgallego/pecl-gearman and publish updated packages in the Remi repositories to prevent crashes when using the Gearman extension on PHP 7.4.

**Comment by remicollet** [comment]
Please ask upstream to release a new version ;)

**Comment by prupert** [comment]
Will do!

But we saw this commit yesterday which suggests no new release is coming soon:
https://github.com/wcgallego/pecl-gearman/commit/a787fa0ca5ff5ab4abc30d440ddfc77eea55b825
"Note: This is no longer under active development. If you'd like to pick up development as caretaker for the pecl-gearman project, please do so! I'd be happy to offer a redirect to anyone looking to be a better custodian than I have the last few years :)"

**Comment by remicollet** [comment]
Fixed by https://git.remirepo.net/cgit/rpms/php/pecl/php-pecl-gearman.git/commit/?id=8218b4b7f40656152a4ca04152f315ee2cec119c

**Comment by remicollet** [comment]
Version **2.0.6-2** upload to the repository, and includes this fix.

**Comment by remicollet** [comment]
Else, for test: [php74-php-pecl-gearman-2.0.6-2.el7.remi.x86_64.rpm](https://rpms.remirepo.net/enterprise/7/safe/x86_64/php74-php-pecl-gearman-2.0.6-2.el7.remi.x86_64.rpm)

**Comment by prupert** [comment]
Awesome work, Remi! Thank you.
