### ISSUE TITLE
Sorry, but PHP version older than Array are not available

### ISSUE THREAD

**Issue by jamieburchell** [remicollet/remirepo#140]
There's a bug in the wizard printing "Array" in the output.

![Capture](https://user-images.githubusercontent.com/3270426/74932027-cb797f00-53d8-11ea-8a26-65f768ce7b2c.PNG)

**Comment by remicollet** [comment]
Thanks for the report

Fixed by https://git.remirepo.net/cgit/web/rpms.git/commit/?id=329de2c52ed2405f28fcb403f3994d2b1c26d620
