### ISSUE TITLE
Mismatch in libxml versions in php73-php-7.3.15-1.el6

### ISSUE THREAD

**Issue by rogersd** [remicollet/remirepo#141]
Hi,

I'm installing PHP 7.3 on Amazon Linux from your repo, and I'm getting a mismatch in the version of libxml being reported by phpinfo():

![Screen Shot 2020-02-25 at 4 13 33 PM](https://user-images.githubusercontent.com/260826/75288200-d291fa00-57e9-11ea-84c4-7740260fb9fe.png)

As you can see the "Compiled Version" is 2.7.6, but the "Loaded Version" is 20901

By comparison, on our PHP 7.2 install (using Amazon's RPMs), these both show version 2.9.1:

![Screen Shot 2020-02-25 at 4 14 51 PM](https://user-images.githubusercontent.com/260826/75288274-02d99880-57ea-11ea-8cbb-e70d25c1e0cf.png)

This is causing a PHP warning when trying to use features from the new version of libxml:

`PHP Warning:  Use of undefined constant LIBXML_HTML_NODEFDTD - assumed 'LIBXML_HTML_NODEFDTD' (this will throw an Error in a future version of PHP)`

Could you please take a look at why this is the case?

Thanks.

**Comment by remicollet** [comment]
My packages are built against RHEL and official packages

So using libxml2-**2.7.6** for RHEL-6 and libxml2-**2.9.1** for RHEL-7 and libxml2 **2.9.7** for RHEL-8

I obviously cannot change this (or will break all real RHEL or CentOS user installation)

So looks like you are using an old **amzn1** dsitribution
You should try with an **amzn2** one

**Comment by remicollet** [comment]
**Ugly** workaround:

```
if (LIBXML_LOADED_VERSION >= 20708 && !defined("LIBXML_HTML_NODEFDTD")) 
   define("LIBXML_LOADED_VERSION", 4);
```

**Comment by rogersd** [comment]
Thanks for the workaround, worked great for us!
