### ISSUE TITLE
EPEL-8 testing packages for official PHP streams

### ISSUE THREAD

**Issue by remicollet** [remicollet/remirepo#143]
Because of [EPEL issue #75](https://pagure.io/epel/issue/75) some of the extensions usually found in EPEL are missing.

Waiting for infrastructure to be ready, first workaround is to use [my repository](https://rpms.remirepo.net/wizard/). second is to use official streams and try some test builds which are available:

* for [php:7.2](https://rpms.remirepo.net/temp/epel-8-php-7.2/)
* for [php:7.3](https://rpms.remirepo.net/temp/epel-8-php-7.3/)
* for [php:7.4](https://rpms.remirepo.net/temp/epel-8-php-7.4/)

This is NOT a repository.

Feel free to ask for other extensions here.

**Comment by fkooman** [comment]
Is there an easy way to integrate this (or remi repo) in mock? I'm building my PHP packages in mock environment and depend heavily on `php-sodium` (or `php-pecl-libsodium`) and also PHPUnit which is used in `%test` during build. Everything works great on EL7 and all versions of Fedoras...

**Comment by remicollet** [comment]
@fkooman yes, you can, see all the mock configuration I use in https://git.remirepo.net/cgit/tools/mock.git/

**Comment by remicollet** [comment]
Improvements:

* https://rpms.remirepo.net/temp/epel-8-php-7.2/ can now be used as a flat repository
* https://rpms.remirepo.net/temp/epel-8-php-7.3/  can now be used as a flat repository
* https://rpms.remirepo.net/temp/epel-8-modular/ can now be used as a modular repository, providing **php-extras** module, with 2 streams: **7.2** an **7.3**

Of couse **php-extras:7.3** requires **php:7.3** and **php-extras:7.2** requires **php:7.2**.

**Comment by remicollet** [comment]
Available extensions:

1. apcu_bc
2. ast
3. http
4. igbinary
5. imap
6. interbase
7. memcache
8. memcached
9. mongodb
10. msgpack
11. pdo_dblib
12. pdo_firebird
13. propro
14. psr
15. raphf
16. redis
17. uuid
18. xdebug
19. pspell
20. sodium
21. tidy
22. zstd

**Comment by remicollet** [comment]
Temporary repository configuration : [epel-temp.repo](https://rpms.remirepo.net/temp/epel-temp.repo)

**Comment by fkooman** [comment]
> @fkooman yes, you can, see all the mock configuration I use in https://git.remirepo.net/cgit/tools/mock.git/

Sorry for bothering you again, but I'm still not 100% sure how to use this... to get both access to e.g. php-sodium and PHPUnit. It seems those mock configs point to local directories and not (remote) repositories. Do I have to copy the packages first to my build server? Which of those `.cfg` files in https://git.remirepo.net/cgit/tools/mock.git/tree/ should I use that will most closely match what will be in el8 when it becomes available?

**Comment by remicollet** [comment]
**epel872** and **epel873** are the configurations used to build php extensions only using RHEL + EPEL. But this configuration doesn't include any noarch packages which are in the "remi" repository only for now.

>  It seems those mock configs point to local directories and not (remote) repositories.

Yes, for performance, but online exists with the same content

`file:/home/rpmbuild/site/rpms/` => `https://rpms.remirepo.net/`

**Comment by bertusdebruin** [comment]
> Feel free to ask for other extensions here.
@remicollet Hereby the request for PHP YAML as extension.
Thanks.

**Comment by remicollet** [comment]
@bertusdebruin EPEL-8 branches requested, will build the package as soon as created.
* https://pagure.io/releng/fedora-scm-requests/issue/25955
* https://pagure.io/releng/fedora-scm-requests/issue/25956

**Comment by bertusdebruin** [comment]
> @bertusdebruin EPEL-8 branches requested, will build the package as soon as created.
> 
> * https://pagure.io/releng/fedora-scm-requests/issue/25955
> * https://pagure.io/releng/fedora-scm-requests/issue/25956

Seems to be created and ready to rumble. Great and fast job. 
Thanks @remicollet and @ignatenkobrain

**Comment by remicollet** [comment]
> Seems to be created

No... only the 7.3 branch, the 7.2 is missing.... :(
BTW, **php-pecl-yaml-2.1.0**-1.epel8 is now available in the temp repo.

**Comment by Blaimi** [comment]
I feel free and ask for the missing `php-pecl-imagick`-package

**Comment by remicollet** [comment]
Sorry, But I don't have enough right to request new branch for this package in EPEL

**Comment by Blaimi** [comment]
Thanks for the answer :) Can I feel free again and ask for `php-pecl-gmagick` :)

**Comment by remicollet** [comment]
Same owner (hubbitus); so same issue....

**Comment by remicollet** [comment]
So, use the streams from my repository where [more (most) extensions](https://blog.remirepo.net/pages/PECL-extensions-RPM-status) are available.

**Comment by remicollet** [comment]
RHEL 8.3 is released and provide **php:7.4** stream.

**php-extras:7.4** stream is now also avalaible

**Comment by remicollet** [comment]
I give up on this one
