### ISSUE TITLE
[7.8] ImageMagick 6.9.10.68-3.el7

### ISSUE THREAD

**Issue by remicollet** [remicollet/remirepo#144]
In RHEL 7.8, **ImageMagick** was updated to **6.9.10.68-3.el7**
Which have the same soname, so which conflicts with ImageMagick6-libs from my repostiory.

So I have to drop it from "remi-safe", but I also need to wait for CentOS 7.8 to be available.

**Comment by remicollet** [comment]
Workaround for now

**1 Cleanup**

    # yum remove ImageMagick6-libs

Keep the list of removed php packages

**2 Update to 7.8**

    # yum update

**3 Reinstall missing extension (list from step 1)**

    # yum install php-pecl-imagick

**Comment by remicollet** [comment]
ImageMagick 6.9.10.68-3.el7 is now also available in the [CentOS CR](https://wiki.centos.org/AdditionalResources/Repositories/CR) repository.

**Comment by remicollet** [comment]
Proper way (without "remi", only "remi-safe")
```
# yum shell
> remove ImageMagick6-libs
> install ImageMagick
>  run
```

Alternative way with "remi" to get latest ImageMagick version
```
# yum --enablerepo=remi install ImageMagick
```

**Comment by daan-b** [comment]
It seems that vips-devel is still build against ImageMagick6-devel 

 Processing Dependency: ImageMagick6-devel for package: vips-devel-8.9.1-1.el7.remi.x86_64
Package ImageMagick6-devel is obsoleted by ImageMagick-devel, but obsoleting package does not provide for requirements
--> Finished Dependency Resolution
Error: Package: vips-devel-8.9.1-1.el7.remi.x86_64 (remi)
           Requires: ImageMagick6-devel
           Available: ImageMagick6-devel-6.9.11.3-1.el7.remi.x86_64 (remi)
               ImageMagick6-devel = 6.9.11.3-1.el7.remi
           Available: ImageMagick6-devel-6.9.11.6-1.el7.remi.x86_64 (remi)
               ImageMagick6-devel = 6.9.11.6-1.el7.remi

**Comment by remicollet** [comment]
> It seems that vips-devel is still build against ImageMagick6-devel

Indeed (btw, most users don't need this package)

Fixed in new build (vips-8.9.1-3 and vips-full-8.9.1-4)

**Comment by remicollet** [comment]
As **7.8** is now released, old **ImageMagick6** have been removed from the repository.

**Comment by shiz0** [comment]
Thanks for the workaround.
One problem I ran into was reinstalling php56-php-magickwand:
`
Resolving Dependencies
--> Running transaction check
---> Package php56-php-magickwand.x86_64 0:1.0.9.2-14.el7.remi will be installed
--> Processing Dependency: ImageMagick6-libs(x86-64) >= 6.9.9 for package: php56-php-magickwand-1.0.9.2-14.el7.remi.x86_64
--> Finished Dependency Resolution
Error: Package: php56-php-magickwand-1.0.9.2-14.el7.remi.x86_64 (remi-safe)
           Requires: ImageMagick6-libs(x86-64) >= 6.9.9
`
Not too much of an issue, as I think I don't have anything running under php56 anymore anyway, but wanted to let you know.

**Comment by remicollet** [comment]
@shiz0 new build uploaded.

BTW, this extension should be avoided, this is a deprecated extension (use **imagick** instead).

**Comment by shiz0** [comment]
Thank you!
I'll see if I can replace it (or leave deinstalled), it's probably a left over dependency of some long gone vhost.
