### ISSUE TITLE
Wrong permissions for /etc/logrotate.d/roundcubemail

### ISSUE THREAD

**Issue by shodanshok** [remicollet/remirepo#145]
When running logrotate after having installed/upgraded `roundcubemail`, the following error is returned:

```
Potentially dangerous mode on roundcubemail: 0664
error: Ignoring roundcubemail because it is writable by group or others.
```

Indeed, the permissions include group-write: 
`-rw-rw-r--. 1 root root 107 Mar 24  2017 /etc/logrotate.d/roundcubemail`

To fix the error one must issue the following command: 
`chmod g-w /etc/logrotate.d/roundcubemail`

However at the next update the group-writable bit would be set again, causing `logrotate` to complain again. To avoid the error, the RPM package should be modified to `chmod` the file disabling group write permission.

**Comment by remicollet** [comment]
Thanks for the report.

Fixed by: https://git.remirepo.net/cgit/rpms/roundcubemail.git/commit/?id=304bde86048ca25ebd916122f6c4065c1251fcc1

New build (1.4.4-2) is now available in the repository

**Comment by shodanshok** [comment]
It seems to work OK now:
`-rw-r--r--. 1 root root 107 Mar 24  2017 /etc/logrotate.d/roundcubemail`

Thank you for the fast response (and for your repo!)
