### ISSUE TITLE
Update request: icu62 to v62.2 to support Japanese new era Reiwa

### ISSUE THREAD

**Issue by fetus-hina** [remicollet/remirepo#149]
Japan began using [the new era "令和 (Reiwa)"](https://en.wikipedia.org/wiki/Reiwa) on May 1, 2019 (an year ago).  
The ICU project released v62.2 on April 12, 2019 to support it.

"Today" is "令和2年5月7日 (R2/05/07, May 7, Reiwa 2)". But the following code with the current package returns an incorrect result:
```php
<?php

$locales = [
    'ja_JP.UTF-8@calendar=japanese',
    'en_US.UTF-8@calendar=japanese',
];

foreach ($locales as $locale) {
    $dateFmt = IntlDateFormatter::create(
        $locale,
        IntlDateFormatter::FULL, // date type
        IntlDateFormatter::NONE, // time type
        'Asia/Tokyo', // timezone
        IntlDateFormatter::TRADITIONAL // use non-gregorian calendar
    );

    echo $dateFmt->format(strtotime('2020-05-07T12:00:00+09:00')) . "\n";
}
```

results with libicu62-62.1-3.el7.remi.x86_64 (and php-intl):
```
平成32年5月7日木曜日
Thursday, May 7, 32 Heisei
```

"平成32年 (Heisei 32)" is invalid and it should be:
```
令和2年5月7日木曜日
Thursday, May 7, 2 Reiwa
```

Currently, most systems in Japan are developed using the Gregorian calendar (i.e., "2020" now).  
However, a small number of systems (e.g., government-releated) use the Japanese calendar (gengo), and some people prefer to use it.

This request is like an update "tzdata" database (typically, DST rule updates), which is necessary for the Japanese.
If it's not updated, the Japanese will be forced to deal with a complex and bizarre response like below:
```php
<?php

date_default_timezone_set('Asia/Tokyo');
$time = strtotime('2020-05-07T12:00:00+09:00'); // from database, in real world code
$y = (int)date('Y', $time);
$m = (int)date('n', $time);
$d = (int)date('j', $time);

if ($y >= 2019 && $m >= 5 && $d >= 1) {
    printf("R%d/%02d/%02d\n", $y - 2018, $m, $d); // Reiwa, 248th era
} elseif ($y >= 1989 && $m >= 1 && $d >= 8) {
    printf("H%d/%02d/%02d\n", $y - 1988, $m, $d); // Heisei
} elseif ($y >= 1926 && $m >= 12 && $d >= 25) {
    printf("S%d/%02d/%02d\n", $y - 1925, $m, $d); // Showa
} elseif ($y >= 1912 && $m >= 7 && $d >= 30) {
    printf("T%d/%02d/%02d\n", $y - 1911, $m, $d); // Taisho
} elseif ($y >= 1868 && $m >= 10 && $d >= 23) {
    printf("M%d/%02d/%02d\n", $y - 1867, $m, $d); // Meiji
} else {
    // ... and more
}
```

**Comment by remicollet** [comment]
Make sense, and doable as a minor version only update.

Fixed by https://git.remirepo.net/cgit/rpms/lib/icu-last.git/commit/?id=f62e790469c583788c9de4ec0e7b9d375698737a

**Comment by remicollet** [comment]
version 62.2-1 is now available in the repository for EL-7 and EL-8 (and in all mirrors in a few hours)

Feedback welcome.

BTW, in the future, I will probably have to fix PHP packages to use a more recent version (perhaps 65 from F32)

**Comment by fetus-hina** [comment]
The new version of libicu62 package looks work collectly.
Thank you very much!
