### ISSUE TITLE
VIPS on Amazon Linux Ami 2

### ISSUE THREAD

**Issue by andrefelipe** [remicollet/remirepo#151]
Hello Remi, this is recurring help to install Vips on Amazon Linux AMI 2, previously at https://github.com/libvips/libvips/issues/1184

Again, I have trouble installing LibVIPS, now with the error:
```
Error: Package: vips-full-8.9.2-2.el7.remi.x86_64 (remi-safe)
           Requires: libMagickCore-6.Q16.so.6()(64bit)
```

First, I don't mean to take any more of your valuable time, do you think is there a permanent solution for this? Maybe forget about Amazon Linux AMI 2?

All my requirement is to install VIPS Full and PHP Pecl Vips, that's all. Maybe there is a way to circumvent the issue?

For reference, here is your install code used

```
FROM amazonlinux:2

RUN yum update -y

# Import archive signing keys and update packages
RUN rpm --import https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7 && \
    rpm --import https://rpms.remirepo.net/RPM-GPG-KEY-remi && \
    rpmkeys --import file:///etc/pki/rpm-gpg/RPM-GPG-KEY-amazon-linux-2 && \
    yum update -y

RUN yum install -y yum-utils

RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && \
    yum install -y https://rpms.remirepo.net/enterprise/remi-release-7.rpm && \
    yum-config-manager --enable remi-php73 && \
    yum install -y https://download1.rpmfusion.org/free/el/rpmfusion-free-release-7.noarch.rpm && \
    rpmkeys --import file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-el-7 && \
    yum install -y --setopt=tsflags=nodocs --noplugins \
        vips-full-tools php-cli php-pecl-vips && \
    yum clean all

RUN vips --version && php --modules && php --version
```

Thanks a lot in advance

**Comment by remicollet** [comment]
until recently (before EL 7.8) this library was provided by ImageMagick-libs in "remi-safe", but as 7.8 provides this version I had to remove it from the repository (as by design "remi-safe" should not replace package avaiable in the distro).
See issue #144 

So, you have to enable "remi" which provides this library (but which is not a "safe" repository, as it replace various packages from the distro)

**Comment by andrefelipe** [comment]
Great, it worked indeed. Just run:
`yum-config-manager --enable remi`

Thank you very much!

**Comment by AdamT213** [comment]
Trying to use the same script (but in a .ebextenstions file) to install just vips (no php): 

`commands:
  install_vips:
    command: |
      yum update -y
      rpm --import https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
      rpm --import https://rpms.remirepo.net/RPM-GPG-KEY-remi
      rpmkeys --import file:///etc/pki/rpm-gpg/RPM-GPG-KEY-amazon-linux-2
      yum update -y
      yum install -y yum-utils
      yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      yum install -y https://rpms.remirepo.net/enterprise/remi-release-7.rpm
      yum-config-manager --enable remi
      yum install -y https://download1.rpmfusion.org/free/el/rpmfusion-free-release-7.noarch.rpm
      rpmkeys --import file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-el-7
      yum install -y --setopt=tsflags=nodocs --noplugins vips-full-tools
      yum clean all
      vips --version`

Yields a whole host of errors: 

`Error: Package: vips-full-tools-8.9.2-2.el7.remi.x86_64 (remi)
  Requires: liborc-0.4.so.0()(64bit)
  Error: Package: vips-full-tools-8.9.2-2.el7.remi.x86_64 (remi)
  Requires: librsvg-2.so.2()(64bit)
  Error: Package: vips-full-tools-8.9.2-2.el7.remi.x86_64 (remi)
  Requires: libIlmImf.so.7()(64bit)
  Error: Package: vips-full-tools-8.9.2-2.el7.remi.x86_64 (remi)
  Requires: libIex.so.6()(64bit)
  Error: Package: vips-full-8.9.2-2.el7.remi.x86_64 (remi)
  Requires: libIlmImf.so.7()(64bit)
  Error: Package: openslide-3.4.1-1.el7.x86_64 (epel)
  Requires: libgdk_pixbuf-2.0.so.0()(64bit)
  Error: Package: vips-full-8.9.2-2.el7.remi.x86_64 (remi)
  Requires: libHalf.so.6()(64bit)
  Error: Package: vips-full-8.9.2-2.el7.remi.x86_64 (remi)
  Requires: libgdk_pixbuf-2.0.so.0()(64bit)
  Error: Package: vips-full-tools-8.9.2-2.el7.remi.x86_64 (remi)
  Requires: libHalf.so.6()(64bit)
  Error: Package: vips-full-8.9.2-2.el7.remi.x86_64 (remi)
  Requires: liborc-0.4.so.0()(64bit)
  Error: Package: vips-full-tools-8.9.2-2.el7.remi.x86_64 (remi)
  Requires: libgdk_pixbuf-2.0.so.0()(64bit)
  Error: Package: vips-full-8.9.2-2.el7.remi.x86_64 (remi)
  Requires: librsvg-2.so.2()(64bit)
  Error: Package: openslide-3.4.1-1.el7.x86_64 (epel)
  Requires: libopenjpeg.so.1()(64bit)
  Error: Package: vips-full-tools-8.9.2-2.el7.remi.x86_64 (remi)
  Requires: libpng15.so.15()(64bit)
  Error: Package: vips-full-8.9.2-2.el7.remi.x86_64 (remi)
  Requires: libImath.so.6()(64bit)
  Error: Package: vips-full-tools-8.9.2-2.el7.remi.x86_64 (remi)
  Requires: libgsf-1.so.114()(64bit)
  Error: Package: openslide-3.4.1-1.el7.x86_64 (epel)
  Requires: libpng15.so.15()(64bit)
  Error: Package: vips-full-8.9.2-2.el7.remi.x86_64 (remi)
  Requires: libIlmThread.so.6()(64bit)
  Error: Package: vips-full-8.9.2-2.el7.remi.x86_64 (remi)
  Requires: libgsf-1.so.114()(64bit)
  Error: Package: libheif-1.3.2-2.el7.x86_64 (rpmfusion-free-updates)
  Requires: libpng15.so.15()(64bit)
  Error: Package: libheif-1.3.2-2.el7.x86_64 (rpmfusion-free-updates)
  Requires: libpng15.so.15(PNG15_0)(64bit)
  Error: Package: vips-full-8.9.2-2.el7.remi.x86_64 (remi)
  Requires: libIexMath.so.6()(64bit)
  Error: Package: openslide-3.4.1-1.el7.x86_64 (epel)
  Requires: libpng15.so.15(PNG15_0)(64bit)
  Error: Package: vips-full-tools-8.9.2-2.el7.remi.x86_64 (remi)
  Requires: libIlmThread.so.6()(64bit)
  Error: Package: vips-full-8.9.2-2.el7.remi.x86_64 (remi)
  Requires: libpng15.so.15()(64bit)
  Error: Package: vips-full-tools-8.9.2-2.el7.remi.x86_64 (remi)
  Requires: libImath.so.6()(64bit)
  Error: Package: vips-full-8.9.2-2.el7.remi.x86_64 (remi)
  Requires: libpng15.so.15(PNG15_0)(64bit)
  Error: Package: vips-full-tools-8.9.2-2.el7.remi.x86_64 (remi)
  Requires: libIexMath.so.6()(64bit)
  Error: Package: vips-full-8.9.2-2.el7.remi.x86_64 (remi)
  Requires: libIex.so.6()(64bit)
  You could try using --skip-broken to work around the problem
  You could try running: rpm -Va --nofiles --nodigest
`

It seems none of the dependencies are resolved. Is there any glaring reason why this could not work?

**Comment by remicollet** [comment]
> It seems none of the dependencies are resolved. Is there any glaring reason why this could not work?

Bad base image ?
