### ISSUE TITLE
Request: pdlib

### ISSUE THREAD

**Issue by MAngel666** [remicollet/remirepo#152]
It would be nice to have pdlib in remi repo :)
https://github.com/goodspb/pdlib
It is used of nextcloud face recognition module...

TiA
Greetz

**Comment by remicollet** [comment]
**dlib-19.10** is available in the repository.
The build includes a workaround for [Broken pkg-config file](https://github.com/davisking/dlib/issues/2111)

**php-pdlib-1.0**-1.20200620git45c0b7 is also available.
Various PR are open, and waiting for uptream feedback

* [fix linker command](https://github.com/goodspb/pdlib/pull/25) (merged)
* [fix tests skip condition](https://github.com/goodspb/pdlib/pull/26) (merged)
* [display extension and library version in phpinfo](https://github.com/goodspb/pdlib/pull/27)
* [Fix build and PHP 8 compat.](https://github.com/goodspb/pdlib/pull/29)

Also waiting for e new tag, see [Release 1.0.1 ](https://github.com/goodspb/pdlib/issues/28)


Test and feedback welcome

**Comment by MAngel666** [comment]
working good with nextcloud :) 2 days - no problems...

**Comment by remicollet** [comment]
Great :)
Thanks for the feedback
