### ISSUE TITLE
Update request: icu65+

### ISSUE THREAD

**Issue by kynx** [remicollet/remirepo#153]
Hi Remi. You [previously](https://github.com/remicollet/remirepo/issues/149#issuecomment-625074740) mentioned bumping the ICU version to something more recent.

We're getting grief over the number of decimal places for the IDR currency:

```
$f = new NumberFormatter('en_GB', NumberFormatter::CURRENCY);
$s = $f->formatCurrency(123.45, 'IDR');
var_dump($s);
// string(8) "IDR 123"
```

The correct output (ICU64+) is "IDR 123.45" (which is also what JS's `Intl.NumberFormatter` displays in browsers).

It'd be great to see an update!

Many thanks for all the hard work.

**Comment by botzkobg** [comment]
+1

**Comment by remicollet** [comment]
I usually only update such dependencies before a PHP RC versions

So will be for 7.3.21RC1, 7.4.9RC1 and 8.0.0alpha3 in ~3 weeks

**Comment by kynx** [comment]
Awesome :) Thanks!

**Comment by remicollet** [comment]
WIP: https://git.remirepo.net/cgit/rpms/lib/icu-last.git/commit/?id=b2566771ca22c2659e63357cfaa1f58d0f429d45

Note to myself: also need a php-pecl-http rebuild.

**Comment by remicollet** [comment]
libicu65 is now available in the repository, and is already used by PHP 8.0.0alpha2

Other versions will use it with next RCs

**Comment by remicollet** [comment]
I just uploaded **7.3.21RC1**, 7**.4.9RC1** and **8.0.0alpha3**, which use ICU **65.1**
```
$ php --ri intl

intl

Internationalization support => enabled
ICU version => 65.1
ICU Data version => 65.1
ICU TZData version => 2019c
ICU Unicode version => 12.1

Directive => Local Value => Master Value
intl.default_locale => no value => no value
intl.error_level => 0 => 0
intl.use_exceptions => 0 => 0
```

Test and feedback welcome.

**Comment by tdclaritum** [comment]
Hi Remi. 

We have built docker image and have run all our unit tests against **7.3.21RC1**. All passed.

Thank you for your work.

**Comment by remicollet** [comment]
@tdclaritum thanks for the feedback


All new builds now use libicu version 65.1

* 5.6.40-22
* 7.0.33-22
* 7.1.33-9
* 7.2.33-1
* 7.3.21-1
* 7.4.9-1
