### ISSUE TITLE
Request: php-awl (Andrew's Web Libraries)

### ISSUE THREAD

**Issue by StudioMaX** [remicollet/remirepo#154]
It is possible to add this package?
Source: https://gitlab.com/davical-project/awl

Short history: in fact, I have no idea what kind of library it is, it seems like a set of some auxiliary php scripts. In fact, this library is a [dependency](https://stash.z-hub.io/projects/ZP/repos/z-push/browse/build/rpm/z-push.spec#96) for [Z-Push](https://z-push.org/). On Debian-like systems this library is known as [`libawl-php`](https://pkgs.org/search/?q=libawl), but it doesn't exist in RHEL repos. Therefore, developers of Z-Push have [compiled this library](https://jira.z-hub.io/browse/ZP-1149?focusedCommentId=11681&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-11681) and distribute it via [their repositories](https://repo.z-hub.io/z-push:/final/RHEL_7/src/) with the main software. But it seems that they just once built one of the old versions of this `php-awl` library and never updated it.

I just realized that this library has a critical vulnerability ([reported to them](https://jira.z-hub.io/browse/ZP-1563)) in their repository. Maybe they will update this library, but I thought it might be worth adding this library to your repository?

**Comment by remicollet** [comment]
Looks like this is only a small PHP library, not an extension.

Sorry I do'nt think this make sense to be in my repository, but should rather be updated in their official repo.
I will make sense of all the z-push stack was packaged.

**Comment by remicollet** [comment]
Closing
