### ISSUE TITLE
gd-last 2.3.0 regression fix

### ISSUE THREAD

**Issue by kstange** [remicollet/remirepo#155]
I recently updated a system which uses gd to the 2.3.0 version from your
repo and discovered there was a regression that is fixed in master.
Given the time between the 2.2.5 and 2.3.0 releases was 3 years, is it
possible you could push an updated gd package that contains this patch,
in case it's another 3 years before gd is next updated?

https://github.com/libgd/libgd/issues/615
https://github.com/libgd/libgd/commit/3dd0e308cbd2c24fde2fc9e9b707181252a2de95

The problem is that textLayout() called with an empty string returns a
failure that bails out on the entire image, which previously was handled
as a no-op.  Rolling back to 2.2.5 is my current workaround.

**Comment by kstange** [comment]
I realized that remi already committed this fix, so this doesn't need to be open.

**Comment by remicollet** [comment]
For memory fixed upstream by https://github.com/libgd/libgd/commit/0be6aec0fe11dce8b8a5674eea5ee23bc700042e

Package fixed by:
https://git.remirepo.net/cgit/rpms/lib/gd.git/commit/?id=963d12f9a31e56cad5d6c68f4d526925887cb28e
