### ISSUE TITLE
php-mbstring-7.4.9-1.el7.remi.x86_64 (remi-php74) requires: libonig.so.105()(64bit)

### ISSUE THREAD

**Issue by tartina** [remicollet/remirepo#157]
libonig.so.105()(64bit) does not exist to my knowledge, latest SONAME is stil libonig.so.5.0.0.
It seems a 10 has been added by mistake, but I can't find where it is.

**Comment by remicollet** [comment]
Expected to allow parallel installation with system old oniguruma.

You need **oniguruma5php** from remi-safe which is enabled by default.

**Comment by tartina** [comment]
Thanks, I usually enable your repositories manually and I forgot to enable remi-safe.
