### ISSUE TITLE
Non modular version for PHP 8.0?

### ISSUE THREAD

**Issue by rodehoed** [remicollet/remirepo#160]
We are using a mixed environment of EL7 and EL8 machines managing PHP with puppet. At the moment there is not a good way to manage modules with puppet and the module only rpms a breaking things for us. 

Am I overlooking something? We could rebuild the rpm ourselves and disabling the modules. But what about the pecl extentsions are these also modular?

**Comment by remicollet** [comment]
You can use create a repository (remi-php80) using http://cdn.remirepo.net/enterprise/8/remi/x86_64/mirror for the mirrorlist

As modular is the standard/proper way to install package on EL-8, this is not provided in remi-release package (and no plan to add it)

BTW, really puppet really need to be fixed....

**Comment by rodehoed** [comment]
Yes agree on that. 

But what about the pecl rpms? Are they modular too? If not I could rebuild the main rpm and pull in your pecl extensions as a temp. workaround.

**Comment by remicollet** [comment]
all extensions have dependency on PHP version / API.
So are also in the same repository / stream

**Comment by remicollet** [comment]
Ex: see the content of the php80 repository https://rpms.remirepo.net/enterprise/8/php80/x86_64/repoview/

**Comment by rodehoed** [comment]
> all extensions have dependency on PHP version / API.
> So are also in the same repository / stream

Has this behaviour been changed for the PHP 8.0 builds? Because I just build PHP 7.4 non-modular (based on your srpms) to test something and it was not a problem to install extra php modules where the php 8.0 rpms nag about "No available modular metadata".

**Comment by remicollet** [comment]
> Has this behaviour been changed 

No, this have always exists

```
$ rpm -qp --requires php-pecl-zip-1.19.2-1.el8.remi.8.0.x86_64.rpm
...
php(api) = 20200930-64
php(zend-abi) = 20200930-64
...
```

So an extension build with 7.4 cannot be installed with any other version (and won't work).

**Comment by rodehoed** [comment]
I was referring to that I can build my own PHP 7.4 non-modular rpm and install the php modules (7.4) from your repo. Whereis I build PHP 8.0 non-modular rpm  and I cannot install the extra (8.0) modules from your repo. But guess we have to check if we can get this managed by puppet

**Comment by remicollet** [comment]
Closing as workaround provided, and not a real  issue
