### ISSUE TITLE
Webp support

### ISSUE THREAD

**Issue by chrmah** [remicollet/remirepo#161]
Hello,

we use in one our projects "webp" - if possible. But the application could create/use webp images.

Currently we use the current 7.4 repo. Is there a webp support activated ?
https://www.php.net/manual/en/image.installation.php
https://www.php.net/manual/en/function.imagewebp.php

Testcase:
```
<?php
$file = './example.jpg';
$image = imagecreatefromstring(file_get_contents($file));
ob_start();
imagejpeg($image,NULL,100);
$cont = ob_get_contents();
ob_end_clean();
imagedestroy($image);
$content = imagecreatefromstring($cont);
$output = './example.webp';
imagewebp($content,$output);
imagedestroy($content);
```
Failed with 
> PHP Fatal error:  Call to undefined function imagewebp() in /test.php on line 11

**Comment by remicollet** [comment]
Distro ? version ? arch ? installed packages ?

```
$ php --ri gd

gd

GD Support => enabled
GD headers Version => 2.3.0
GD library Version => 2.3.0
FreeType Support => enabled
FreeType Linkage => with freetype
GIF Read Support => enabled
GIF Create Support => enabled
JPEG Support => enabled
PNG Support => enabled
WBMP Support => enabled
XPM Support => enabled
XBM Support => enabled
WebP Support => enabled
BMP Support => enabled
TGA Read Support => enabled

Directive => Local Value => Master Value
gd.jpeg_ignore_warning => 1 => 1

```

Is **php-gd** installed ?

**Comment by chrmah** [comment]
Repo: http://rpms.remirepo.net/enterprise/7/safe/x86_64/
Distri: CentOS Linux release 7.9.2009 (Core)

Installed packages:
> php74-php-mysqlnd-7.4.13-1.el7.remi.x86_64
> php74-php-bcmath-7.4.13-1.el7.remi.x86_64
> php74-php-pdo-7.4.13-1.el7.remi.x86_64
> php74-php-intl-7.4.13-1.el7.remi.x86_64
> php74-php-pecl-igbinary-3.1.6-1.el7.remi.x86_64
> php74-php-gmp-7.4.13-1.el7.remi.x86_64
> php74-php-sodium-7.4.13-1.el7.remi.x86_64
> php74-php-mbstring-7.4.13-1.el7.remi.x86_64
> php74-php-common-7.4.13-1.el7.remi.x86_64
> php74-php-soap-7.4.13-1.el7.remi.x86_64
> php74-php-cli-7.4.13-1.el7.remi.x86_64
> php74-php-pecl-zip-1.19.2-1.el7.remi.x86_64
> php74-php-pecl-imagick-3.4.4-10.el7.remi.x86_64
> php74-php-json-7.4.13-1.el7.remi.x86_64
> php74-php-embedded-7.4.13-1.el7.remi.x86_64
> php74-runtime-1.0-3.el7.remi.x86_64
> php74-php-process-7.4.13-1.el7.remi.x86_64
> php74-unit-php-1.21.0-1.el7.remi.x86_64
> php74-php-xml-7.4.13-1.el7.remi.x86_64
> php74-php-gd-7.4.13-1.el7.remi.x86_64

cat /etc/php.d/gd.ini 
> ; Enable gd extension module
> extension=gd.so

**Comment by chrmah** [comment]
Ok, found the issue on my side ... alternative was not set on php74 binary *blush*

**Comment by remicollet** [comment]
> cat /etc/php.d/gd.ini

I don't know from which repo comes this files... **php74-php-gd** uses `/etc/opt/remi/php74/php.d/20-gd.ini`

And 
```
# php74 --ri gd

gd

GD Support => enabled
GD headers Version => 2.3.0
GD library Version => 2.3.0
FreeType Support => enabled
FreeType Linkage => with freetype
GIF Read Support => enabled
GIF Create Support => enabled
JPEG Support => enabled
PNG Support => enabled
WBMP Support => enabled
XPM Support => enabled
XBM Support => enabled
WebP Support => enabled
BMP Support => enabled
TGA Read Support => enabled

Directive => Local Value => Master Value
gd.jpeg_ignore_warning => 1 => 1
```

Looks like you are confused with the SCL packages, please read the [FAQ](https://blog.remirepo.net/pages/English-FAQ)

Do you need multiple version ?

For a proper install, follow the [Wizard](https://rpms.remirepo.net/wizard/) instructions
