### ISSUE TITLE
CentOS 8 + PHP 8.0.0 + swoole 4.6.0 with swoole-curl: undefined symbol: _Z25zend_get_gc_buffer_createv

### ISSUE THREAD

**Issue by billionaire** [remicollet/remirepo#165]
Hi.
I have been trying to compile swoole v4.6.0 extension for php 8.0 on CentOS 8.3 for several days, but i get error when activating this extension:
```
# php --ri swoole
PHP Warning:  PHP Startup: Unable to load dynamic library 'swoole.so' (tried: /usr/lib64/php/modules/swoole.so (/usr/lib64/php/modules/swoole.so: undefined symbol: _Z25zend_get_gc_buffer_createv), /usr/lib64/php/modules/swoole.so.so (/usr/lib64/php/modules/swoole.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
Extension 'swoole' not present.
```
When i compile the PHP 8 extension on Ubuntu 18 ([ppa:ondrej/php](https://launchpad.net/~ondrej/+archive/ubuntu/php/)) everything builds and works correctly.
With CentOS 8 + remi-8.0 error (**undefined symbol: _Z25zend_get_gc_buffer_createv**).
Maybe you know what reason of this?
In the [swoole-src repository](https://github.com/swoole/swoole-src), i created ticket [#3977](https://github.com/swoole/swoole-src/issues/3977) (there is a bash-script to reproduce the error), but until now no one know what cause of this error.
Thank you for your work.
Regards.

**Comment by remicollet** [comment]
Sorry but 4.6.0 is not yet released on pecl
Once available there I will update the RPM available in my repository

**Comment by remicollet** [comment]
BTW, I cannot reproduce

```
$ php -i
phpinfo()
PHP Version => 8.0.0

System => Linux centos8 4.18.0-240.1.1.el8_3.x86_64 #1 SMP Thu Nov 19 17:20:08 UTC 2020 x86_64
Build Date => Nov 24 2020 17:04:03
Build System => Red Hat Enterprise Linux release 8.3 (Ootpa)
Build Provider => Remi's RPM repository <https://rpms.remirepo.net/>
Compiler => gcc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)
Architecture => x86_64
..

$ php -d extension=modules/swoole.so --ri swoole

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.6.0-beta
Built => Jan  5 2021 15:05:36
coroutine => enabled
trace_log => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1g FIPS  21 Apr 2020
http2 => enabled
json => enabled
zlib => 1.2.11
brotli => E16777222/D16777222
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

```

**Comment by billionaire** [comment]
Thank you for your reply.
Yes, but v4.6.0 is already available in the repository and everyone can build it yourself for testing. Also [extension-developer recommends](https://github.com/swoole/swoole-src#2-install-from-source-recommended) building the extension yourself from source instead of installing from pecl.
But on CentOS, the build of version 4.6.0 with the enable-swoole-curl flag fails. What is strange, if i compile this extension on the default PHP version (7.2.24) from the base centos repository, then everything builds correctly and works fine.
I took clean VPS with CentOS 8.3 from digitalocean, run this commands below and got result:
```bash
dnf update -y
dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
dnf install -y https://rpms.remirepo.net/enterprise/remi-release-8.rpm
dnf install -y yum-utils dnf-utils
dnf module reset php
dnf module install php:remi-8.0 -y
dnf install -y php-cli php-curl php-mysqlnd php-devel git make curl libcurl libcurl-devel openssl openssl-devel
git clone https://github.com/swoole/swoole-src; cd swoole-src; git checkout version-4.6.0; phpize; ./configure --enable-swoole-curl; make; make install
php -d extension=modules/swoole.so --ri swoole
```

```
PHP Warning:  PHP Startup: Unable to load dynamic library 'modules/swoole.so' (tried: modules/swoole.so (modules/swoole.so: undefined symbol: _Z25zend_get_gc_buffer_createv), /usr/lib64/php/modules/modules/swoole.so.so (/usr/lib64/php/modules/modules/swoole.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
Extension 'swoole' not present.
```

**Comment by remicollet** [comment]
> it looks like you didnot use --enable-swoole-curl option when configure. error appears only with this option.

I have update my previous post with --enable-swoole-curl 

=> curl-native => enabled

**Comment by billionaire** [comment]
it looks like magic. we do same thing, but get different results.

**Comment by remicollet** [comment]
Have you tried, in the git clone

`make clean; make -j8`

To ensure everything is built with the proper PHP version

**Comment by remicollet** [comment]
Found.

Fixed by https://github.com/php/php-src/commit/26c7b9402da7308e92d7cecd3bebd465341467c5

So in 8.0.1RC1, already in remi-modular-test
And will be in 8.0.1 soon in stable repo

**Comment by billionaire** [comment]
> So in **8.0.1RC1**, already in remi-modular-test (indeed I run my latest build with this version)
you are right. everything works correctly on PHP 8.0.1RC1.
thank you for help in finding cause of error.
good luck.

**Comment by remicollet** [comment]
Notice that swoole 4.6.0 is now released (as stable), and available as RPM in my repo, like most of pecl extensions
