### ISSUE TITLE
vips 8.11 (with plugins)

### ISSUE THREAD

**Issue by remicollet** [remicollet/remirepo#171]
Util version **8.10** all optional modules are build statically, which is not very flexible

User have choice between 2 packages:

- vips (with ImageMagick 6, poppler, openslide but **without** heif)
- vips- **full** (with ImageMagick 6, poppler, openslide **and** heif)

Plan for **8.11**

- vips without any optional  modules
- vips-**heif** (obsoleting vips-full)
- vips-**poppler**
- vips-**openslide**
- only one for magick among:
    - vips-**magick-im6** (using ImageMagick version 6)
    - vips-**magick-im7** (using ImageMagick version 7)
    - vips-**magick-gm** (using GraphicsMagick)

All modules will be suggested (weak dependencies of the main package)
(maybe poppler and openslide can be recommended)

Upstream WIP : [PR #2167](https://github.com/libvips/libvips/pull/2167)

**Comment by kleisauke** [comment]
libvips version 8.11.0-rc1 is now available for testing.
https://github.com/libvips/libvips/releases/tag/v8.11.0-rc1
https://libvips.github.io/libvips/2021/06/04/What's-new-in-8.11.html#loadable-modules-for-some-dependencies

Hopefully this improvement will make the work of downstream packagers easier. 👍

**Comment by remicollet** [comment]
Updated:
https://git.remirepo.net/cgit/rpms/lib/vips.git/diff/vips.spec?id=b8e8059ae09998294ca709ec0c2fe29abec59ad1

**Comment by remicollet** [comment]
First set of **testing packages** are now available in **remi-test** repository:

- vips-8.11.0~rc1-1
- vips-devel-8.11.0~rc1-1
- vips-doc-8.11.0~rc1-1
- vips-heif-8.11.0~rc1-1
- vips-magick-gm-8.11.0~rc1-1
- vips-magick-im6-8.11.0~rc1-1
- vips-magick-im7-8.11.0~rc1-1
- vips-openslide-8.11.0~rc1-1
- vips-poppler-8.11.0~rc1-1
- vips-tools-8.11.0~rc1-1

Feedback very welcome

**Possible known issue**, one of the vips-magick-* have to be installed manually, if needed, not pull but the update, as user have to choice which library to use

**Comment by remicollet** [comment]
> **Possible known issue**, one of the vips-magick-* have to be installed manually, if needed, not pull but the update, as user have to choice which library to use

Should be improved (excepted on EL-7) by https://git.remirepo.net/cgit/rpms/lib/vips.git/commit/?id=e327587fbf765c3715c00e85be3718435dc0ff1d

**Comment by kleisauke** [comment]
Seems to work! I also tested this Dockerfile to simulate a clean environment:
<details>
   <summary>Dockerfile</summary>

```Dockerfile
FROM centos:8

# Import archive signing keys and update packages
RUN rpm --import https://sourceforge.net/projects/libjpeg-turbo/files/LJT-GPG-KEY \
    && rpmkeys --import file:///etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial \
    && dnf update -y

# Install the latest stable version of libjpeg-turbo,
# since the version on CentOS is too old (v1.5.3)
RUN dnf install -y dnf-utils \
    && dnf config-manager --add-repo https://libjpeg-turbo.org/pmwiki/uploads/Downloads/libjpeg-turbo.repo \
    && sed -i '/^exclude=/ s/$/,libjpeg-turbo-*.*.9[0-9]-*/' /etc/yum.repos.d/libjpeg-turbo.repo \
    && dnf install -y libjpeg-turbo-official \
    && echo '/opt/libjpeg-turbo/lib64' >> /etc/ld.so.conf.d/libjpeg-turbo-official-x86_64.conf \
    && ldconfig \
    && dnf clean all

# Update the PKG_CONFIG_PATH environment variable,
# since libjpeg-turbo is installed in a non-standard prefix
ENV PKG_CONFIG_PATH=/opt/libjpeg-turbo/lib64/pkgconfig${PKG_CONFIG_PATH:+:${PKG_CONFIG_PATH}}

# Install libvips (full-fat version)
RUN dnf install -y epel-release \
    && rpmkeys --import file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8 \
    && dnf config-manager --set-enabled powertools \
    && dnf install -y https://rpms.remirepo.net/enterprise/remi-release-8.rpm \
    && rpmkeys --import file:///etc/pki/rpm-gpg/RPM-GPG-KEY-remi.el8 \
    && dnf config-manager --set-enabled remi \
    && dnf install -y --nogpgcheck https://download1.rpmfusion.org/free/el/rpmfusion-free-release-8.noarch.rpm \
    && rpmkeys --import file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-el-8  \
    && dnf install -y --enablerepo=remi-test --setopt=tsflags=nodocs \
        vips \
        vips-devel \
        vips-heif \
        vips-magick-im6 \
        vips-openslide \
        vips-poppler \
        vips-tools \
    && dnf clean all

ENTRYPOINT ["/usr/bin/vips"]
CMD ["--version"]
```

```bash
docker build -t remi-test .
docker run remi-test
docker run -it --entrypoint /bin/bash remi-test

# Test to see whether load/save operations for modules work
vips heifload
vips heifsave
vips magickload
vips magicksave
vips openslideload
vips pdfload
exit
```
</details>

BTW, giflib is no longer needed for libvips 8.11, so it can be safely removed.
<details>
   <summary>0001-Remove-giflib-as-dependency.patch</summary>

```diff
From c47521daf86f5988f0809ae1fee8f26fd7d1ef80 Mon Sep 17 00:00:00 2001
From: Kleis Auke Wolthuizen <github@kleisauke.nl>
Date: Sat, 5 Jun 2021 11:09:23 +0200
Subject: [PATCH] Remove giflib as dependency

No longer needed for libvips 8.11, as it has switched to libnsgif (embedded in VCS).
---
 vips.spec | 1 -
 1 file changed, 1 deletion(-)

diff --git a/vips.spec b/vips.spec
index 602b1ef..196c0c4 100644
--- a/vips.spec
+++ b/vips.spec
@@ -78,7 +78,6 @@ BuildRequires:	pkgconfig(spng) >= 0.6
 #BuildRequires:	pkgconfig(imagequant) TODO only in 2.12+
 BuildRequires:	libimagequant-devel
 %endif
-BuildRequires:	giflib-devel
 BuildRequires:	pkgconfig(gthread-2.0)
 
 BuildRequires:	gcc-c++
-- 
2.31.1
```
</details>

**Comment by remicollet** [comment]
@kleisauke thanks for feedback, patch applied.

**Comment by remicollet** [comment]
[**vips 8.11.0**](https://github.com/libvips/libvips/releases/tag/v8.11.0) is released and available in the repository
