### ISSUE TITLE
Add versioned PHP OCI8 extensions to make dependency breakage more obvious

### ISSUE THREAD

**Issue by kkatpcc** [remicollet/remirepo#176]
Every so often, the Remi php-oci8 extension changes the Instant Client version dependency. Examples:

- https://forum.remirepo.net/viewtopic.php?id=3756
- https://github.com/remicollet/remirepo/issues/167

What makes this awkward is that the dependency is not tracked, as it has to be manually installed, and therefore you may not know you have to upgrade Instant Client from (for example) version 19 to 21 until after the fact. This is especially awkward if you are intentionally locked to the same minor version of PHP (e.g. 7.4.x) and only expected security and bug fixes during the yum update process.

While I understand that the Instant Client cannot be provided or directly depended upon, for licensing reasons, perhaps the php-oci8 extension can be versioned in the Remi repo to help mitigate this issue? Example of how Oracle Linux does it: http://yum.oracle.com/repo/OracleLinux/OL7/developer/php74/x86_64/index.html

This would seemingly involve maintaining multiple builds. Users could stay on a particular version of Instant Client for some time (yum install php-oci8-19c) without having to worry about subtle PHP dependency breakage during yum updates. The thought here is that when Instant Client versions become old enough that support is no longer warranted, they are removed from the repo which should block a yum update because "php X.Y.Z requires php-oci8-NEW but is blocked by php-oci8-OLD" or something like that. Even if only one version of Instant Client was supported at a time, it would seem less annoying to find out that your update is blocked because you need to "yum remove php-oci8-19c && yum install php-oci8-21c" along with still manually updating Instant Client than to "yum update php" and think everything will be good.

Also, instead of replacing how the existing php-oci8 extension is updated, the php-oci8-N versions could be alternatives to it. This way, people can choose if they want yum updates to potentially block or not.

Thoughts?

**Comment by remicollet** [comment]
> This would seemingly involve maintaining multiple builds. 

This also mean much more time to build a new version (already more than 1 full day for all versions / distros)

**Comment by kkatpcc** [comment]
> > This would seemingly involve maintaining multiple builds.
> 
> This also mean much more time to build a new version (already more than 1 full day for all versions / distros)

Ok. Would providing "php-oci8" and then just "php-oci8-$ver" be practical enough?

**Comment by remicollet** [comment]
> Ok. Would providing "php-oci8" and then just "php-oci8-$ver" be practical enough?

Yes, this is mostly my idea

For now there is no urgency, 21 is there for a while (new major version in 1-2 year)

I need to decide if oci extensions will have a strong dependency on other extensions (exact same version/release, e.g. 7.3.28), and thus will block update, or only on ABI (e.g; 7.3) thus allowing security update for other ext.

So I don't really plan to change before next library major version

**Comment by kkatpcc** [comment]
> I need to decide if oci extensions will have a strong dependency on other extensions (exact same version/release, e.g. 7.3.28), and thus will block update, or only on ABI (e.g; 7.3) thus allowing security update for other ext.

Dependency at the minor/ABI level (e.g. 7.3) seems like the least surprising option. I would honestly be baffled if a critical revision/bug/security update was being blocked because of this extension dependency.

**Comment by remicollet** [comment]
In recent client versions (RPM), the proper _provides_ are available

```
# rpm -q --provides oracle-instantclient-basic
...
libclntsh.so = 21.11
libclntsh.so.21.1
libclntsh.so.21.1()(64bit)
libclntshcore.so = 21.11
libclntshcore.so.21.1()(64bit)
...
```

So I choose to re-enable **RPM auto dependencies**

```
# rpm -q --requires php-oci8
...
libclntsh.so.21.1()(64bit)
php83-php-pdo(x86-64) = 8.3.0~rc2-2.fc37.remi
```

As for all other libraries, what should have be done since the beginning...

This will solve the upgrade issue.
But this will make the RPM usage mandatory.

Notice: **aarch64** still have 19.19 where things are still missing :(
(at least libclntsh.so.19.1 is provided)

**Comment by remicollet** [comment]
This now applied on all branches (5.6 to 8.3)

Already used by 8.1.24RC1, 8.2.11RC1 and 8.3.0RC2
Announced https://twitter.com/RemiRepository/status/1705114287763525686

**Comment by remicollet** [comment]
Closing as this is now fixed (in 8.1.24, 8.2.11 and 8.3.0RC2)

Nobody comes to cry :)

**Comment by kkatpcc** [comment]
> This now applied on all branches (5.6 to 8.3)
@remicollet, according to the [commit log](https://git.remirepo.net/cgit/rpms/php/php74.git/log/), this seems to be the case for 5.6 through 8.3 **except** 7.4.

**Comment by remicollet** [comment]
> > This now applied on all branches (5.6 to 8.3)
> 
> @remicollet, according to the [commit log](https://git.remirepo.net/cgit/rpms/php/php74.git/log/), this seems to be the case for 5.6 through 8.3 **except** 7.4.

I forgot the "git push"
Fixed
