### ISSUE TITLE
vips-8.11.0-1 can't process .svs file (jp2k: libvips built without JPEG2000 support)

### ISSUE THREAD

**Issue by allanw1** [remicollet/remirepo#178]
Upgraded to vips-8.11 and now it cannot process .svs files which use jpeg2000.
Seems like vips-8.11 added native jpeg2000 support while older versions used imagemagick, so I've tried installing vips-magick-im7 but this doesn't help.
I also tried installing vips-full and vips-openslide

Downgraded to vips-8.10.6 and it works again.
Using CentOS 7. 9.2009.

```
$ vips dzsave test.svs abc
(vips:1704): VIPS-WARNING **: 03:34:42.857: error in tile 39168 x 0
jp2k: libvips built without JPEG2000 support
```

Sample file can be found here: http://openslide.cs.cmu.edu/download/openslide-testdata/Aperio/

**Comment by remicollet** [comment]
Hmm... cannot reproduce

Using CMU-1-Small-Region.svs

```
# cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)

# rpm -qa vips\*
vips-openslide-8.11.0-1.el7.remi.x86_64
vips-tools-8.11.0-1.el7.remi.x86_64
vips-8.11.0-1.el7.remi.x86_64
vips-poppler-8.11.0-1.el7.remi.x86_64

# vips dzsave test.svs abc

# find abc_files/ -type f
abc_files/12/5_6.jpeg
abc_files/12/8_7.jpeg
abc_files/12/1_8.jpeg
abc_files/12/1_10.jpeg
abc_files/12/5_11.jpeg
abc_files/12/0_0.jpeg
abc_files/12/2_0.jpeg
abc_files/12/4_0.jpeg
...
```

**Comment by remicollet** [comment]
Notice, for now, vips RPMs  have never used libopenjpg2, as version 2.4 is required, and only version 2.3 is available in the repository.

Will be used, for next build, but only on Fedora 34 which have version 2.4

**Comment by allanw1** [comment]
> Using CMU-1-Small-Region.svs

Sorry, I should have specified to use JP2K-33003-1.svs to test JPEG2000 .svs file

**Comment by allanw1** [comment]
Before I wrote about using a test jpeg2000 file but that works too.

Now I found that vips dzsave does work as root, but with my limited user it gives the error even after logging in and out. I'm not sure what permissions are missing.

**Comment by allanw1** [comment]
With the limited user, there was a vips executable in /bin/vips installed 6/10 (about when vips was updated to 8.11.0) while the root one was using /usr/bin/vips which works on my limited user too. Not sure where this file came from but they have the same md5sum

```
$ which vips
/bin/vips
$ md5sum /bin/vips
9c9986a213082b1f9d80f6b9d0eb73fc  /bin/vips
$ md5sum /usr/bin/vips
9c9986a213082b1f9d80f6b9d0eb73fc  /usr/bin/vips
$ /usr/bin/vips dzsave JP2K-33003-1.svs abc1

$ /bin/vips dzsave JP2K-33003-1.svs abc1
(vips:19013): VIPS-WARNING **: 05:35:55.530: error in tile 15360 x 0
jp2k: libvips built without JPEG2000 support
```

```
# rpm -qf /bin/vips
vips-tools-8.11.0-1.el7.remi.x86_64
# rpm -qf /usr/bin/vips
vips-tools-8.11.0-1.el7.remi.x86_64
```

**Comment by remicollet** [comment]
Same file...
```
$ ll -d /bin
lrwxrwxrwx. 1 root root 7 27 juil.  2020 /bin -> usr/bin

```

**Comment by remicollet** [comment]
I have suggested upstream to allow libopenjpg2 version 2.3
See https://github.com/libvips/libvips/pull/2305

Can you please try with test packages in temp directory
https://rpms.remirepo.net/temp/

**Comment by remicollet** [comment]
Forget these test build... openjpg2 usage cannot be enabled in EL-7
Old issue... poppler pulls openjpeg v1, other pulls openjpeg v2, and thus create symbols nightmare and segfault.

As it works using /usr/bin/vips, and as /bin is NOT in the PATH by default
I think this issue can be closed (fix your PATH)

**Comment by allanw1** [comment]
I can't find where /bin is even being put into my path other than possibly /etc/init.d/functions but I can't reboot this server to check. This system is running cpanel so that might be the cause of weird configurations.
Anyway I will just use /usr/bin and now the error message comes up on Google if anyone else has the same problem.

**Comment by remicollet** [comment]
And for memory, dependency on openjpeg2 added for other distro in
https://git.remirepo.net/cgit/rpms/lib/vips.git/commit/?id=4c881c4a712c6c3ab0fbd89436a2872db02b0dbd

**Comment by remicollet** [comment]
Some more explanation

When /usr/bin/vips is used, plugins are search in /usr/lib64, as expected
```
# strace vips dzsave test.svs abc 2>&1 | grep vips-modules
openat(AT_FDCWD, "/usr/lib64/vips-modules-8.11", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 3
```

When /bin/vips is used, plugins are search in /lib, , so of course are not found, which explain this issue
```
# LANG=C strace /bin/vips dzsave test.svs abc 2>&1 | grep vips-modules
openat(AT_FDCWD, "/lib/vips-modules-8.11", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = -1 ENOENT (No such file or directory)
```

So, for me, this looks like an issue in some library (perhaps libgmodule from glibc)

**Comment by remicollet** [comment]
> So, for me, this looks like an issue in some library (perhaps libgmodule from glibc)

No, issue is really in vips which use hardcoded path (not a packaging issue)

Should be fixed in next build by https://github.com/libvips/libvips/pull/2308

(waiting for upstream feedback)
