### ISSUE TITLE
Imagick extension version 3.5.0 - IM6 or IM7

### ISSUE THREAD

**Issue by remicollet** [remicollet/remirepo#179]
Change planed  for upcoming **imagick 3.5.0**

Instead of providing **php-pecl-imagick** using ImageMagick6, plan is to offer the choice

- **php-pecl-imagick-im6** using ImageMagick6 (and obsoleting php-pecl-imagick for smooth upgrade)
- **php-pecl-imagick-im7** using ImageMagick7

Sometime in the future, a new version (probably imagick 4) will only support IM7, and for new distro (Fedora 35, RHEL 9 ?) I may choose to drop IM6 build.

For **vips** and **imagick** extensions users, I recommend to keep using a single library for consistency

- php-pecl-vips + vips-magick-gm + php-pecl-gmagick
- php-pecl-vips + vips-magick-im6 + php-pecl-imagick-im6
- php-pecl-vips + vips-magick-im7 + php-pecl-imagick-im7

**Comment by remicollet** [comment]
Done in https://git.remirepo.net/cgit/rpms/php/pecl/php-pecl-imagick.git/diff/php-pecl-imagick.spec?id=38acc4f0998012852bea97c2aad1224badde86e6   (test build, not published yet)

**Comment by remicollet** [comment]
**Version 3.5.0RC2** is now released.

Packages are available in the testing repository

**Comment by remicollet** [comment]
**Version 3.5.0** is now released.

Packages are available in the **stable** repository

**Comment by Danack** [comment]
btw this scared me.

*does release*
*gets notification from Remi 30 minutes later*.
*ahahaahhahrghahgh, oh it's fine.*

**Comment by remicollet** [comment]
For memory, to switch variant used

On Fedora / EL 8

`# dnf install php-pecl-imagick-im7 --allowerasing`

On EL 7

`# yum swap -- install php-pecl-imagick-im7 -- remove php-pecl-imagick-im6`
