### ISSUE TITLE
Imagemagick doesn't support AVIF 

### ISSUE THREAD

**Issue by MaluNoPeleke** [remicollet/remirepo#186]
The Imagemagick version

ImageMagick 7.1.0-4 Q16 x86_64 2021-07-18

doesn't support AVIF as a file format:

magick -list format |grep "AVIF"
$: (empty)

If I try to convert a jpeg to AVIF I just get a Jpeg with .avif as an output.
Maybe the issue is related to an older libheif library or aom for compilation!?
At least that is mentioned here:

https://github.com/ImageMagick/ImageMagick/issues/2551

**Comment by remicollet** [comment]
Distribution ? version ? Installed packages ?

BTW, I use libheif from rpmfusion,, so not something under my control

Is it available on Fedora build
```
$ magick -list format |grep "AVIF"
     AVIF* HEIC      rw+   AV1 Image File Format (1.8.0)

```

**Comment by MaluNoPeleke** [comment]
CentOS 7 and regarding the packages I need to ask my hoster.

**Comment by MaluNoPeleke** [comment]
Maybe you could help me out @SalocinHB ?

**Comment by remicollet** [comment]
Perhaps @leigh123linux may help

BTW EL-7 have a very old version (1.3.2), and I don't think we should expect any update there.

EL-8 have libheif 1.7.0, with AVIF support

```
$ magick -list format |grep "AVIF"
     AVIF* HEIC      rw+   AV1 Image File Format (1.7.0)
```

Probably you should consider using a modern distro to have the benefits of modern features.

Marking as "not a bug", as not related to package provided by my repository.

**Comment by MaluNoPeleke** [comment]
As I rely on my hoster https://github.com/Uberspace I cannot change the distro version.
I was hoping that it is possible with CentOS 7 as well to generate AVIF images with pre-built packages.
