### ISSUE TITLE
SSL expired!!

### ISSUE THREAD

**Issue by nandakumarcs** [remicollet/remirepo#187]
Hello,

It appears the SSL certificate for rpms.remirepo.net is expired.

wget -O /dev/null https://rpms.remirepo.net/enterprise/remi-release-8.rpm
--2021-10-12 02:35:09--  https://rpms.remirepo.net/enterprise/remi-release-8.rpm
Resolving rpms.remirepo.net (rpms.remirepo.net)... 109.238.14.107, 2a00:c70:1:109:238:14:107:1
Connecting to rpms.remirepo.net (rpms.remirepo.net)|109.238.14.107|:443... connected.
ERROR: cannot verify rpms.remirepo.net's certificate, issued by ‘/C=US/O=Let's Encrypt/CN=R3’:
  Issued certificate has expired.
To connect to rpms.remirepo.net insecurely, use `--no-check-certificate'.

Please fix this as soon as possible.

**Comment by remicollet** [comment]
Sorry cannot reproduce...

```
# wget -O /dev/null https://rpms.remirepo.net/enterprise/remi-release-8.rpm
--2021-10-12 08:46:49--  https://rpms.remirepo.net/enterprise/remi-release-8.rpm
Resolving rpms.remirepo.net (rpms.remirepo.net)... 2a00:c70:1:109:238:14:107:1, 109.238.14.107
Connecting to rpms.remirepo.net (rpms.remirepo.net)|2a00:c70:1:109:238:14:107:1|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 26132 (26K) [application/x-rpm]
Saving to: '/dev/null'

/dev/null                                              100%[===========================================================================================================================>]  25.52K  --.-KB/s    in 0s      

2021-10-12 08:46:49 (383 MB/s) - '/dev/null' saved [26132/26132]

```
Certificate information (from the Browser)
```
Not before Thu, 23 Sep 2021 06:29:05 GMT
Not after  Wed, 22 Dec 2021 06:29:04 GMT
```

Are you affected by let's encrypt root certificate issue ?
Is your system fully updated ?

See https://access.redhat.com/articles/6338021

**Comment by nandakumarcs** [comment]
Thanks, man!! Works well now
