### ISSUE TITLE
Repository for RHEL 9 and CentOS Stream 9

### ISSUE THREAD

**Issue by remicollet** [remicollet/remirepo#189]
As [RHEL-9 Beta is released](https://www.redhat.com/en/blog/whats-new-rhel-90-beta)

- [x] Repositoy layout
- [x] remi-release
- [x] php:remi-7.4 stream
- [x] extensions for php:remi-7.4 stream
- [x] php:remi-8.0 stream
- [x] extensions for php:remi-8.0 stream
- [x] php:remi-8.1 stream
- [x] extensions for php:remi-8.1 stream
- [x] php74 SCL
- [x] extensions for php74
- [x] php80 SCL
- [x] extensions for php80
- [x] php81 SCL
- [x] extensions for php81
- [x] noarch packages (done: composer, phpMyAdmin, phpunit*, roundcubemail, Wordpress and dependencies)

Missing for now

- [x] vips and php-pecl-vips (missing matio and hdf5, from EPEL)
- [x] cassandra (missing libcassandra because of openssl 3)
- [ ] mosquitto (missing libwebsockets because of openssl 3)

**Comment by remicollet** [comment]
As the repository is mostly ready, it is announced:
https://blog.remirepo.net/post/2021/11/08/Enterprise-Linux-9-Repository

**Comment by aran112000** [comment]
Not sure if this is the correct place to report this, but just spotted "**CentOS 9** (Development version)" is showing in the OS list on the [Configuration wizard](https://rpms.remirepo.net/wizard/) which I believe is an error as it'll now be CentOS Stream.

**Comment by remicollet** [comment]
perhaps should only set "9" as the group name is "CentOS Linux and other clones"

In all cases cannot be CentOS Stream (but CentOS 9 Stream)

**Comment by remicollet** [comment]
Packages missing and reqsuested for EPEL-9

- tidy, [#2029448](https://bugzilla.redhat.com/show_bug.cgi?id=2029448)

**Comment by khs1994** [comment]
miss `uw-imap-devel`

https://pkgs.org/search/?q=uw-imap-devel

**Comment by remicollet** [comment]
> miss `uw-imap-devel`
 
It is in my repo (for php-imap), and I don't plan to ask for it in the official EPEL repository.
This is a DEAD thing. Nobody serious should need it.

**Comment by khs1994** [comment]
how to install `uw-imap-devel` on rhel9?

**Comment by remicollet** [comment]
@khs1994 please don't pollute this issue with out of topic question
