### ISSUE TITLE
can't make VIPS to work on Centos8

### ISSUE THREAD

**Issue by sadektouati** [remicollet/remirepo#193]
I'm sorry if what I'm asking is a trivia or it has been solved.

After a lot of trial and errors I managed to install libvips on a Centos 8  server. The only problem is that when converting to AVIF I get results similar to this image 
![141600196-2f442129-7118-49da-8e1f-b0479faa4658](https://user-images.githubusercontent.com/6498750/144050011-084100dd-591b-4f6a-a567-4118d544ce45.jpg)

I'm using (https://github.com/libvips/php-vips)

Thank you for your help

**Comment by remicollet** [comment]
Looks like you are displaying content of the file instead of saving it.

It works for me using 
```
# rpm -qa \*vips\* | sort
php-pecl-vips-1.0.12-5.el8.remi.7.4.x86_64
vips-8.12.1-1.el8.remi.x86_64
vips-heif-8.12.1-1.el8.remi.x86_64
vips-magick-im7-8.12.1-1.el8.remi.x86_64
vips-openslide-8.12.1-1.el8.remi.x86_64
vips-poppler-8.12.1-1.el8.remi.x86_64
vips-tools-8.12.1-1.el8.remi.x86_64
```

Simple test
```
<?php

if ($_SERVER['argc'] < 2) {
	$n = $_SERVER['argv'][0];
	die("usage $n in  [ out ] \n");
}
$n = $_SERVER['argv'][1];
echo "load $n\n";
$im = vips_image_new_from_file($_SERVER['argv'][1])["out"];
printf("Size: %dx%d\n", vips_image_get($im, "width")["out"], vips_image_get($im, "height")["out"]);

$res = vips_call("invert", $im);
$im = $res["out"];

if ($_SERVER['argc'] > 2) {
	$n = $_SERVER['argv'][2];
	echo "save $n\n";
	vips_image_write_to_file($im, $_SERVER['argv'][2]);
}
```

And run it
```
$ php -d extension=vips vips.php logo3w.png  logo3w.avif
load logo3w.png
Size: 275x95
save logo3w.avif

$ file logo3w*
logo3w.avif: ISO Media, AVIF Image
logo3w.png:  PNG image data, 275 x 95, 8-bit colormap, non-interlaced
```

Need a small reproducer to understand your problem (btw, I don't use **php-vips** library, only **php-vips-ext** extension)

**Comment by sadektouati** [comment]
Thank you for your answer.

From what I see on your answer, we have the same packages installed.

I ran your code.

The resulting file is the same as the one I produced using vips-php.

What I noticed is that: when I run the file command on my resulting AVIF file it only shows: ISO Media, **NO AVIF Image**

**Comment by remicollet** [comment]
> I run the file command on my resulting AVIF file it only shows: ISO Media

I think "file" is outdated
Simply try to display the resulting image in a avif supported app (I test with eog on Fedora)

**Comment by sadektouati** [comment]
> I think "file" is outdated Simply try to display the resulting image in a avif supported app (I test with eog on Fedora)

I'm on a remote server, so can't try that one.

I want to COMPLETELY remove libvips and install it again. I might have missed a package or so...

Can you please provide me with the steps for a FRESH install of libvips on CentOS 8

**Comment by remicollet** [comment]
> I'm on a remote server, so can't try that one.

<sic>
download the image to yous local computer

> I want to COMPLETELY remove libvips and install it again. 

This have never solved anything...

> Can you please provide me with the steps for a FRESH install of libvips on CentOS 8

`dnf install vips`

**Comment by sadektouati** [comment]
Ok.
I downloaded the image:
Here it is (in a screenshot) 
![ffdsg - Copy](https://user-images.githubusercontent.com/6498750/144307143-9f3fe560-a907-4644-9089-6332cae0bc32.jpg)

GitHub doesn't allow me to upload avif format

**Comment by remicollet** [comment]
So ? everything seems OK ?

**Comment by sadektouati** [comment]
> So ? everything seems OK ?

Not exactly. I don't understand why it makes "des images négatif". (I'm using your exact script)

**Comment by remicollet** [comment]
Because the test script have` $res = vips_call("invert", $im);`

**Comment by sadektouati** [comment]
Everything is working as expected. 
Thank you very much
