### ISSUE TITLE
Please, port the Fix #351 to gd-2.2.5

### ISSUE THREAD

**Issue by mikaku** [remicollet/remirepo#194]
The package `gd-2.2.5` that comes with Rocky 8.5 (upstream RHEL 8.5) have a problem when drawing the slices of a pie chart.

It appears that this bug was fixed in 2.3.0 version as stated [here](https://github.com/libgd/libgd/blob/gd-2.3.3/CHANGELOG.md) (`Fix #351: gdImageFilledArc() doesn't properly draw pies`).

Please, consider porting this fix to the current version of `gd` for RHEL 8 and derivatives.
Thank you very much.

**Comment by remicollet** [comment]
Plan is to provide a gd3php package providing latest version (2.3.3) with soname artificially bump to 103 and only used by PHP.

**Comment by remicollet** [comment]
Plan is to use "gd3php" for upcoming RC versions (7.4.27RC1, 8.0.14RC1 and 8.1.1RC1)

And then to all new stable version

**Comment by mikaku** [comment]
You are a wizard!
Thanks.

**Comment by remicollet** [comment]
Fix for gd library
https://git.remirepo.net/cgit/rpms/lib/gd.git/commit/?id=996c8728cb22e41f1c85787e7f400f249c993be3

Fix for PHP 7.4.27RC1
https://git.remirepo.net/cgit/rpms/scl-php74/php.git/commit/?id=27e9cf8e86f6f7c80b207096100d4239f926111f
https://git.remirepo.net/cgit/rpms/php/php74.git/commit/?id=81292e85e085fec64dbeb705dd49a59eafe49f46

Fix for PHP 8.0.14RC1
https://git.remirepo.net/cgit/rpms/php/php80.git/commit/?id=47e6300a74a98cd3ea5076a05c7ac043e178de36
https://git.remirepo.net/cgit/rpms/scl-php80/php.git/commit/?id=725892bf62bc43cdadbb276950b9451c6b2b14b4

Will also be in 8.1.1RC1

**Comment by mikaku** [comment]
Just tested with PHP 7.4.27RC1 and it indeed fixes the problem in the pie charts.
Live is beautiful!
Thank you very much.

**Comment by remicollet** [comment]
Previous version (7.4.26-1)

```
# php --ri gd

gd

GD Support => enabled
GD headers Version => 2.2.5
GD library Version => 2.2.5
FreeType Support => enabled
FreeType Linkage => with freetype
GIF Read Support => enabled
GIF Create Support => enabled
JPEG Support => enabled
PNG Support => enabled
WBMP Support => enabled
XPM Support => enabled
XBM Support => enabled
WebP Support => enabled
BMP Support => enabled
TGA Read Support => enabled

Directive => Local Value => Master Value
gd.jpeg_ignore_warning => 1 => 1

```
New version (7.4.27~RC1-2)

```
# php --ri gd

gd

GD Support => enabled
GD headers Version => 2.3.3
GD library Version => 2.3.3
FreeType Support => enabled
FreeType Linkage => with freetype
GIF Read Support => enabled
GIF Create Support => enabled
JPEG Support => enabled
PNG Support => enabled
WBMP Support => enabled
XPM Support => enabled
XBM Support => enabled
WebP Support => enabled
BMP Support => enabled
TGA Read Support => enabled

Directive => Local Value => Master Value
gd.jpeg_ignore_warning => 1 => 1

```

**Comment by remicollet** [comment]
All build using **gd3php**: php **7.4.27RC1**, **8.0.14RC1** and **8.1.1RC1** for EL-7 and EL-8 are now in the testing repository

**Comment by mikaku** [comment]
JFYI, I've just installed the latest updates of PHP 7.4.27 for EL8 and all continues working finely.
