### ISSUE TITLE
zip extension, undefined symbol: zip_register_cancel_callback_with_state

### ISSUE THREAD

**Issue by rowhel95** [remicollet/remirepo#195]
PHP Warning:  PHP Startup: Unable to load dynamic library 'zip.so' (tried: /usr/lib64/php/modules/zip.so (/usr/lib64/php/modules/zip.so: undefined symbol: zip_register_cancel_callback_with_state), /usr/lib64/php/modules/zip.so.so (/usr/lib64/php/modules/zip.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP 7.4.27 (cli) (built: Dec 14 2021 17:17:06) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
CentOS 7

 /usr/lib64/php/modules/
-rw-r--r-- 1 root root 5808 Nov 24 07:27 10-opcache.ini.rpmnew
-rw-r--r-- 1 root root 5855 Dec 22  2020 10-opcache.ini.rpmsave
-rw-r--r-- 1 root root   44 Dec 15 08:47 20-bz2.ini
-rw-r--r-- 1 root root   54 Dec 15 08:47 20-calendar.ini
-rw-r--r-- 1 root root   48 Dec 15 08:47 20-ctype.ini
-rw-r--r-- 1 root root   46 Dec 15 08:47 20-curl.ini
-rw-r--r-- 1 root root   44 Dec 15 08:47 20-dom.ini
-rw-r--r-- 1 root root   46 Dec 15 08:47 20-exif.ini
-rw-r--r-- 1 root root   54 Dec 15 08:47 20-fileinfo.ini
-rw-r--r-- 1 root root   44 Dec 15 08:47 20-ftp.ini
-rw-r--r-- 1 root root   42 Dec 15 08:47 20-gd.ini
-rw-r--r-- 1 root root   52 Dec 15 08:47 20-gettext.ini
-rw-r--r-- 1 root root   48 Dec 15 08:47 20-iconv.ini
-rw-r--r-- 1 root root   46 Dec 15 08:47 20-intl.ini
-rw-r--r-- 1 root root   46 Dec 15 08:47 20-json.ini
-rw-r--r-- 1 root root   54 Dec 15 08:47 20-mbstring.ini
-rw-r--r-- 1 root root   52 Dec 15 08:47 20-mysqlnd.ini
-rw-r--r-- 1 root root   44 Dec 15 08:47 20-pdo.ini
-rw-r--r-- 1 root root   46 Dec 15 08:47 20-phar.ini
-rw-r--r-- 1 root root   48 Dec 15 08:47 20-posix.ini
-rw-r--r-- 1 root root   48 Dec 15 08:47 20-shmop.ini
-rw-r--r-- 1 root root   56 Dec 15 08:47 20-simplexml.ini
-rw-r--r-- 1 root root   52 Dec 15 08:47 20-sockets.ini
-rw-r--r-- 1 root root   50 Dec 15 08:47 20-sodium.ini
-rw-r--r-- 1 root root   52 Dec 15 08:47 20-sqlite3.ini
-rw-r--r-- 1 root root   52 Dec 15 08:47 20-sysvmsg.ini
-rw-r--r-- 1 root root   52 Dec 15 08:47 20-sysvsem.ini
-rw-r--r-- 1 root root   52 Dec 15 08:47 20-sysvshm.ini
-rw-r--r-- 1 root root   56 Dec 15 08:47 20-tokenizer.ini
-rw-r--r-- 1 root root   44 Dec 15 08:47 20-xml.ini
-rw-r--r-- 1 root root   56 Dec 15 08:47 20-xmlwriter.ini
-rw-r--r-- 1 root root   44 Dec 15 08:47 20-xsl.ini
-rw-r--r-- 1 root root   50 Dec 15 08:47 30-mysqli.ini
-rw-r--r-- 1 root root   56 Dec 15 08:47 30-pdo_mysql.ini
-rw-r--r-- 1 root root   58 Dec 15 08:47 30-pdo_sqlite.ini
-rw-r--r-- 1 root root   56 Dec 15 08:47 30-xmlreader.ini
-rw-r--r-- 1 root root   47 Oct 12 15:32 30-zip.ini

**Comment by remicollet** [comment]
You are not using the proper version of zip library

```
$ ldd /usr/lib64/php/modules/zip.so
	libzip.so.5 => /lib64/libzip.so.5 (0x00007fcdf9a0f000)

$ rpm -qf /lib64/libzip.so.5
libzip5-1.8.0-2.el7.remi.x86_64

$ php --ri zip
zip

Zip => enabled
Zip version => 1.20.0
Libzip version => 1.8.0
BZIP2 compression => Yes
XZ compression => Yes
ZSTD compression => Yes
AES-128 encryption => Yes
AES-192 encryption => Yes
AES-256 encryption => Yes

```

So probably an old version somewhere in the library path (/usr/local ?)

**Comment by rowhel95** [comment]
ldd /usr/lib64/php/modules/zip.so
        linux-vdso.so.1 =>  (0x00007fffcf696000)
        libzip.so.5 => /usr/local/lib/libzip.so.5 (0x00007fad7a5e0000)
        libc.so.6 => /usr/lib64/libc.so.6 (0x00007fad7a212000)
        libz.so.1 => /usr/lib64/libz.so.1 (0x00007fad79ffc000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fad7aa0e000)

 rpm -qf /lib64/libzip.so.5
libzip5-1.8.0-2.el7.remi.x86_64

php --ri zip
PHP Warning:  PHP Startup: Unable to load dynamic library 'zip.so' (tried: /usr/lib64/php/modules/zip.so (/usr/lib64/php/modules/zip.so: undefined symbol: zip_register_cancel_callback_with_state), /usr/lib64/php/modules/zip.so.so (/usr/lib64/php/modules/zip.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
Extension 'zip' not present.

How can i fix this?

**Comment by remicollet** [comment]
> libzip.so.5 => /usr/local/lib/libzip.so.5 (0x00007fad7a5e0000)

Clean up this one, probably build manually from sources

**Comment by rowhel95** [comment]
Thanks! it works now

**Comment by remicollet** [comment]
:)
