### ISSUE TITLE
Missing module.yaml on reposync

### ISSUE THREAD

**Issue by Kyle0341** [remicollet/remirepo#198]
Unable to install remi-php81 on RHEL 8 due to dnf error 'No available modular metadata for modular package'. Our local repository lacks a modules.yaml after performing a reposync against rpms.remirepo.net/enterprise/8/php81/$basearch. Reviewing the respective repond.xml file there doesn't appear to be a reference to a module.yaml file either.

Executing 'dnf --disablerepo=* --enablerepo=remi-php8 module list' returns error '@modulefailsafe' with the repository setup below.

[remi-php8]
name=remi php8 for RHEL 8
baseurl=http://rpms.remirepo.net/enterprise/8/php81/$basearch/
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-remi

What I'm trying to do is reposync the remi-8.1 content to our local repository for redistribution. I'm pulling all the required packages and they'll install via 'rpm -i', however, I can't install anything via yum/dnf as the module metadata isn't available and looking for assistance as I believe this is to be provided by the repository owner.

Relevant RHEL Articles
Error '@modulefailsafe': https://access.redhat.com/solutions/5975941
Missing Module metadata: https://access.redhat.com/solutions/5890551

**Comment by remicollet** [comment]
module.yaml is not missing, 
see https://rpms.remirepo.net/enterprise/8/modular/x86_64/repodata/

You cannot use the "php81" folder, which is a build artefact, you need the "modular" folder (which contains all packages of all streams), and you also probably need the "safe" directory for some common dependencies.

**Comment by remicollet** [comment]
Notice: for a proper repository configuration, use the "remi-release" package.

At least, this seems wrong (should be the 2018 key)
> gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-remi

**Comment by Kyle0341** [comment]
Resolved, misunderstanding on my part.
