### ISSUE TITLE
SnipeIT Install - Missing remi-libzip

### ISSUE THREAD

**Issue by renegadext** [remicollet/remirepo#199]
Hello Remi,

I am trying to install SnipeIT under CentOS 9 in a fresh VM using this link: https://www.linuxcapable.com/how-to-install-php-8-1-on-centos-9-stream/

The output I get is the following:

[root@snipeit ~]# dnf install php-cli php-fpm php-curl php-mysqlnd php-gd php-opcache php-zip php-intl php-common php-bcmath php-imap php-imagick php-xmlrpc php-json php-readline php-memcached php-redis php-mbstring php-apcu php-xml php-dom php-redis php-memcached php-memcache
Last metadata expiration check: 0:08:52 ago on Mon 28 Feb 2022 11:36:25 AM EST.
Package php-cli-8.1.3-1.el9.remi.x86_64 is already installed.
Package php-fpm-8.1.3-1.el9.remi.x86_64 is already installed.
Package php-common-8.1.3-1.el9.remi.x86_64 is already installed.
Package php-opcache-8.1.3-1.el9.remi.x86_64 is already installed.
Package php-common-8.1.3-1.el9.remi.x86_64 is already installed.
Package php-common-8.1.3-1.el9.remi.x86_64 is already installed.
Package php-cli-8.1.3-1.el9.remi.x86_64 is already installed.
Package php-mbstring-8.1.3-1.el9.remi.x86_64 is already installed.
Package php-xml-8.1.3-1.el9.remi.x86_64 is already installed.
Package php-xml-8.1.3-1.el9.remi.x86_64 is already installed.
Error:
Problem: conflicting requests

    nothing provides remi-libzip(x86-64) >= 1.8.0 needed by php-pecl-zip-1.20.0-2.el9.remi.8.1.x86_64
    (try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
    [root@snipeit ~]#

I got the same output using version remi-7.4 as well.  Thanks!

Bill

**Comment by remicollet** [comment]
Indeed, "remi-libzip" was missing in "remi-safe" (but available in "remi", but not enabled by default).

Should be fixed now.
