### ISSUE TITLE
php81-pecl-memcached version number

### ISSUE THREAD

**Issue by giggsey** [remicollet/remirepo#200]
Hi,

Is it possible to bump the version number of your pecl-memcached module for PHP 8.1, to avoid the version constraint in https://github.com/symfony/symfony/issues/45601 ?

**Comment by remicollet** [comment]
> Would it be possible to release version 3.1.5.1 maybe? Then we could ensure Symfony allows it.

Downstream (IMHO) cannot use version > upstream one

**Comment by remicollet** [comment]
After a bit more thinking, the current package is soo far from 3.1.5 that it probably doesn't make sense to keep it  named 3.1.5

So I bump release from 3.1.5 (stable) to 3.1.6-dev (beta), which is much more true.
(I only revert change of store_retry_count from 2 to 0, planed for 3.2.0)

Now available in the repository (soon on all mirrors)
* php-pecl-memcached-3.1.6~DEV-1
* php80-php-pecl-memcached-3.1.6~DEV-1
* php81-php-pecl-memcached-3.1.6~DEV-1

**Comment by remicollet** [comment]
Closing, as fixed

(as upstream, I also released 3.2.0RC1)

**Comment by giggsey** [comment]
@remicollet Do you build packages for the RC versions?

**Comment by remicollet** [comment]
Yes, of course, in the testing repository (remi-test or remi-modular-test...)
Also announced https://twitter.com/RemiRepository/status/1501558556881035274

**Comment by giggsey** [comment]
Thanks
