### ISSUE TITLE
Rebuild php81-php-pecl-solr2 with PHP 8.1 fixes

### ISSUE THREAD

**Issue by alexgit2k** [remicollet/remirepo#201]
It looks like php81-php-pecl-solr2 has been build with the latest available release 2.5.1 from 2020 (https://pecl.php.net/package/solr) which shows a lot of deprecation notices.

The deprecations have already been fixed upstream with php/pecl-search_engine-solr/pull/30 but a release including these fixes has not been published yet. So please rebuild php81-php-pecl-solr2 with the master-branch of upstream https://github.com/php/pecl-search_engine-solr

Thanks.

**Comment by remicollet** [comment]
While I think https://github.com/php/pecl-search_engine-solr/commit/c656212bad2db9217fdcd014002ea723f3eaa6e8 make sense, I dont think https://github.com/php/pecl-search_engine-solr/commit/abebab934d2439193339b062abec4d75610a4fb2  to remove serializable make sense

For now you have to disable deprecated (error_reporting) to use this extension.
And test suite passes, with all PHP versions (with server configured)

**Comment by remicollet** [comment]
Fixed by https://git.remirepo.net/cgit/rpms/php/pecl/php-pecl-solr2.git/commit/?id=fb4c17732956a11ffcf000e394b669c7d109a751

**Comment by remicollet** [comment]
New builds uploaded to the repository.

**Comment by alexgit2k** [comment]
Removing serializable at [php/pecl-search_engine-solr@abebab9](https://github.com/php/pecl-search_engine-solr/commit/abebab934d2439193339b062abec4d75610a4fb2) was more a workaround to suppress deprecations. At least for the core functionality this doesn't seem to be used.

Testing your RPM now.

Thank you very much!

**Comment by alexgit2k** [comment]
I can confirm that import and search in Solr is working with php81-php-pecl-solr2-2.5.1-4 with 4 deprecation notices because of Serializable. Thanks!
