### ISSUE TITLE
EL-8: ImageMagick6-libs versus ImageMagick-libs

### ISSUE THREAD

**Issue by remicollet** [remicollet/remirepo#205]
For now, EPEL provides version 6.9.10.86 (soname = 6)
thus I was able to provide ImageMagick6, version 6.9.12.50 (soname = 7)

But EPEL maintainer choose to update (and break ABI for all users) to 6.9.12-48 in https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2022-62b1a9e158

**Plan**

- "remi" (disabled by default)  will still have latest **ImageMagick** version replacing EPEL version, and obsoleting previous **ImageMagick6** stack 
- "remi-safe" won't have any package, "dnf update --allowerasing" should allow to switch back to the EPEL version

Notice: I recommend to switch to **ImageMagick7** stack instead (using vips-magick-im7 and/or php-pecl-imagick-im7)

**Comment by sergiomb2** [comment]
Let me know if I can help , the update should be push to stable tomorrow (days to stable 1)

ImageMagick soname bump was approved [0] in EPEL Steering Committee meeting. and I'm continuing with the process for incompatible upgrades from step 4 forward [1]. and 81 security bugs  on ImageMagick will be fixed.

[0] https://meetbot.fedoraproject.org/teams/epel/epel.2022-04-13-20.00.html 

[1] https://docs.fedoraproject.org/en-US/epel/epel-policy-incompatible-upgrades/#process_for_incompatible_upgrades

**Comment by sergiomb2** [comment]
Tomorrow it goes to stable (I hope) , after we can think in others improvements anyway nothing provides ImageMagick6 , so I don't see for what we need these obsoletes  ? 

Thank you 

 dnf repoquery --whatprovides ImageMagick6

**Comment by remicollet** [comment]
> anyway nothing provides ImageMagick6

It is in my repo, and the subject of "this" issue... 
trying to manage breakage from EPEL for users of my repository.

**Comment by remicollet** [comment]
Pushed to the repository.

**Comment by sergiomb2** [comment]
Hi Remi
I can add Obsoletes: ImageMagick6%{?_isa} = %{epoch}:%{version}-%{release} etc to package on epel8 branch , 
one pull request on https://src.fedoraproject.org/rpms/ImageMagick/pull-requests is the best for me

**Comment by remicollet** [comment]
> Hi Remi I can add Obsoletes: ImageMagick6%{?_isa} = %{epoch}:%{version}-%{release} etc to package on epel8 branch , if you send me one pull request on https://src.fedoraproject.org/rpms/ImageMagick/pull-requests , is what I liked best

https://src.fedoraproject.org/rpms/ImageMagick/pull-request/9

**Comment by remicollet** [comment]
Update to 6.9.12-50 in EPEL-8 will fix the update issue for users of my repository
https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2022-53b708673f

**Comment by paskuale75** [comment]
Hi, can anyone help me understand how to upgrade the 'convert' command from 6.x to 7.x ?
Currently on the Plesk server (a centos 7 - php 7.2.34 ) I have these 3 installations (image below) thanks

<img width="804" alt="Schermata 2023-12-28 alle 12 05 43" src="https://github.com/remicollet/remirepo/assets/9800/74100add-0a87-42af-ac0b-8414905b4943">

**Comment by remicollet** [comment]
@paskuale75 

Read: https://blog.remirepo.net/post/2023/04/27/ImageMagick-and-imagick-extension

```
yum remove ImageMagick
yum install ImageMagick7
```
Can also be done in `yum shell`

Notice: el7 is close to its end of live in ~6 months, I recommend using a more modern version (el8 or el9)
and such a switch is simpler thanks to `dnf`.

**Comment by paskuale75** [comment]
Thanks for reply @remicollet I solved here https://imagemagick.org/script/install-source.php (after configure + make + make install) I finally got the "convert" version 7.x
