### ISSUE TITLE
The "multiple versions simultaneously" php-fpm package sets itself as the default version.

### ISSUE THREAD

**Issue by tsteiner** [remicollet/remirepo#208]
I recently installed php81-php-fpm in order to allow users to test the latest version of PHP on a new virtual host.  I intended to leave the existing virtual hosts running PHP 7.4.  After configuring the virtual host to use the alternate socket location for PHP files, I was surprised to find that every virtual host was now using PHP 8.1.  I was able to fix this by commenting out the "SetHandler" line in /etc/httpd/conf.d/php81-php.conf.  However, I'm not sure its the best idea to include modifications to the web server config in the "multiple versions simultaneously" versions of the RPMs.  I think it would be better to leave that for the "Default/Single version" RPMs only.

**Comment by remicollet** [comment]
Thanks for the report

I understand your explanation (and perhaps your frustration to see a broken configuration)

But package content is designed to work out of the box when you install a single version (base OR SCL)
Changing the package now will break all existing user configuration, and it is like this for years.

So I don't think this can be changed now.

BTW, this is very quickly detected after installation, and in all case, as soon as you have multiple versions, you MUST configuration (per vhost, directory, project...) which version will be used.

**Comment by remicollet** [comment]
No other feedback so closing
