### ISSUE TITLE
libssh 1.10 for CentOS 7

### ISSUE THREAD

**Issue by hegyre** [remicollet/remirepo#212]
Hello,

As discussed on the [user forum](https://forum.remirepo.net/viewtopic.php?id=4376), I'm opening this in the hope of having libssh 1.10 (or 1.09) for CentOS 7.

This library is used by php-pecl-ssh2, and currently, only libssh v1.08 is available.

I understand that this could be a PITA and time consuming task to maintain on such old distribution, however newer libssh versions have [bugfixes for SFTP](https://www.libssh2.org/changes.html), and so I would be very grateful if you can provide this new version in your repo.

if this is too much of an hassle, I would be glad if maybe you can just share the process that you used to create the [1.8 rpm for Amazon](https://remi.mirror.ate.info/enterprise/7/safe/x86_64/libssh2-1.8.0-0.el7.remi.x86_64.rpm).

Thanks in advance.

**Comment by remicollet** [comment]
1.8.0-0 was a special build, only for amzn2 users, as amzn2 was late on el-7 an still provide 1.4.3 from 7.x to avoid breakage when 1.8.0 was updated in 7.8

Obviously, I don't want to update the system library to not break existing packages.

Plan can be:

- provides **rem-libssh2** installed in /opt/remi for EL-7 and EL-8
- rebuild **php-pecl-libssh2** against it

**Comment by remicollet** [comment]
Update to 1.10.0 and rename to remi-libssh2
https://git.remirepo.net/cgit/rpms/lib/libssh2.git/commit/?id=20e61c0a1471086c99fd346cfd200b865b30bf57

**Comment by remicollet** [comment]
Fix for **php-pecl-ssh2** to use **remi-libssh2**
https://git.remirepo.net/cgit/rpms/php/pecl/php-pecl-ssh2.git/commit/?id=5f7f7c3a0a06d00eda99e635cb29dda42d2c86ad

**Comment by remicollet** [comment]
Build done and uploaded to the repository (PHP 7.0 to 8.1, F34, EL-7 and EL-8)

- remi-libssh2-1.10.1-1
- php-pecl-ssh2-1.3.1-3

Announced: https://twitter.com/RemiRepository/status/1541101164799852545


On EL-8, before:
```
$ php81 --ri ssh2

ssh2

SSH2 support => enabled
extension version => 1.3.1
libssh2 version => 1.9.0
banner => SSH-2.0-libssh2_1.9.0
```

After:
```
$ php81 --ri ssh2

ssh2

SSH2 support => enabled
extension version => 1.3.1
libssh2 version => 1.10.0
banner => SSH-2.0-libssh2_1.10.0
```
