### ISSUE TITLE
aarch64 repository for EL9

### ISSUE THREAD

**Issue by remicollet** [remicollet/remirepo#214]
Because of a lack of resources, and build time (~30x slower), the current plan is

* single distribution: **Enterprise Linux 9**
* only **PHP**
* only  **modules** (no Software Collections)
* only **NTS** build (no ZTS  build)
* only **stable** version, i.e. no build of alpha/beta/RC version
* nearly complete set of packages (feel free to ask for ones missing for you)
* slightly delayed builds, after x86_64 (will try to avoid significant delay)

Current process

- [x] [wizard](https://rpms.remirepo.net/wizard/)
- [x] repository layout
- [x] php 7.4
- [x] php 8.0
- [x] php 8.1
- [x] extensions for 7.4
- [x] extensions for 8.0
- [x] extensions for 8.1

**Comment by remicollet** [comment]
# PHP 7.4:

```
$ php -v
PHP 7.4.30 (cli) (built: Jun  7 2022 08:38:19) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

$ php -i
phpinfo()
PHP Version => 7.4.30

System => Linux rhel9arm 5.14.0-70.17.1.el9_0.aarch64 #1 SMP Tue Jun 14 11:43:56 EDT 2022 aarch64
Build Date => Jun  7 2022 08:38:19
Build System => Red Hat Enterprise Linux release 9.0 (Plow)
Build Provider => Remi's RPM repository <https://rpms.remirepo.net/> #StandWithUkraine

```

**Comment by remicollet** [comment]
Extensions available in remi's streams:

1. **all in official streams**: apcu, rrd, xdebug and zip
2. ast, igbinary, lzf, mailparse, memcache, memcached, msgpack, pcov, rpminfo, selinux, uuid, xattr
3. amqp, apfd, datadog-trace, dio, ds, event, gearman, http, inotify, ip2location, json_post, krb5, mongodb, oauth, pq, propro, raphf, redis, ssdeep, ssh2, uopz, var_representationn, yac, yaconf, yaml

**Comment by anthonydarty** [comment]
4647

**Comment by fishfree** [comment]
Can I use this in CentOS 7? and how to use it, please?

**Comment by remicollet** [comment]
@fishfree see the topic, "aarch64 repository for **EL9**", so not for EL7
Sorry, but not enough resources for additional targets.

**Comment by remicollet** [comment]
Big changes

Thanks to new builder, aarch64 is now a primary arch on EL-9 and probably more targets will come soon (EL-7 ? Fedora ?)

So

- x86_64 and aarch64 are build and published simultenaously
- modules and software collections
- all packages
- testing versions

**Comment by remicollet** [comment]
Thanks to new builder, aarch64 is now also a primary arch on **EL-8**

**Comment by remicollet** [comment]
Thanks to new builder, aarch64 is now also a primary arch on **Fedora 39** (PHP 7.4 to 8.3)
