### ISSUE TITLE
PHP-Packages for PDFLib

### ISSUE THREAD

**Issue by alexgit2k** [remicollet/remirepo#215]
PDFLib is a library for processing PDFs. The [PECL-Version](https://pecl.php.net/package/pdflib) is unmaintained and the latest version from REMI is for PHP 7.4: https://blog.remirepo.net/pages/PECL-extensions-RPM-status

However, the commercial version of [PDFLib](www.pdflib.com) is still maintained (without supplied license PDFlib generated PDFs will have a "www.pdflib.com"-stamp across it). It would be great if you can offer RPM-packages for it.

Files for PHP 8.1:
- [php81-php-pdflib.spec](https://github.com/remicollet/remirepo/files/9221123/php81-php-pdflib-spec.txt)
- [pdflib.ini](https://github.com/remicollet/remirepo/files/9221126/pdflib-ini.txt)

Thanks!

**Comment by remicollet** [comment]
I'm aware of pecl version being unmaintained

Sorry, but I cannot use the commercial library.

**Comment by alexgit2k** [comment]
Thanks for our fast reply!

Are there any (legal) issues for offering the commercial library in a RPM? It is freely downloadable from the companies website for everyone and unless supplied with a license just prints a stamp on each PDF.
Or is it your policy to not offer commercial libraries?

**Comment by remicollet** [comment]
I'm not a legal expert, and their licensing is a mess for years...
So, I don't want to (risk to) provide illegal content

And definitively, I hate non Open Source products.

**Comment by alexgit2k** [comment]
I understand, but thanks for your time!

So I'm closing this ticket now.
