### ISSUE TITLE
Unable to load dynamic library 'zip.so' ... undefined symbol: zip_file_is_seekable 

### ISSUE THREAD

**Issue by mazation** [remicollet/remirepo#217]
I got this error.
Fedora 36
```
 $ php74 --ri zip
PHP Warning:  PHP Startup: Unable to load dynamic library 'zip.so' (tried: /opt/remi/php74/root/usr/lib64/php/modules/zip.so (/opt/remi/php74/root/usr/lib64/php/modules/zip.so: undefined symbol: zip_file_is_seekable), /opt/remi/php74/root/usr/lib64/php/modules/zip.so.so (/opt/remi/php74/root/usr/lib64/php/modules/zip.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
Extension 'zip' not present.
```
I tried reinstalling php74-php package and also I tried solution from https://github.com/remicollet/remirepo/issues/182 but it didn't work

**Comment by mazation** [comment]
Of course I solved it right after creating an issue. Sorry for that. I was trying to resolve it for 3 hours and it drove me nuts.
`sudo dnf install --best --allowerasing php-pecl-zip`
There was a problem in installing dependencies. After that command everything is fine

**Comment by remicollet** [comment]
> There was a problem in installing dependencies.

I'm curious to know what problem, and what need to be removed ?

BTW, this should not happen as the proper requirement are there (to ensure all needed symbols are there)

```
$ rpm -qp --requires fedora/36/php74/x86_64/php-pecl-zip-1.21.0-3.fc36.remi.7.4.x86_64.rpm 
libzip(x86-64) >= 1.9.2
...
$ rpm -qp --requires fedora/36/remi/x86_64/php74-php-pecl-zip-1.21.0-3.fc36.remi.x86_64.rpm
libzip(x86-64) >= 1.9.2
...

```
