### ISSUE TITLE
website: remi-php74 links to php81 instead of php74 for Fedora 35 & 36

### ISSUE THREAD

**Issue by Whissi** [remicollet/remirepo#218]
Hi,

I just noticed that the link to "remi-php74 (only PHP 7.4 and extensions)" on https://rpms.remirepo.net/fedora/35/ and https://rpms.remirepo.net/fedora/36/ are pointing to php81 instead of php74:

![remirepo-php74-links](https://user-images.githubusercontent.com/729436/183549223-2bb7e4c8-7690-487b-b16b-bbff4db8ded2.png)

**Comment by remicollet** [comment]
Thanks for the notice.

Fixed.
