### ISSUE TITLE
Request: php81 Snappy module on EL7

### ISSUE THREAD

**Issue by lvance-lw** [remicollet/remirepo#223]
Hi there! Would it be possible to make Snappy module is available in EL7 php81 repos? It is often recommended for compression as it's the most suitable library in many cases and EL7 is still very commonly used. Seems that `php-snappy` is available for EL9 only at this moment. Many thanks for all the work!

**Comment by remicollet** [comment]
Indeed, snappy was missing for 8.1 (it is available for 5.4 to 8.2)

Built and uploaded.


P.S. please notice that **EL-7 is >8 years** old, close to its end of live. Everything is old there so, for modern features (such as PHP 8+) I recommend updating to a more recent version (EL-8 or EL-9)
