### ISSUE TITLE
php-fpm.conf include directive is not in the same place as in upstream's default config, cannot override the global options

### ISSUE THREAD

**Issue by flora-five** [remicollet/remirepo#225]
In php-fpm.conf, the `include=/etc/php-fpm.d/*.conf` directive appears before the `[global]` section. While it is possible to use local configuration files to override the default `www` pool options, it's not possible to override the global options. In the upstream's php-fpm.conf file, the include directive appears after the `[global]` section and the users of it (and probably the users of other distributions too) may use local configuration files to override both the global options and the default pool options.

I'm not sure if this difference is intentional. I can see that Remi has created the split fpm config for the rpm package in 2010 and Remi has contributed it upstream in 2014, https://bugs.php.net/bug.php?id=67106, but with the different placement of the include directive.

Allowing the override of the global options by placing the include directive after the `[global]` section, as in upstream, would be good and nice to have, as it will match the upstream functionality and it is more flexible. Could you, please, consider this change? I hope that there are no cases of very few cases of people with custom config files in `php-fpm.d` that contain a `[global]` section.

**Comment by remicollet** [comment]
I understand...

> Could you, please, consider this change?

I need to think a bit more about this change, and how it may break things for existing installation
(especially as the file is like this for >10 years)
and fixing installed php-fpm.conf is a workaround (config file are not replaced on update)

Perhaps better to postpone for next major version (8.3) ?

**Comment by remicollet** [comment]
BTW, I don't see any use case for overloading value from [global]...  if you can give one ?

**Comment by flora-five** [comment]
> Perhaps better to postpone for next major version (8.3) ?

That seems good too. How about the official Fedora/RHEL/CentOS rpms? Would you make this change on them too or it would be necessary to open requests for them?

**Comment by flora-five** [comment]
> BTW, I don't see any use case for overloading value from [global]... if you can give one ?

In my particular case (and using the official CentOS rpms actually), I would like to change error_log to syslog, to send the error log to journald for further collecting/processing.

An example from SO: https://serverfault.com/questions/805647/override-php-fpm-pool-config-values-with-another-file#comment1298258_806530

**Comment by remicollet** [comment]
> That seems good too. How about the official Fedora/RHEL/CentOS rpms?

Don't expect such change in stable version

> Would you make this change on them too or it would be necessary to open requests for them?

Usual road is Remi's repo => Fedora => CentOS Stream => RHEL => Clones

**Comment by remicollet** [comment]
So, after more thinking during the week-end, I choose to fix this in PHP 8.2

In my repository

* Module: https://git.remirepo.net/cgit/rpms/php/php82.git/commit/?id=a490fbcf113ac2d188515b5d83a1aec4147a2174
* SCL: https://git.remirepo.net/cgit/rpms/scl-php82/php.git/commit/?id=a2c63c8845e5ecfc10f120fbfc139ae2d8ad5aee

And thus, also in Fedora 38

* https://src.fedoraproject.org/rpms/php/c/0238007d88969f5e58c6da0df26260e79e1d1ebf?branch=rawhide

**Comment by remicollet** [comment]
New build available in the testing repository

* in remi-modular-test: php-8.2.1~RC1-2
* in remi-test (SCL): php82-php-8.2.1~RC1-2

Feedback welcome.

**Comment by flora-five** [comment]
Tested php-8.2.1~RC1-2 and it worked well, thank you!

**Comment by remicollet** [comment]
Closing as 8.2.1 is now in the repostiory
