### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by Ricky-Tigg** [remicollet/remirepo#226]
**servuce:** https://rpms.remirepo.net/rpmphp/. **RPMPHP v.:** 1.0.0-dev. **FedoraClient v.:** 0.3.0-dev.

Hello. A package attested present within an OS that is covered by this service's search tool may not be found. Test-case:
- **Package a search query is made against:** _json-c-devel_
- **Result of the query:** package not found.

Attestation of the presence of such package within Fedora's main repository during a session of Fedora.
```
$ dnf -q rq --archlist noarch,x86_64 --qf '%{name} %{version} %{release} | %{summary} | %{url} | %{reponame}' json-c-devel
json-c-devel 0.16 2.fc37 | Development files for json-c | https://github.com/json-c/json-c | fedora
```

**Comment by remicollet** [comment]
This app is for version tracking, and only source package are indexed (so json-c, not json-c-devel)

**Comment by Ricky-Tigg** [comment]
And of course. It wouldn't occur to you that there's little sense in deciding to include some packages in a search query and excluding others, nor to consider bringing to your scenario any improvement. _C'est la vie_, and _C'est comme ça_, or some other stereotyped phrase you must be used to saying in such a situation.
