### ISSUE TITLE
roundcube 1.6.1 update breaks calendar plugin

### ISSUE THREAD

**Issue by vgiralt** [remicollet/remirepo#230]
My roundcubemail was upgraded on Jan 29th to 1.6.1 and calendar broke. We have tried on php7.4 and 8.2 with same results.
This breakage prevents the messages to be displayed if calendar is in the plugin list. When it is removed, messages display again.
This is what the log shows:
[31-Jan-2023 09:46:06 Europe/Madrid] PHP Fatal error:  Uncaught Error: Class "Sabre\VObject\Property\Text" not found in /usr/share/roundcubemail/plugins/libcalendaring/libvcalendar.php:1515
Stack trace:                                                                                                #0 /usr/share/roundcubemail/plugins/libcalendaring/libcalendaring.php(158): require_once()                  #1 /usr/share/roundcubemail/plugins/libcalendaring/libcalendaring.php(1144): libcalendaring::get_ical()     #2 /usr/share/roundcubemail/plugins/calendar/calendar.php(3205): libcalendaring->get_mail_ical_objects()    #3 /usr/share/roundcubemail/program/lib/Roundcube/rcube_plugin_api.php(518): calendar->mail_messagebody_html(Array)                                                                                                     #4 /usr/share/roundcubemail/program/include/rcmail_output_html.php(1615): rcube_plugin_api->exec_hook('template_object...', Array)                                                                                      #5 [internal function]: rcmail_output_html->xml_command(Array)                                              #6 /usr/share/roundcubemail/program/include/rcmail_output_html.php(1322): preg_replace_callback('/<roundcube:([-...', Array, '<roundcube:incl...')                                                                      #7 /usr/share/roundcubemail/program/include/rcmail_output_html.php(825): rcmail_output_html->parse_xml('<roundcube:incl...')                                                                                            #8 /usr/share/roundcubemail/program/include/rcmail_output_html.php(654): rcmail_output_html->parse('message', false)                                                                                                    #9 /usr/share/roundcubemail/program/actions/mail/show.php(164): rcmail_output_html->send('message', false)  #10 /usr/share/roundcubemail/program/include/rcmail.php(282): rcmail_action_mail_show->run(Array)           #11 /usr/share/roundcubemail/index.php(278): rcmail->action_handler()                                       #12 {main}                                                                                                    thrown in /usr/share/roundcubemail/plugins/libcalendaring/libvcalendar.php on line 1515

**Comment by remicollet** [comment]
I think after you update roundcubemail, you also have to reinstall every plugin to regenerate the composer autoloader.

Just try a `composer require kolab/libcalendaring` and everything seems to work as expected

**Comment by vgiralt** [comment]
It worked! Thanks Remi, I've been using your repo for ages. I knew this was my safe bet after finding a lot of not working solutions by googling. And I was right, blazing fast and perfect response.
