### ISSUE TITLE
Missing patch file from gd.git

### ISSUE THREAD

**Issue by dalebowie** [remicollet/remirepo#232]
In [this commit](https://git.remirepo.net/cgit/rpms/lib/gd.git/commit/?id=996c8728cb22e41f1c85787e7f400f249c993be3), a new _libgd-bumpsoname.patch_ file is referenced but that hasn't been committed into [the repo](https://git.remirepo.net/cgit/rpms/lib/gd.git/tree/). Is there any chance the missing file could please be added?

**Comment by remicollet** [comment]
Sorry for the missing file

Added

**Comment by dalebowie** [comment]
Thanks for the quick resolution!
