### ISSUE TITLE
php-snuffleupagus for the default PHP on Fedora

### ISSUE THREAD

**Issue by JGoutin** [remicollet/remirepo#236]
Hello,

Is it possible to have the `php-snuffleupagus` package for the base PHP version of Fedora ?

I see that this package already exists for some specific PHP versions (Like `php81-php-snuffleupagus`).

Note: I am using Fedora 38 with its default PHP 8.2

Thanks.

**Comment by remicollet** [comment]
Fedora only provides PHP version 8.2 and a small set of extensions (most asked ones)

My repository provides 4 alternative stacks (7.4 to 8.2), and 8.3 coming soon, with [most extensions](https://blog.remirepo.net/pages/PECL-extensions-RPM-status)

If you want something not in Fedora, you have to switch the stack used.

See the [Wizard instructions](https://rpms.remirepo.net/wizard/).

There is no plan to provide extensions for official Fedora stack in my repo.
When I choose to do this, I simply add it to official repository.

As I also maintain PHP in Fedora, and as my repo is used as upstream for Fedora (ex PHP 8.3 will appear here, and later in Fedora, probably for F40) ou should not notice any difference (excepted more features, such as snuffleupagus ext)

**Comment by JGoutin** [comment]
Thank you for the help, the information and useful links. And more generally, thank you also for your work on the repository.

I successfully setup the PHP stack in my Ansible.

Also, concerning the wizard. Maybe you already known about it, there is also the [`dnf module switch-to php:remi-8.2`](https://dnf.readthedocs.io/en/latest/command_ref.html#module-command-label) command that look to be a shortcut to `dnf module reset` + `dnf module install php:remi-8.2` + `dnf update`.
