### ISSUE TITLE
Request: pdlib for PHP >= 8.1

### ISSUE THREAD

**Issue by jyrkij** [remicollet/remirepo#238]
In #177 `pdlib` was marked as not ready.  Any chance of checking this again and building `pdlib` for all current PHP versions >= 8.1?

**Comment by remicollet** [comment]
I will have a look.

Main issue is to fix the build of dlib on recent Fedora/EL version
IIRC I forgive because lack of time and lack of stills on BLAS stuff, and this stack already require bug patching... :s

**Comment by jyrkij** [comment]
Sounds troublesome if it doesn't compile easily.

There are `openblas` packages in `powertools` repo, at least for Rocky 8.8.  Would they be of any help?

**Comment by remicollet** [comment]
OK, so the builds are running (PHP 7.0 to 8.2)

- Fedora will use **dlib 19.24** from official repository
- EL-7 and EL-8 will use old **dblib 19.22** from my repository
- EL-9 will use **dblib 19.24** from my repository (rebuild from F36, waiting for #[2219855](https://bugzilla.redhat.com/show_bug.cgi?id=2219855)

**Comment by remicollet** [comment]
x86_64 builds are uploaded to the repository
aarch64 builds coming soon

https://twitter.com/RemiRepository/status/1676634407614947330

**Comment by remicollet** [comment]
New builds (1.1.0-2, fixing displayed extension version) is now available (all arches, all versions)

**Comment by remicollet** [comment]
no feedback, closing

**Comment by jyrkij** [comment]
Sorry for not answering, haven't been close to a computer in a while.  Thank you for building pdlib, it seems to be working!
