### ISSUE TITLE
Should not override PHP session settings in php.conf

### ISSUE THREAD

**Issue by peterkeung** [remicollet/remirepo#24]
In php.conf, you set these values:

    #
    # Apache specific PHP configuration options
    # those can be override in each configured vhost
    #
    php_value session.save_handler "files"
    php_value session.save_path    "/var/lib/php/session"

These are not intuitive to find if you are troubleshooting why your php.ini values are not taking effect. Why not comment these out as an example only, and if they're important for the basic setup, set them in php.ini?

**Comment by remicollet** [comment]
IN php.ini you have a comment explaining where to change these values.

    ; RPM note : session directory must be owned by process owner
    ; for mod_php, see /etc/httpd/conf.d/php.conf
    ; for php-fpm, see /etc/php-fpm.d/*conf
    ;session.save_path = "/tmp"

**Comment by remicollet** [comment]
Keeping default values set in php.ini create more issues.

- script run by "root" will create file which be clean by "apache" user
- script run by other can't write in this directory

And this settings give a tips how to correctly set such values, per user (apache vhost or fpm pool).
