### ISSUE TITLE
PHP 5.6 OCI8 crashes Apache (prefork) when reloading service

### ISSUE THREAD

**Issue by MxD-Sans** [remicollet/remirepo#243]
Hello. I realize PHP 5.6 is horribly outdated and EoL'd years ago, but submitting just in the off-case it could actually get resolved.

I have two machines, one running Oracle Linux (RH-based) **7.9** and the other **8.8**. Apache HTTPD versions below:
httpd-2.4.6-99.0.1.el7_9.1.x86_64
httpd-2.4.37-56.module+el8.8.0+18758+b3a9c8da.6.x86_64

Both Apache instances are configured with the **mpm_prefork** module, as the old application (that cannot really be updated) doesn't play nicely with php-fpm.

Affected Packages:
php-oci8-5.6.40-39.el7.remi.x86_64
php56-php-oci8-5.6.40-39.el8.remi.x86_64

When attempting to reload the Apache HTTPD service (systemctl reload httpd , apachectl -k graceful), the daemon segfaults and doesn't recover until a restart (systemctl restart httpd).
Issue was discovered when logrotate attempted to rotate the Apache logs, reloading the HTTPD service in the process.

Complete reproduction steps:
1. Install Remi Release & EPEL Release packages for your testing distribution, on RH 7 / 8 or alternative
 - Also enable the php56 repo on RH 7
2. Install the latest available httpd, php-oci8, mod_php, oracle-instantclient packages
2.a: RH7
 - yum install [oracle-instantclient-basic-21.11.0.0.0-1.x86_64.rpm](https://download.oracle.com/otn_software/linux/instantclient/2111000/oracle-instantclient-basic-21.11.0.0.0-1.x86_64.rpm)
 - yum install httpd mod_php php-oci8
2.b: RH8
 - yum install [oracle-instantclient-basic-21.11.0.0.0-1.el8.x86_64.rpm](https://download.oracle.com/otn_software/linux/instantclient/2111000/oracle-instantclient-basic-21.11.0.0.0-1.el8.x86_64.rpm)
 - yum install httpd php56-mod_php php56-php-oci8
3. Change the Apache MPM module in /etc/httpd/conf.modules.d/00-mpm.conf to mpm_prefork_module, deactivating mpm_event_module
4. Start the HTTPD service
 - systemctl start httpd
5. Attempt to reload the HTTPD service
 - systemctl reload httpd | OR | apachectl -k graceful
6. Check on Apache
 - systemctl status httpd
 
Both cases were attempted on the latest available system updates for the distros, HTTPD 2.4.6 on an actual VM (OL7) and HTTPD 2.4.37 in an RH/UBI8 container (OL9).
 
 Thanks a lot,
 MxD

**Comment by remicollet** [comment]
I was able to reproduce it immediately after the installation
Later, no more segfault

BTW
- EL-7 is terrible old, close to its EOL in a few month
- PHP 5.6... :(
- mod_php... :(

I urgently recommend switching to fpm, which has better process isolation, and may avoid such issue.

BTW I think this is related to a library conflict, but **I won't be able to debug** as oracle-instantclient is closed sources.

> (that cannot really be updated) doesn't play nicely with php-fpm.

I'm not aware of any issue with FPM
Only missing getallheaders function https://www.php.net/getallheaders
But this one exists in PHP 7.3+ and in 7.1+ from my repository
and  pure-PHP alternatives exist, ex: https://packagist.org/packages/ralouphie/getallheaders

**Comment by MxD-Sans** [comment]
I am currently in the process of moving a bunch of machines from EL-7 to EL-9, running RH/UBI8 containers for PHP 5.6 from RemiRepo.
And the headers issue is exactly the problem with the application, as it heavily relies on headers (Soap API) and this [Apache Issue](https://bz.apache.org/bugzilla/show_bug.cgi?id=64919) kills my attempts to run PHP-FPM.

Honestly, it would've been really easy to just throw PHP-FPM in a container and use the latest available Apache from system repos with it, and that's exactly what I'm going to do with other apps that share the same fate but don't have the same issues (some of which being almost entirely encrypted/compiled with IonCube for PHP 5.X, which cannot run on, or even be ported to, PHP 7.4 or newer).

**Comment by remicollet** [comment]
Closing as (sadly) I have to way to investigate and fix this
