### ISSUE TITLE
unit shouldn't require systemd

### ISSUE THREAD

**Issue by mu1f407** [remicollet/remirepo#245]
Hi Remi,

I think that hard `systemd` dependency in the [unit](https://git.remirepo.net/cgit/rpms/unit.git) package is not necessary. Unit works well without it. It is mostly noticeable in container images. In my use case, in an image based on ubi9-minimal, the resulting image size is 109 MB (3 deps installed) without systemd (using fakeprovide package instead) vs 142 MB (25 deps installed) with systemd.

Probably the `%{?systemd_requires}` in spec file could be replaced with `%{?systemd_ordering}` as [written in docs](https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/#_dependencies_on_the_systemd_package)?

Thank you!

**Comment by remicollet** [comment]
Will take a look

Notice: ubi*-**minimal** have lof ot issue, with PHP, especially missing **tzdata**, I usually don't recommend it

**Comment by remicollet** [comment]
Fixed by https://git.remirepo.net/cgit/rpms/unit.git/commit/?id=bcbc4b9e504eaf36078cefda483d513a33cfb125

**Comment by remicollet** [comment]
New build (1.31.1-2) is now available in the repository

**Comment by mu1f407** [comment]
Thank you for quick update! Even though systemd is still pulled in through logrotate as dependency. My bad, I didn't checked carefully all packages which requires systemd before, sorry. :man_facepalming: 

Regarding the ubi-minimal issues, yes, I also faced the tzdata bug, but found a simple workaround to run `microdnf reinstall tzdata` which resolves it. Otherwise everything runs fine, including oci8. But it can be little hacky sometimes.

I'm closing this issue. Thank you for your work! :slightly_smiling_face:
