### ISSUE TITLE
vips unable to generate heif image

### ISSUE THREAD

**Issue by devhaozi** [remicollet/remirepo#248]
I install `vips` and `vips-heif` and `vips-tools` packages on AlmaLinux 9.3, and I try to use `vips copy 1.png 1.heif` to convert a png image to heif, it return error `heifsave: Unsupported compression`.

![image](https://github.com/remicollet/remirepo/assets/115467771/ff6a6c54-34f4-4845-a1f8-f76c38ab6d87)

I've also tried other encodings such as avif jxl and they all work fine.

**Comment by devhaozi** [comment]
https://github.com/libvips/libvips/discussions/3173 may help.

**Comment by remicollet** [comment]
I was able to reproduce on EL-9 with **libheif 1.16.1**, but only once... so **Heisenbug**

libheif seems OK 
```
$ heif-enc 1.png
$ file 1.heic
1.heic: ISO Media, HEIF Image HEVC Main or Main Still Picture Profile

$ heif-convert 1.heic  1.jpg
File contains 1 image
Written to 1.jpg
$ file 1.jpg 
1.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, baseline, precision 8, 420x460, components 3
```

```
$ vips copy 1.png 1.heic
$ file 1.png 1.heic
1.png:  PNG image data, 420 x 460, 8-bit/color RGBA, non-interlaced
1.heic: ISO Media, HEIF Image HEVC Main or Main Still Picture Profile

$ vips copy 1.heic x.png
$ file 1.heic x.png
1.heic: ISO Media, HEIF Image HEVC Main or Main Still Picture Profile
x.png:  PNG image data, 420 x 460, 8-bit/color RGBA, non-interlaced

```

**Comment by remicollet** [comment]
Ok, found:

# vips copy 1.png 1.heic
heifsave: Unsupported compression
# dnf install libheif-freeworld
...
# vips copy 1.png 1.heic

This mean additional codecs (not suitable for **EPEL**) are available in **RPMfusion**

**Comment by remicollet** [comment]
For next vips build, I will add a weak dependency on the libheif-freeworld, but this will only work if RPMFusion is enabled.

**Comment by devhaozi** [comment]
> For next vips build, I will add a weak dependency on the libheif-freeworld, but this will only work if RPMFusion is enabled.

After enable RPMfusion and install `libheif-freeworld`, it works well.
