### ISSUE TITLE
Report only available SAPIs in php-config

### ISSUE THREAD

**Issue by edlman** [remicollet/remirepo#25]
Hello,

I created this patch to php-config so it reports available SAPIs only. And adds 'embed' SAPI. If you find is useful, please use it.

Patch in on [this link](https://drive.google.com/file/d/0BxbgjCVegAuOWU1BV2dJaGFIcWc/view?usp=sharing) (I cannot upload it here, GitHub complains "Attaching documents requires write permission to this repository").

Martin

**Comment by remicollet** [comment]
Simple way implemented in 579c5d898481177551bc3390e93f414c34392e7f
