### ISSUE TITLE
[EL9] php-* repo files don't get installed with remi-release-9

### ISSUE THREAD

**Issue by crussell52** [remicollet/remirepo#252]
Noticed that the `php-*` repo files do not get installed when remi-release-9 is installed. However they are listed on the repo web page (see screen cap)

The repos do exist and a manually crafted repo file mostly works as expected.  (The mirrorlist page is `404`'d, but baseurl works)

![image](https://github.com/remicollet/remirepo/assets/375294/8258f9fe-928b-4171-9dd1-5e30e994375b)

**Comment by remicollet** [comment]
The **remi-php*** directories are build artefacts, and are shown on the home page only for browsing.

All the packages are available in the **remi-modular** repository

See the [Wizard](https://rpms.remirepo.net/wizard/) instructions for a proper repository configuration and usage.

**Comment by remicollet** [comment]
Comment added on the main page:
> not a repository, only for browsing

**Comment by crussell52** [comment]
Thank you for fast clarification! I made some assumptions based on experience with your EL7 repos. Appreciate you!
