### ISSUE TITLE
Small website display issue for https://rpms.remirepo.net/enterprise/9/

### ISSUE THREAD

**Issue by hegyre** [remicollet/remirepo#253]
As shown on #252:

Currently on https://rpms.remirepo.net/enterprise/9/:
`Enterprise Linux 9 - RHEL 8 (Plow) and Clones`

Should'nt be: Enterprise Linux 9 - RHEL **9** (Plow) and Clones ?

**Comment by remicollet** [comment]
Thanks,
Fixed
