### ISSUE TITLE
Fedora 41, Remi's repo and the state of modules in dnf5

### ISSUE THREAD

**Issue by PatrickJosh** [remicollet/remirepo#257]
Hello,

Firstly, thank you very much for providing this repo. It helps a lot when dealing with applications which require a specific version of PHP.

Secondly, I have some questions regarding the support of dnf modules in this repo. 
Fedora recently dropped any support for modules in dnf. Moreover, in dnf5, the `module` subcommand will probably not be implemented when Fedora 41 is released (see [this issue](https://github.com/rpm-software-management/dnf5/issues/146)), but Fedora will most likely [switch to dnf5 starting from Fedora 41](https://fedoraproject.org/wiki/Changes/SwitchToDnf5). However, the [configuration wizard](https://rpms.remirepo.net/wizard/) for this repo still advises to use modules with Fedora 40.
What are the plans regarding the recommended installation method of this repo's packages from Fedora 41 onwards? Since modules are most likely unsupported by dnf5, at least in the beginning, will there be an alternative that enables users to switch between php versions? And for users currently using dnf modules with this repo, like me, how will the migration look like?

Thanks very much!

**Comment by remicollet** [comment]
I'm aware of the problem
Read : https://blog.remirepo.net/post/2024/03/29/DNF-5-and-Modularity

Don't know yet how I will manage this,
perhaps as in the old EL-7 time: 1 repo per version

**Comment by PatrickJosh** [comment]
Ah, thanks for pointing me to your blog post. I had searched the forum and the website, but I didn't find your blog. Sorry for that.

Also thank you for making the effort to continue supporting multiple versions. I do share your sadness on the abandonment of modularity. I think it was a pretty neat and easy to use solution.

I don't now how dnf handles that, but I could imagine that having multiple repos for the different versions could work quite well as well, at least in the case that you want to upgrade to a newer major version. Enable the new repo, upgrade, and disable the old repo, for example? Downgrading would probably be more of a hassle since you probably need the downgrade command and have to disable the newer repo beforehand. Could that work? I have to say though that I have no experience in maintaining any packages nor repos. I just wanted to say that I could imagine such a workflow form a user's perspective.

Since my question's been answered, you can close the issue if you want to, or leave it open till a solution is found.

**Comment by remicollet** [comment]
> Enable the new repo, upgrade, and disable the old repo, for example?

Yes

> Downgrading would probably be more of a hassle since you probably need the downgrade command and have to disable the newer repo beforehand. Could that work?

Yes, and "distrosync" may be simpler

**Comment by remicollet** [comment]
Closing as I will create a tracker ticket for Fedora 41 repo (when branched)
