### ISSUE TITLE
Possible to provide a php-pgsql94-x.x.x rpm?

### ISSUE THREAD

**Issue by earsdown** [remicollet/remirepo#26]
Hi Remi

Thanks for the awesome work you with this repo. I've been [digging](https://github.com/mayflower/puppet-php/issues/138) around to work out why phpinfo tells me I'm running a postgres 9.2.7 client library version even though I only have postgres 9.4 installed (via yum.postgresql.org). I think I've tracked it down to the php-pgsql-X.X.X-1.el7.remi.x86_64 package which was produced by the phpXX.spec file that links using `--with-pgsql=shared`.

Would it be possible to provide php-pgsql94.x.x.x RPMs as well? That would be awesome.

Cheers

**Comment by remicollet** [comment]
How is this an issue ?
The system client library  (9.2 here) allow you to work with other Server versions (9.4 here) (I even have tried client 8.4 in C6 to connect to serveur 9.2 in C7, it just works)

The main problem with using a newer version of postgresql, is that it doesn't exists in official repository, and I can't imagine relying on another 3rd party repo.

And this also mean I will have to build for 9.0, 9.2, 9.4 (for C6).

**Comment by earsdown** [comment]
Most enterprises I've seen either stick with the official repos (and use php54+postgres92), or they are prepared to use third party repos to bring in newer versions of software. If they prefer to use remi-php56 repo, then they probably also prefer to use yum.postgresql.org.

For production systems, I'm concerned that using an older system client library could cause undefined/untested behaviour, which would be difficult to identify and/or troubleshoot. This combination does not appear in unit/system tests by either project. I wasn't able to find any other RPM repo that provides a pgsql94 client library either.

To build it, yeah I guess the simplest approach would be to use yum.postgresql.org repos. And yeah, I'm sure others would benefit if you also built it for other versions of pgsql as well. Let me know if you think the feature needs sponsoring. Much appreciated.
