### ISSUE TITLE
Error with php-pecl-yaz

### ISSUE THREAD

**Issue by killerpapy** [remicollet/remirepo#260]
Hello,

I have an error with php-pecl-yaz (php 8.2)

My OS version : Red Hat Enterprise Linux release 9.4 (Plow)

![image](https://github.com/user-attachments/assets/a1c9e2e7-e9b8-4059-af47-23db8df20b7d)

Thank you !

**Comment by remicollet** [comment]
You need to enable **codeready-builder-for-rhel-9-x86_64-rpms** channel which provides **libmemcached-awesome**

As explained bt the [Wizard](https://rpms.remirepo.net/wizard/)

`    subscription-manager repos --enable codeready-builder-for-rhel-9-x86_64-rpms`

**Comment by killerpapy** [comment]
Thank you verry much !
