### ISSUE TITLE
access to repositories on git.remirepo.net always returns 500 error since mid-July

### ISSUE THREAD

**Issue by mdei** [remicollet/remirepo#262]
I can't pull or fetch from git.remirepo.net since mid-July

$ git clone https://git.remirepo.net/git/rpms/php/php82.git
Cloning into 'php82'...
fatal: unable to access 'https://git.remirepo.net/git/rpms/php/php82.git/': The requested URL returned error: 500

$ git --version
git version 2.45.2

Thank you!

**Comment by remicollet** [comment]
Error in  log

`fatal: detected dubious ownership in repository at ...`

Seems related to new security option (safe.directory)

**Comment by remicollet** [comment]
Temporary workaround:

* downgrade from git 2.43.5 (from 8.10) to 2.39.3 (from 8.9)

Seems to work, but this is only an unsecured workaround... need a real solution

**Comment by remicollet** [comment]
Proper fix applied (using `safe.directory = * `in /etc/gitconfig)

Notice: better fix `safe.directory = /path/to/git/* ` is not supported by git 2.43.5 (higher version seems required)

**Comment by mdei** [comment]
Now I can access to git.remirepo.net

Thanks a lot.
