### ISSUE TITLE
Inquiry about Syncing and Distributing Remi Repository

### ISSUE THREAD

**Issue by 89ao** [remicollet/remirepo#266]
Hello Remi Collet and Team,

My name is moto and I represent my company. We have been using the Remi repository for some time now and have found it to be an invaluable resource for our team, providing us with the latest versions of software packages that are crucial for our development and operations.

We are interested in syncing and distributing the software packages from the Remi repository to better serve our user community and ensure they receive timely updates. To proceed with this, we have a few questions that we hope you can clarify:

Is it permissible for third-party organizations to sync the Remi repository's software packages?
If so, what specific terms and conditions must we adhere to?
Are there any agreements or licensing requirements we need to be aware of?
What technical details or best practices should we consider during the syncing process?
We respect intellectual property and copyright laws and wish to ensure that we have your explicit permission and guidance before proceeding with any syncing or distribution activities.

Thank you for taking the time to consider our inquiry. We look forward to your response and the possibility of working together. Please feel free to contact us at [Your Email Address] or [Your Phone Number] for further discussion.

Best regards,

**Comment by remicollet** [comment]
For **private** mirror, you can rsync  from any mirror with rsync enabled
search for rsync in https://rpms.remirepo.net/

For public/official mirror, I prefer to use email contact
notice that I'm use to request to be able to retrieve mirror access log for stat computation

A sync script exists, see https://git.remirepo.net/cgit/tools/helpers.git/plain/mirrorsync

**Comment by remicollet** [comment]
No news,
Closing

**Comment by 89ao** [comment]
thanks a lot @remicollet . But it seems that I can't find out how much your email address is.What's more , May I ask how I should apply to become an officially recommended repository such as https://rpms.remirepo.net/?

**Comment by remicollet** [comment]
Use `remi AT remirepo DOT net`
