### ISSUE TITLE
PHP 7.4 file_get_contents() not working with OpenSSL v3

### ISSUE THREAD

**Issue by roooxvee** [remicollet/remirepo#267]
Hello,

I'm using PHP 7.4 on Rocky Linux 9 (using OpenSSL v3) and I'm getting following error when using file_get_contents() function:
Error ErrorException: file_get_contents(): SSL operation failed with code 1.
OpenSSL Error messages: error:0A000126:SSL routines::unexpected eof

After searching for a while, I found that this problem was fixed in PHP 8.1.7
https://www.php.net/ChangeLog-8.php#8.1.7
https://bugs.php.net/bug.php?id=79589
https://github.com/php/php-src/commit/74f75db0c3665677ec006cd379fd561feacffdc6

Any chance to add the patch to your PHP 7.4 remi as well?

**Comment by remicollet** [comment]
Will check if can be applied

Cannot reproduce

```
$ php74 -r 'var_dump(file_get_contents("https://rpms.remirepo.net/fedora/40/remi/x86_64/httpsmirror"));'
string(1307) "https..."
```
Can you provide a simple reproducer ?

**Comment by roooxvee** [comment]
Hm, it's working with your test.
Try with www.google.com for example.

php74 -r 'var_dump(file_get_contents("https://www.google.com"));'
PHP Warning:  file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:0A000126:SSL routines::unexpected eof while reading in Command line code on line 1
......

**Comment by remicollet** [comment]
Reproduced, working on backporting the fix

**Comment by remicollet** [comment]
Backported to 8.0, in **8.0.30-8**:
* https://git.remirepo.net/cgit/rpms/php/php80.git/commit/?id=62b12f3195f27b5bcffcbf64a58e2aed778dd56f
* https://git.remirepo.net/cgit/rpms/scl-php80/php.git/commit/?id=a3bc7da51b195f073fd549371b7814866fa15650

**Comment by remicollet** [comment]
New builds uploaded and announced
https://x.com/RemiRepository/status/1828070200492662971

**Comment by neufeind** [comment]
Works for me with PHP 7.4 against internal Microsoft-IIS which previously triggered the issue. Thanks a lot.

**Comment by roooxvee** [comment]
Remi thank you. It works for me too :)
