### ISSUE TITLE
Issue installing php-oci8-8.1.29-2.el8.remi.x86_64

### ISSUE THREAD

**Issue by nm-dlh** [remicollet/remirepo#268]
While trying to install or update this package php-oci8-8.1.29-2.el8.remi.x86_64 I am getting

"nothing provides libclntsh.so.23.1 needed by php-oci8-8.1.29-2.el8.remi.x86_64" 

I saw this in the past and I think it was quickly fixed on an update to the package

steps to reproduce
from rhel8/alma8/rock8
set module for remi php8.1
dnf install php php-oci8

**Comment by remicollet** [comment]
See the pinned issue #255

**Comment by nm-dlh** [comment]
Thanks will give that a try. Now that you mentioned it I think that is how I resolved last time and just forgot
