### ISSUE TITLE
PHP83: Upgrading fpm installs a new www.conf in /etc/opt/remi/php83/php-fpm.d/

### ISSUE THREAD

**Issue by idc77** [remicollet/remirepo#270]
I have my own pool defined and removed the www.conf file from /etc/opt/remi/php83/php-fpm.d .
Now I have upgraded the package via dnf and a new www.conf waas placed in this directory.
This is not desired behaviour, as it spawns 2 www.conf assocated workers.

What can be done so that this doesn't happen again?

**Comment by remicollet** [comment]
> Now I have upgraded the package via dnf and a new [www.conf](http://www.conf/) waas placed in this directory.

This is the expected behavior

> I have my own pool defined and removed the [www.conf](http://www.conf/) file from /etc/opt/remi/php83/php-fpm.d .

Comment out the content of the provided www.conf

**Comment by idc77** [comment]
Thanks but this is a workaround, not a solution.
No files, except initially, should be created there.
For various reasons there are multiple pool definitions in separate files and directories (per user, per php version)
I guess it's a limitation of dnf.
On Gentoo there's this etc-update command which does a diff and you can say ignore changes. I doubt there's something like this in dnf.
Ah well, I guess when in Rome do as Romans do.

**Comment by remicollet** [comment]
This is the common behavior for config files with RPM.
