### ISSUE TITLE
Cannot prepare internal mirrorlist: No URLs in mirrorlist

### ISSUE THREAD

**Issue by daerlnaxe** [remicollet/remirepo#271]
Hi,

(First i'm French and very bad in english)

We met a problem in professionnal environment, the biggest is it's a managed OS and i can't do what i want, and we are behind a proxy.

We don't know what the support did but we have this problem "cannot prepare internal mirrorlist: no urls in mirror list"

We can't download metadata. 
We cannot follow each step because of work load, and time... and i must install an old app that need php7.4 on a RHEL8.10 OS.

I would to make quickly something or guide the guy to stop to lost time.. We asked for add your repo there 2 weeks 1/2, i have today now before vacancy to install a very important app needed for a migration.

Coud you help us please ?

**Comment by remicollet** [comment]
Le français est acceptable ici

Je n'ai pas assez d'informations sur ce qui a été fait et sur le problème (ex commande passée et sa sortie complète en mode verbeux)

1/ PHP 7.4 est disponible dans les dépôts officiels, 

mon dépôt n'est utile que pour avoir plus de choix de versions et d'extensions

2/ Configuration de mon dépôt

Il faut suivre les instructions de [l'assistant ](https://rpms.remirepo.net/wizard/)

Il faut aussi configurer yum/dnf pour utiliser le cache (il y a plein de doc sur Internet)

Il faut aussi savoir ce qui est autorisé par le cache, et probablement remplacer le `mirrorlist`, par un `baseurl` du miroir qui est autorisé.

**Comment by daerlnaxe** [comment]
Hello,

merci de ta réponse. Bon la personne a planché tard et finalement résolu le problème.

Je n'ai malheureusement pas eu le temps de passer au crible. Beaucoup de choses ne me sont pas accessible avec le choix de ma direction. De mon côté il ya quelques semaines j'avais fait la même manip sur le même os, en vm et je n'avais pas rencontré le moindre problème. Je vais voir du côté de la base url, on avait tenté de notre côté mais avec uniquement les url qu'on avait fait ouvrir car la personne pour ouvrir le proxy nous avait demandé une liste... c'est possible que dans le lot une url n'ait pas été incluse, je vais tout reprendre. Si j'arrive à comprendre ce qui a pu se passer je mettrais le problème + la résolution, au cas où pour d'autres.

Encore merci de ton aide.

Je te souhaite un agréable week end.

**Comment by remicollet** [comment]
> Bon la personne a planché tard et finalement résolu le problème.

Super, donc je ferme ce ticket
