### ISSUE TITLE
php-ioncube-loader package for PHP 8.3, RHEL 7

### ISSUE THREAD

**Issue by andrewg-mira** [remicollet/remirepo#275]
Hello,

I notice that there is not a php-ioncube-loader package for PHP 8.3, RHEL 7 (at eg. http://remi.mirrors.cu.be/enterprise/7/php83/x86_64/) but there is one for PHP 8.2 (eg. http://remi.mirrors.cu.be/enterprise/7/php82/x86_64/php-ioncube-loader-13.0.4-1.el7.remi.8.2.x86_64.rpm).

I am not sure if this is an oversight, or even who it is that creates the package. Please close this issue and let me know if there is someone else I should be reporting to or asking.

Thank you,
 - Andrew

**Comment by remicollet** [comment]
Sorry, but

* EL-7 has reached in End of life in June.
* EPEL-7 is closed
* EL-7 repository is closed.

So you urgently need to upgrade to a supported distribution, EL-8 or EL-9

**Comment by andrewg-mira** [comment]
Thanks for the quick response and info.
