### ISSUE TITLE
php70-php-opcache missing for centos7 x64 after upgrading to php 7.0.1

### ISSUE THREAD

**Issue by iotch** [remicollet/remirepo#28]
Hello.
It seems like opcache extension files are not moved to proper locations after installation - no `opcache.so` and `opcache.ini` found in corresponding folders, but can be located here:
````
/etc/opt/remi/php70/php.d/10-opcache.ini
/etc/opt/remi/php70/php.d/opcache-default.blacklist
/opt/remi/php70/root/usr/lib64/php/modules/opcache.so
````
thanks!

**Comment by remicollet** [comment]
Which rpm version have you used ?
It seems you are confused between php-opcache (base package in remi-php70 and php70-php-opcache (SCL package in remi-safe)

See : http://blog.remirepo.net/pages/English-FAQ#scl
Try : http://rpms.remirepo.net/wizard/

**Comment by iotch** [comment]
I'm using yum and remi-php70 repo.
Yes, it seems like I've installed php70-php-opcache by mistake, but I did it when found out that opcache.so that was there from early php7 betas was missing and tried to fix that.

Can't figure why it was missing as I'm only doing `yum update php\*` from time to time.

**Comment by remicollet** [comment]
So ? solved ?

**Comment by iotch** [comment]
Well, I've installed the correct version manually, and if you believe that opcache extension was not removed during php update from your repo - I apologize for misleading :)
