### ISSUE TITLE
phalcon extension missing for php8.4 / Fedora 41

### ISSUE THREAD

**Issue by pgnd** [remicollet/remirepo#281]
installing a symfony app (sulu/sulu) on Fedora 41 + php 8.4
```
php -v
	PHP 8.4.1 (cli) (built: Nov 20 2024 09:48:35) (NTS gcc x86_64)
	Copyright (c) The PHP Group
	Built by Remi's RPM repository <https://rpms.remirepo.net/> #StandWithUkraine
	Zend Engine v4.4.1, Copyright (c) Zend Technologies
	    with Zend OPcache v8.4.1, Copyright (c), by Zend Technologies
	    with Xdebug v3.4.0, Copyright (c) 2002-2024, by Derick Rethans
```

i bumped into a missing phalcon,

https://github.com/sulu/sulu/issues/7696#issuecomment-2526691937

checking locally
```
dnf search phalcon
	Updating and loading repositories:
	Repositories loaded.
	Matched fields: name, summary
	 php74-php-phalcon5.x86_64: Phalcon Framework
	 php80-php-phalcon5.x86_64: Phalcon Framework
	 php81-php-phalcon5.x86_64: Phalcon Framework
	 php82-php-phalcon5.x86_64: Phalcon Framework
	 php83-php-phalcon5.x86_64: Phalcon Framework
```

i don't see it for php84

here, for php 8.2

https://github.com/remicollet/remirepo/issues/206

i see

	"[ ]  phalcon is not yet compatible (zephir issue)"

and here,

https://github.com/remicollet/remirepo/issues/251

an apparent workaround,

	"phalcon, workaround, reported as [BUG]: broken build [-Wincompatible-pointer-types] phalcon/cphalcon#16531"

is an 8.4 rpm in the works?

EDIT:

fwiw, here on F41
```
dnf install php-pear
rpm -qa php-pear
	php-pear-1.10.16-1.fc41.remi.noarch

pecl channel-update pecl.php.net
	Updating channel "pecl.php.net"
	Update of Channel "pecl.php.net" succeeded

pecl install phalcon
	pecl/phalcon requires PHP (version >= 8.0.0, version <= 8.3.99), installed version is 8.4.1
	No valid packages found
	install failed
```

checking
"[NFR]: PHP 8.4 support #16671"
  https://github.com/phalcon/cphalcon/issues/16671 claims "Blocked by https://github.com/zephir-lang/zephir/issues/2440"

**Comment by remicollet** [comment]
RPM will be available as soon as supported by upstream

**Comment by remicollet** [comment]
Closing as there is nothing I can do
