### ISSUE TITLE
libzip conflict when upgrading from Fedora 22 to 23

### ISSUE THREAD

**Issue by pcaviede** [remicollet/remirepo#29]
Description of problem:
Upon upgrading onlie from Fedora server 22 to 23, the packages download correclly. After the transaction check, the system aborts the upgrade, giving the following error:

Running transaction check
Transaction check succeeded.
Running transaction test
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Transaction check error:
  file /usr/lib/libzip.so.4.0.0 from install of libzip-1.0.1-2.fc23.i686 conflicts with file from package libzip-last-1.0.1-1.fc22.remi.i686

Error Summary
-------------

Version-Release number of selected component (if applicable):
Upgrade from Fedora 22 to 23

How reproducible:

Steps to Reproduce:
1. dnf update
2. dnf install dnf-plugin-system-upgrade
3. dnf system-upgrade download --releasever=23  The latter also tried later with --best and --allowerasing options

Actual results:

See aforementioned error

Expected results:
Upgrade to F23

**Comment by remicollet** [comment]
Should be fixed by 7e2f6268bcdeee8c1d864580068af0c2003933d2  

Please wait for mirrors to be synced with master repository.
And try the upgrade.

**Comment by pcaviede** [comment]
Error message gone! Thanks!


El 14-01-2016 a las 3:09 pm, Remi Collet escribió:
>
> Should be fixed by 7e2f626 
> <https://github.com/remicollet/remirepo/commit/7e2f6268bcdeee8c1d864580068af0c2003933d2> 
>
>
> Please wait for mirrors to be synced with master repository.
> And try the upgrade.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/remicollet/remirepo/issues/29#issuecomment-171725622>.
>

-- 
Dr. Pablo A. Caviedes, M.D., Ph.D.
Program of Molecular & Clinical Pharmacology,
ICBM, Faculty of Medicine, Univ. of Chile
Independencia 1027.
Clasificador Nº 7, Independencia
Santiago, Chile
Phones: (562) 2978-6559 (Voice)
         (562) 2737-2783 (FAX)
Email: pcaviede@med.uchile.cl

**Comment by remicollet** [comment]
:)

**Comment by pcaviede** [comment]
I spoke too soon. It had reported a missing Mysql package. I had to 
rerun the upgrade, and the libzip error popped up again

Ideas?

El 14-01-2016 a las 3:09 pm, Remi Collet escribió:
>
> Should be fixed by 7e2f626 
> <https://github.com/remicollet/remirepo/commit/7e2f6268bcdeee8c1d864580068af0c2003933d2> 
>
>
> Please wait for mirrors to be synced with master repository.
> And try the upgrade.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/remicollet/remirepo/issues/29#issuecomment-171725622>.
>

-- 
Dr. Pablo A. Caviedes, M.D., Ph.D.
Program of Molecular & Clinical Pharmacology,
ICBM, Faculty of Medicine, Univ. of Chile
Independencia 1027.
Clasificador Nº 7, Independencia
Santiago, Chile
Phones: (562) 2978-6559 (Voice)
         (562) 2737-2783 (FAX)
Email: pcaviede@med.uchile.cl

**Comment by remicollet** [comment]
Sorry, no idea, excepted an outdated repo... but all mirror seem in sync with master;

**Comment by pcaviede** [comment]
Aparently it needed a final sync. I refreshed the repos, tried the 
upgrade and.... No conflicts! System is working fine, now with F23

Thanks for your help.... yet again!


El 15-01-2016 a las 12:07 pm, Remi Collet escribió:
>
> Sorry, no idea, excepted an outdated repo... but all mirror seem in 
> sync with master;
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/remicollet/remirepo/issues/29#issuecomment-171986158>.
>

-- 
Dr. Pablo A. Caviedes, M.D., Ph.D.
Program of Molecular & Clinical Pharmacology,
ICBM, Faculty of Medicine, Univ. of Chile
Independencia 1027.
Clasificador Nº 7, Independencia
Santiago, Chile
Phones: (562) 2978-6559 (Voice)
         (562) 2737-2783 (FAX)
Email: pcaviede@med.uchile.cl

**Comment by remicollet** [comment]
Thanks for confirming the fix.
