### ISSUE TITLE
redis-shutdown does not work if the server has a password

### ISSUE THREAD

**Issue by ThiefMaster** [remicollet/remirepo#31]

**Comment by remicollet** [comment]
Interesting catch.
Will try to find a solution with Fedora maintainer (package in my repo is only a backport)

A way could be to fall-back on a simple Kill, but this could raise some corruption issues (the reason why this script was added)...

Need more time to investigate

**Comment by ThiefMaster** [comment]
ah, i thought the one in the CentOS7 EPEL repo was taken from your repo.

one option could be grepping the password from the config file just like it's done with the port

**Comment by remicollet** [comment]
> ah, i thought the one in the CentOS7 EPEL repo was taken from your repo.

Well.. we collaborate ;)
And some change have happens in "remi" before being merged in EPEL.

Can you please try to change the redis-shudown script with

     PASS=`awk '/^[[:blank:]]*requirepass/ { print $2 }' $CONFIG_FILE`
     
     # shutdown the service properly
     if [ -n "$PASS" ]; then
       $REDIS_CLI -h $HOST -p $PORT -a $PASS shutdown
     else
       $REDIS_CLI -h $HOST -p $PORT shutdown
     fi

**Comment by hguemar** [comment]
@ThiefMaster thank you for reporting this issue, Fedora package has been fixed. I'll fix EPEL packages after some more testing.
And yeah, we work together with @remicollet on packages :+1: 

I slightly changed Remi's patch so it'd be easier to add more parameters in the future.
http://pkgs.fedoraproject.org/cgit/rpms/redis.git/commit/?id=ffd00fb400e2cb90a1a5e86dc93ef8091bda26d5

**Comment by ThiefMaster** [comment]
Ah thanks, didn't have time to test it yet (not using anything RPM-based at home)

**Comment by remicollet** [comment]
Thanks @ThiefMaster and @hguemar
