### ISSUE TITLE
pdo_ibm extension won't load.

### ISSUE THREAD

**Issue by vbsessa** [remicollet/remirepo#34]
Hi,
I've compiled pdo_ibm extension by myself, loaded it, but i've got the following message:

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/pdo_ibm.so' - /usr/lib64/php/modules/pdo_ibm.so: undefined symbol: Z_STRVAL_PP in Unknown on line 0
```

**Comment by vbsessa** [comment]
There is a pull request that fix this issue, but has not been marged yet.
[https://github.com/php/pecl-database-pdo_ibm/pull/1]()

**Comment by remicollet** [comment]
Closing as this is not a bug with package available in my repository.
