### ISSUE TITLE
php-pecl-oci8 dependency issue

### ISSUE THREAD

**Issue by odoucet** [remicollet/remirepo#36]
Installing php-pecl-oci8 leads to following error : 

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/oci8.so' - libclntsh.so.12.1: cannot o            pen shared object file: No such file or directory in Unknown on line 0
```

```
$ ldd /usr/lib64/php/modules/oci8.so
        linux-vdso.so.1 =>  (0x00007ffc6ea69000)
        libclntsh.so.12.1 => not found
        libc.so.6 => /lib64/libc.so.6 (0x00007fa3bfaff000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fa3c00f8000)
```

The missing lib is provided by Oracle at http://www.oracle.com/technetwork/topics/linuxx86-64soft-092277.html
(instantClient basic)

But is installed in a not-obvious place (/usr/lib/oracle/12.1/client64/lib).

I do not know the best way to fix this issue. I think this package should fail if the dependency is not solved, but this would require a manual copy of libs from oracle.
At minimum, a warning after package installation would be great.

**Comment by remicollet** [comment]
Usually, RPM have dependency on the needed libraries (auto-detected by build process).

For this one, this is not possible.
* the RPM from Oracle doesn't have the "provide"
* the library can be found in other place (according to installed packages, Instant Client, Server...)
* Oracle can be installed manually (which seems a better solution as their RPM are... very strange)

The auto-dependencies have been disable on purpose

So, to make this extension usable, you have to install the library and make it available in the linker path
* adding its path in a /etc/ld.so.conf.d file
* setting LD_LIBRARY_PATH
