### ISSUE TITLE
RPM provides from PHP5 to PHP7

### ISSUE THREAD

**Issue by daniel-lucio** [remicollet/remirepo#42]
When updating from PHP5.x to 7 the following packages have some upgrade issues:

pdo-dblib shuld provide php-mssql
php-mysqlnd should provide php-mysql

this will make the upgrading process easier

**Comment by remicollet** [comment]
> pdo-dblib shuld provide php-mssql

No, the "mssql" extension is not provided, so if you really need it, you cannot update to 7.x

> php-mysqlnd should provide php-mysql

No, the mysql extension is no more provided (but provided by php-pecl-mysql)
