### ISSUE TITLE
Update igbinary7

### ISSUE THREAD

**Issue by ct16k** [remicollet/remirepo#43]
Hello,

Would it be possible to update the php7 igbinary package from https://github.com/igbinary/igbinary7/commit/2b7c703f0b2ad30b15cd0d85bc6b9e40e7603b13 to at least https://github.com/igbinary/igbinary7/commit/a75a435c788d5f30275a218ad733a63d8945c4a8 ? This commit fixes several serialization/unserialization issues that make the extension usable again with the memcached plugin on php7 (https://github.com/igbinary/igbinary7/pull/13).

Thank you!

**Comment by mihai-stancu** [comment]
+1

**Comment by remicollet** [comment]
I will take care of this update ASAP (probably later today)

**Comment by remicollet** [comment]
Fixed by a8b1f5256d858a01a2eccfdf9dacbc6be99ff2ba

Will be in the repo after mirror sync (already uploaded on primary server)
