### ISSUE TITLE
Request for php-sqlsrv package inclusion

### ISSUE THREAD

**Issue by sirio3mil** [remicollet/remirepo#44]
Hi

Thanks this repo. Now that Microsoft is opening its tools to Linux, would it be possible to provide [php-sqlsrv](https://github.com/Azure/msphpsql/tree/PHP-7.0-Linux) as well? That would be awesome cuz their compilation [not work properly with this repo](https://github.com/Azure/msphpsql/issues/115).

Regards

**Comment by remicollet** [comment]
Indeed it will be interesting to provide this extension (especially as php doesn't provide "mssql" ext anymore).

BTW all build tools (confi.m4) are missing in this repository, and using binaries is not a clean way.

**Comment by sirio3mil** [comment]
I couldn't agree more with you. About m4 file there is [already a pending request](https://github.com/Azure/msphpsql/issues/58#issuecomment-229915311).

**Comment by remicollet** [comment]
**msodbcsql** and **php-sqlsrv** are now available in the repository.

* only for PHP 7
* only for x86_64
* only for Fedora and EL 7

They rely on system unixODBC which seems to suite the need.

Any test or feedback is welcome (I don't have any SQL server to test them)

**Comment by remicollet** [comment]
At least I was able to:

```
$ php -r 'var_dump(sqlsrv_connect("foo"', ["UID"=>"foo","PWD"=>"bar"]));'
ressource(4) of type (SQL Server Connection)
```

**Comment by sirio3mil** [comment]
Hi, @remicollet , so fast! I will try to test it this weekend, Regards!

**Comment by sirio3mil** [comment]
Hi @remicollet, it works fine, you can close this request.

Regards
