### ISSUE TITLE
mssqlodbc (remi) not found

### ISSUE THREAD

**Issue by josevieirame** [remicollet/remirepo#47]
I'm following this "guide" and I had a problem with that package: `mssqlodbc`

[http://blog.remirepo.net/post/2016/09/20/Microsoft-SQL-Server-from-PHP#sec5](http://blog.remirepo.net/post/2016/09/20/Microsoft-SQL-Server-from-PHP#sec5)

Thanks!

**Comment by remicollet** [comment]
Distro ? Version ? Arch ?

Ex: http://rpms.remirepo.net/enterprise/7/safe/x86_64/repoview/msodbcsql.html

Notice: 
* only for Fedora and EL-7 
* only for x86_64

**Comment by josevieirame** [comment]
Centos7, I did some tests and it works correctly .

Thanks!

**Comment by remicollet** [comment]
:)
