### ISSUE TITLE
Tarantool-PHP for version 7.0

### ISSUE THREAD

**Issue by bigbes** [remicollet/remirepo#51]
Hello, Remi.

It's great that you have repository with so many php modules and, in particular, php-tarantool (thank you very much for that).
I had question about php7 version of 'php-tarantool' extension - we have php7 version driver on branch php7-v2.

How can I help you to package php7 version of this driver?

**Comment by remicollet** [comment]
I will have a look after new PHP versions build.

BTW I will prefer to have a tagged version (instead of a git snapshot)

**Comment by remicollet** [comment]
Should be fixed by https://git.io/vPUDz

Feedback welcome.

**Comment by bigbes** [comment]
Sorry for long waiting. I'll have a look tomorrow.
Thank you very much!

**Comment by bigbes** [comment]
And about tagged version - I'll provide it tomorrow.

**Comment by bigbes** [comment]
Hello, @remicollet . Sorry for long response. I make PR(https://github.com/remicollet/remirepo/pull/54), but I don't know simple way of testing package building and packages..

**Comment by remicollet** [comment]
version 0.2.0 now available in the repo
