### ISSUE TITLE
compat-php5 ? 

### ISSUE THREAD

**Issue by sergiomb2** [remicollet/remirepo#52]
I need it for maniadrive package , seems to me is the best solution and now I read a second request:  
https://ask.fedoraproject.org/en/question/95078/downgrade-php-7x-to-5x/

We should consider add compat-php5  in F25 , what do you think ?

**Comment by remicollet** [comment]
> We should consider add compat-php5 in F25 , what do you think ? 

This is a solution I don't want to work on.

All the work is ready in my repo using software collections, PHP version from 5.4 to 7.1 are available.

But, Fedora still don't want them.

Closing this bug, as this is not related to my repository.
