### ISSUE TITLE
php-pecl-pthreads 3.1.7 segfaults at PHP 7.1.0

### ISSUE THREAD

**Issue by dterweij** [remicollet/remirepo#55]
pthreads 3.1.6 is  working at PHP 7.0.x
pthreads 3.1.7 is not working at PHP 7.0.x (Segfaults)

You might want to downgrade 3.1.7 at PHP 7.1.0 to 3.1.6 ?

3.1.7 is not advertised at PHP PECL PTHREADS website.

**Comment by remicollet** [comment]
Version for PHP 7.0 is indeed 3.1.6.

3.1.7-dev is only in the repo for PHP 7.1 (as 3.1.6 is not compatible)

Please rpm -qa php\*

**Comment by remicollet** [comment]
>  pthreads 3.1.7 is not working at PHP 7.0.x (Segfaults)

Above sentence is confusing ;)

BTW, the snapshot is quite old (May), so I refresh the version with something more recent.
Please try it.

If it still segfaults, please file an [upstream bug](https://github.com/krakjoe/pthreads/issues), and paste link here.

**Comment by remicollet** [comment]
Updated to php-pecl-pthreads-3.1.7-0.4.20161111git959ab0f in 921446d6a72cd3a24a3b6e32ee9022bb64c4429b

**Comment by dterweij** [comment]
Thanx, i wait till the new package is there and come back with findings :)

**Comment by dterweij** [comment]
Still a segfault. Downgraded to PHP 7.0. Will try again after setting up a vps to play with it.

**Comment by dterweij** [comment]
I dont think the 3.1.7 is ready to be in your repository Remi. It just don't work in PHP 7.1.
Up to you :)  I am not a troubleshooter. Just a user :)

**Comment by dterweij** [comment]
Update: Pthreads 3.17dev + PHP 7.2.0RC3 is working. Now i can go back playing after a freeze of 8 months :) Issue can be closed if needed. Thanks.
