### ISSUE TITLE
PHP 7.1  might need new openssl version

### ISSUE THREAD

**Issue by dterweij** [remicollet/remirepo#56]
Next problem I found with PHP 7.1 is that it gives problems with openssl. (There are things changed with openssl parameters if I am right in PHP 7.1)

Current: openssl-1.0.1e-48.el6_8.3.x86_64

Possible that PHP 7.1 needs openssl 1.0.2 as the same PHP application on a ubuntu system is working fine with openssl 1.0.2 

Request:  newer openssl if possible, but i dont think it is a remi package right?

**Comment by remicollet** [comment]
Indeed, my package rely on system openssl, not maintained by me.

BTW openssl is one of critical package I prefer to not change (even if I will probably need in the future to provide version 1.1.0 if possible)

Please explain encountered problem (at least upstream test suite fully passes without any issue).

**Comment by remicollet** [comment]
no feedback
