### ISSUE TITLE
Add php-pinba package to repo

### ISSUE THREAD

**Issue by simonsunx** [remicollet/remirepo#62]
Is it possible to  add php-pinba extension in ready-to-use state into remi repository?

**Comment by remicollet** [comment]
I usually prefer (and givbe priority on extensions available on PECL), so https://github.com/tony2001/pinba_extension/issues/31

Doesn't see any blocker (in dependencies), will try to work on it.

**Comment by remicollet** [comment]
Also https://github.com/tony2001/pinba_extension/issues/32

**Comment by remicollet** [comment]
Package is now available in the repository (php 7.0 and 7.1)

Feedback welcome.

**Comment by simonsunx** [comment]
Remi, thanks.

We've got pinba.so by compiling https://github.com/tony2001/pinba_extension in branch php5 on the one of the nodes. Then we spread pinba.so and pinba.ini via puppet, using file-resource.

Installation in 7.x seems to be much easier. Migration just planned.

**Comment by remicollet** [comment]
I have open https://github.com/tony2001/pinba_extension/issues/33
If the branch is confirmed as maintainedby upstream, I will add the build for it.
