### ISSUE TITLE
pinba_engine to MySQL.

### ISSUE THREAD

**Issue by billionaire** [remicollet/remirepo#63]
Hi.
You recently added new extension php-pinba #62. It is very convenient.
Could you add to MySQL plugin pinba_engine http://pinba.org/ ?
Thank you.

**Comment by remicollet** [comment]
Sorry, but my repository is now PHP dedicated, and so I avoid as much as possible everything which is out of my skills.

And BTW, MySQL is dead everybody use MariaDB nowadays ;)
