### ISSUE TITLE
php-pecl-sphinx for PHP 7+

### ISSUE THREAD

**Issue by remicollet** [remicollet/remirepo#64]
From IRC:
```
15:55:10 - david__ : hi can you build php71-php-pecl-sphinx package please?
16:15:16 - RemiFedora : david__: would you agree to test a "test" package ?
16:16:13 - david__ : yes I can test it

```

**Comment by remicollet** [comment]
No release publish for now, but git seems mostly ready.

**Comment by remicollet** [comment]
Updated in 41c7aa9b31ad5da4f48cfcfee59255f0f4d382b0

**php-pecl-sphinx-1.4.0-0.1.20160323git9a3d08c** available in the testing repo.
Feedback welcome.

**Comment by remicollet** [comment]
Replace with  **php-pecl-sphinx-1.4.0-0.2.20170203git201eb00** for both i386 and x86_64
With http://git.php.net/?p=pecl/search_engine/sphinx.git;a=commit;h=201eb00bd370bf8ff2d5787ac1a1b588f14af5a0

**Comment by daewo** [comment]
it is working.
no problems found.

**Comment by remicollet** [comment]
thanks for the feedback

**Comment by yatsukhnenko** [comment]
@remicollet is it possible to apply [this](https://github.com/php/pecl-search_engine-sphinx/pull/3) fix in your build?

**Comment by remicollet** [comment]
@yatsukhnenko package updated to 1.4.0-0.6.**20181116**.d958afb

Should be shortly available in all mirrors.

**Comment by yatsukhnenko** [comment]
@remicollet thank you!
