### ISSUE TITLE
librdkafka spec missing lz4 dependency

### ISSUE THREAD

**Issue by edenhill** [remicollet/remirepo#65]
liblz4-devel should probably be a BuildRequires

**Comment by remicollet** [comment]
Indeed, good catch.

Enabled in 0.9.4-0.2.RC1 ( in remi-test), will be in stable with 0.9.4 (probably coming soon, else I will rebuild 0.9.3 with this option)

**Comment by remicollet** [comment]
Also reported to fedora package as [bug #1423367](https://bugzilla.redhat.com/show_bug.cgi?id=1423367)

**Comment by remicollet** [comment]
Closing (as this option is new in 0.9.4)
