### ISSUE TITLE
Redis libexec script

### ISSUE THREAD

**Issue by archonik** [remicollet/remirepo#67]
Hello in you redis-rpm you have a really nasty bug in libexec script.

Consider the following scenario, you have redis listening only on unix socket but not on any port or interface.

The error from systemd was redis.service stopping timed out. Terminating. because it was trying to stop a redis on 127.0.0.1 and port 0 obviously, because redis was not running on port.

So i fixed the redis-shutdown wrapper, it now uses socket, if there is one, and behaves normally when there isnt one.

```bash
#!/bin/bash
#
# Wrapper to close properly redis and sentinel
test x"$REDIS_DEBUG" != x && set -x

REDIS_CLI=/usr/bin/redis-cli

# Retrieve service name
SERVICE_NAME="$1"
if [ -z "$SERVICE_NAME" ]; then
   SERVICE_NAME=redis
fi

# Get the proper config file based on service name
CONFIG_FILE="/etc/$SERVICE_NAME.conf"

# Use awk to retrieve host, port from config file
HOST=`awk '/^[[:blank:]]*bind/ { print $2 }' $CONFIG_FILE | tail -n1`
PORT=`awk '/^[[:blank:]]*port/ { print $2 }' $CONFIG_FILE | tail -n1`
PASS=`awk '/^[[:blank:]]*requirepass/ { print $2 }' $CONFIG_FILE | tail -n1`
SOCK=`awk '/^[[:blank:]]*unixsocket\s/ { print $2 }' $CONFIG_FILE | tail -n1`

# Just in case, use default host, port
HOST=${HOST:-127.0.0.1}
if [ "$SERVICE_NAME" = redis ]; then
    PORT=${PORT:-6379}
else
    PORT=${PORT:-26739}
fi

# Setup additional parameters
# e.g password-protected redis instances
[ -z "$PASS"  ] || ADDITIONAL_PARAMS="-a $PASS"

# shutdown the service properly
if [ -e "$SOCK" ] ; then
	$REDIS_CLI -s $SOCK $ADDITIONAL_PARAMS shutdown
else 
	$REDIS_CLI -h $HOST -p $PORT $ADDITIONAL_PARAMS shutdown
fi
```

**Comment by remicollet** [comment]
Hi,

Thanks for this report, 
BTW, this package is mostly a backport of the Fedora package, so I try to keep it in sync (pushing my changes there, and pulling other changes).

Can you please open a bug on http://bugzilla.redhat.com/ ?

**Comment by archonik** [comment]
Sure

https://bugzilla.redhat.com/show_bug.cgi?id=1444988

**Comment by remicollet** [comment]
Thanks

**Comment by remicollet** [comment]
This is part of redis 4.0.0 update.
See issue #74
