### ISSUE TITLE
php core function getimagesize on zip-stream yields 500-error

### ISSUE THREAD

**Issue by edreg** [remicollet/remirepo#68]
Hello,

I tried different PHP-versions:

PHP 5.6.30 (cli) (built: Jan 19 2017 07:08:58) ; Copyright (c) 1997-2016 The PHP Group; Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies 
PHP 7.1.4 (cli) (built: Apr 11 2017 18:26:18) ( NTS ); Copyright (c) 1997-2017 The PHP Group; Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies 
PHP 7.0.18 (cli) (built: Apr 11 2017 13:29:03) ( NTS ); Copyright (c) 1997-2017 The PHP Group; Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies 

a code snippet like: 
`getimagesize('zip:///path/to/archive/archive.xlsx#xl/media/image1.jpg');`
gets me the "internal server error" with following log entires:
[Fri Apr 28 10:10:25.702289 2017] [fcgid:warn] [pid 8536] (104)Connection reset by peer: [client xxx.xxx.xxx.xxx:yyyyy] mod_fcgid: error reading data from FastCGI server
[Fri Apr 28 10:10:25.702367 2017] [core:error] [pid 8536] [client xxx.xxx.xxx.xxx:yyyyy] End of script output before headers: test.php

The zip-streaming is no issue:
`fopen('zip:///path/to/archive/archive.xlsx#xl/media/image1.jpg', 'r');` 
is working as expected.

Do you need any further information?

Kind regards,
gerald

**Comment by remicollet** [comment]
Indeed, I can reproduce

**Comment by remicollet** [comment]
Fixed in zip extension v 1.15.1 
https://github.com/pierrejoye/php_zip/commit/65e236ae63381c5d8fda35c620d7048313928d50

Will release this new version soon, and push it to the repo.

**Comment by remicollet** [comment]
Released (upstream) and pushed in the repository.

Thanks for the report (despite this is a upstream bug which can have been reported on https://bugs.php.net/) and really sorry for the long delay before I find some spare time to work in it.

**Comment by remicollet** [comment]
No feedback :(
