### ISSUE TITLE
Possible to provide latest sphinx-2.2.11-1.rhel7.x86_64 upgrade?

### ISSUE THREAD

**Issue by yasithab** [remicollet/remirepo#69]
Current available version in remi's repo: sphinx-2.1.5-2.el7.remi.x86_64
Latest stable version: sphinx-2.2.11-1.rhel7.x86_64 (Reference: http://sphinxsearch.com/downloads/release/)

Is it possible to upgrade remi's version to the latest?

**Comment by Nyoroon** [comment]
Hello! Any progress?

**Comment by remicollet** [comment]
Sorry, but really not enough free time to work on this
