### ISSUE TITLE
php-sqlsrv latest preview

### ISSUE THREAD

**Issue by sirio3mil** [remicollet/remirepo#70]
Hi,

I can't find latest 4.1.9 or 4.2.0 packages using yum but I see it in [your official repo](https://git.remirepo.net/cgit/rpms/php/php-sqlsrv.git/ )

Have I to use another repo?

Regards

**Comment by remicollet** [comment]
Latest versions 4.1.x, 4.2.x versions are "preview", so 
- 4.0.8 "stable" is in stable repository
- 4.2.0 "devel" is in testing repository (remi-test for SCL, remi-php70-testn remi-php71-test)

See state on [pecl](https://pecl.php.net/package/sqlsrv) and [extensions list](https://blog.remirepo.net/pages/PECL-extensions-RPM-status)

**Comment by sirio3mil** [comment]
Thanks, but wich is URL's rpm for the testing repository? 

I'm using this to add to yum, but I can find this repos there.

wget http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
rpm -Uvh remi-release-7*.rpm

Regards

**Comment by remicollet** [comment]
You have it, you juste need to enable the testing repo.

> (remi-test for SCL, remi-php70-test, remi-php71-test for base packages)

**Comment by remicollet** [comment]
Also explained by the [Wizard](http://rpms.remirepo.net/wizard/)
