### ISSUE TITLE
Please provide uWSGI-plugins for PHP versions

### ISSUE THREAD

**Issue by aofwer** [remicollet/remirepo#71]
Hi,

as outlined on the [forum](https://forum.remirepo.net/viewtopic.php?id=3593) it would be nice if updated `uwsgi-plugin-php`-versions could be provided in the remi repository.

Since each PHP version needs it's own uWSGI plugin the plugin version shipped with the distribution does not work with the PHP versions from the remi repository.

**Comment by remicollet** [comment]
From a quick look and build test, should be doable

For single version (base package)
* **uwsgi-plugin-php56** in "remi-php56'
* **uwsgi-plugin-php70** in "remi-php70'
* ...

Which will conflict with  uwsgi-plugin-php in base repository (as php-embedded needed, and only 1 version can be installed)

For multiple version (SCL packages)
* **php56-uwsgi-plugin-php** in "remi-safe"
* **php70-uwsgi-plugin-php** in "remi-safe"
* ...

No conflicts needed (but I can't say if various versions can work together, at least can be installed)

Main issue, will have to follow Fedora/EPEL package for synced update


@aofwer would you agree to test the packages ?

**Comment by remicollet** [comment]
Simpler:

For single version (base package)
*    uwsgi-plugin-php in "remi-php56'
*    uwsgi-plugin-php in "remi-php70'
*    ...

With release including version, as for php modules

**Comment by remicollet** [comment]
Fixed in https://git.remirepo.net/cgit/rpms/uwsgi/uwsgi-plugin-php.git/commit/?id=8ad0a75cf2129764eeb1b195601912077ecf119b

So package now available for 
- Fedora 24-26
- CentOS / RHEL 6-7
- All PHP versions
- base and SCL packages

Feedback very welcome

**Comment by aofwer** [comment]
Wow, this was lightning-fast. This is awesome, I'll try next week and report back.

**Comment by aofwer** [comment]
I just tested this in my uWSGI environment (EL7) and it is working! Thank you so much. I hope that this allows more people to start playing around with uWSGI as it such a cool and advanced application server.

**Comment by remicollet** [comment]
Thanks for the feedback
