### ISSUE TITLE
php-pecl-redis 3.1.3 Segfaults on PHP 5.4

### ISSUE THREAD

**Issue by jmfontaine** [remicollet/remirepo#75]
After upgrading to version 3.1.3 of php-pecl-redis on PHP 5.4, we got segfaults. Downgrading to version 3.1.2 fixed the segfaults.

I don't see any related [known upstream bug](https://github.com/phpredis/phpredis/issues?q=is%3Aissue+segfault+is%3Aopen) so I guess I should report the bug here first.

Package info:

```
Name        : php54-php-pecl-redis
Arch        : x86_64
Version     : 3.1.3
Release     : 1.el6.remi
```

PHP Info:

```
PHP 5.4.45 (cli) (built: Feb 18 2017 15:55:26)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
```

CentOS Info: `CentOS release 6.9 (Final)`

Kernel Info: `2.6.32-573.3.1.el6.x86_64`

Redis Info: `2.8.19` (AWS Elasticache)

Upstream Bug Report: https://github.com/phpredis/phpredis/issues/1210

**Comment by remicollet** [comment]
Please report this upstream (and paste link to upstream bug here).

Also reported on IRC...

I won't be able to investigate on it before August (Holidays !)
A backtrace will be useful.

**Comment by remicollet** [comment]
v3.1.3 removed from remi (stable) repository (kept in testing)

**Comment by jmfontaine** [comment]
@remicollet Do you have instructions on how provide a useful backtrace? Thanks!

**Comment by remicollet** [comment]
See https://bugs.php.net/bugs-generating-backtrace.php
(and you need the debuginfo packages)

**Comment by mattias** [comment]
This issue seems to happen on php 7.0 as well. See my comments at the bottom of this issue:
https://github.com/magento/magento2/issues/9875

**Comment by remicollet** [comment]
Version 3.1.4RC1 is available in the **testing** repository (php 5.6 to 7.2 as base package, php 5.4 to 7.2 as SCL packages)

**Comment by remicollet** [comment]
Version **3.1.4RC3** is available in the **testing** repository (php 5.6 to 7.2 as base package, php 5.4 to 7.2 as SCL packages)

**Comment by remicollet** [comment]
Version 3.1.4 is available in the testing repository (no change since RC3)

See https://github.com/remicollet/remirepo/issues/84

**Comment by remicollet** [comment]
No feedback :(
pushing to stable
