### ISSUE TITLE
bzip2 module request

### ISSUE THREAD

**Issue by zamolxe** [remicollet/remirepo#78]
Hey, 
Is it possible to include the bz2/bzip2 support in the repo ? 

Update: Request is for 7.0 repo, higher release are also apreciated

Best regards,
Alex R.

**Comment by remicollet** [comment]
bz2 extension is there since.... always

```
$ php -i 
...
bz2

BZip2 Support => Enabled
Stream Wrapper support => compress.bzip2://
Stream Filter support => bzip2.decompress, bzip2.compress
BZip2 Version => 1.0.6, 6-Sept-2010
...
```

**Comment by zamolxe** [comment]
It was an issue on my end, sorry for the inconvenience.
