### ISSUE TITLE
like mock-rpmfusion-free have we on mock-remi package ? 

### ISSUE THREAD

**Issue by sergiomb2** [remicollet/remirepo#79]
Hi,
I'd like go back to maniadrive which needs php56 and I'd test the build with mock , for that I need a remi mock configuration , also could be interesting use it with or in copr (I don't know how it works) anyway, also could help something take a look at https://github.com/rpmfusion-infra/mock-rpmfusion

Thanks,

**Comment by remicollet** [comment]
> for that I need a remi mock configuration 

Simply duplicate the mock provided configuration for your distribution and add the "remi" configuration in it.

It make sense for rpmfusion, which have a lot of contributors to maintain such a package, but, not for me.

So I don't plan to provide such package.

**Comment by sergiomb2** [comment]
Hum , add if we add these mock configurations to https://github.com/rpmfusion-infra/mock-rpmfusion ?  
we already have mock-kwizart.spec , so add mock-remi.spec shouldn't be a problem ...   
one pull request is very welcome , I may try do it this weekend if no PR appears 😃

**Comment by remicollet** [comment]
Closing as I don't plan to add this package here
