### ISSUE TITLE
couchbase: inconsistent headers/runtime version

### ISSUE THREAD

**Issue by avsej** [remicollet/remirepo#81]
When I install couchbase extension, it reports different library versions in phpinfo();

```
yum install -y https://rpms.remirepo.net/enterprise/remi-release-7.rpm
yum-config-manager –enable remi-php56
yum install -y httpd php php-pecl-couchbase2
```

```
# php -i  | grep -A8 '^couchbase$'
couchbase

couchbase support => enabled
extension version => 2.3.4
libcouchbase runtime version => 2.8.0 (git: 2f655ce41412e8c55b768723f6141e4e7e9cb847)
libcouchbase headers version => 2.7.6 (git: e15b267765913f110fd1bbf65749c54b56875ebf)
igbinary transcoder => enabled
zlib compressor => enabled
```

Usually I expect the runtime and headers to match on new system, they might be different when the libcouchbase updated, while keeping extension version.

**Comment by avsej** [comment]
Compare to what tools report:

```
# yum install libcouchbase-tools
#  cbc version
cbc:
  Runtime: Version=2.8.0, Changeset=2f655ce41412e8c55b768723f6141e4e7e9cb847
  Headers: Version=2.8.0, Changeset=2f655ce41412e8c55b768723f6141e4e7e9cb847
  IO: Default=libevent, Current=libevent, Accessible=libevent,libev,select
  SSL Runtime: OpenSSL 1.0.1e-fips 11 Feb 2013
  SSL Headers: OpenSSL 1.0.1e-fips 11 Feb 2013
```

**Comment by avsej** [comment]
"safe" packages are not affected. It is only for `php-pecl-couchbase2`

**Comment by remicollet** [comment]
* All pecl/couchbase **2.3.4** package were built against current libcouchbase **2.7.6**.
* libcouchbase have been update to 2.7.7 and 2.8.0 later
* All pecl/couchbase **2.4.0** packages were built against current libcouchbase **2.8.0**.

So this inconsistency only exists with PHP 5.4 and 5.5 packages (as 2.4.0 now requires PHP 5.6+)

BTW, from ABI/API check:
* http://rpms.remirepo.net/compat_reports/libcouchbase/2.7.7_to_2.8.0/compat_report.html

The ABI is compatible, so this should not raise any issue (and if not compatible upstream should have raise the soname).

**Comment by remicollet** [comment]
Additional notice, as upstream doesn't manage symbol versioning, the package have a dependency on the build version, ex:

```
$ rpm -qp --requires enterprise/7/php56/x86_64/php-pecl-couchbase2-2.4.0-1.el7.remi.5.6.x86_64.rpm
libcouchbase(x86-64) >= 2.8.0
libcouchbase.so.2()(64bit)
```

**Comment by avsej** [comment]
Thank you for comments.

**Comment by remicollet** [comment]
Additional comment about this.

In fact this is not an inconsistency, as far as the ABI is compatible ;)

BTW, with update of libcouchbase to 2.8.1, abi-compliance-checker detect some incompatibility
=> https://rpms.remirepo.net/compat_reports/libcouchbase/2.8.0_to_2.8.1/compat_report.html

Which seems so bad :(
(perhaps the altered struct should not be used by client, but in this case should not be in the public header, but in some private one, obscure struct are perfect for such needs)

To be sure the php extension won't explode at runtime, I choose to rebuild everything against 2.8.1

```
libcouchbase runtime version => 2.8.1 (git: 5a66d8607605bb23e66ed7ae9e7196fe45be6856)
libcouchbase headers version => 2.8.1 (git: 5a66d8607605bb23e66ed7ae9e7196fe45be6856)
```

And I pray it will not happen too often ;)
