### ISSUE TITLE
php70-php-devel contains no phpize

### ISSUE THREAD

**Issue by gouchaoer** [remicollet/remirepo#82]
```
[gouchaoer@localhost swoole-src-2.0.9]$ sudo yum --enablerepo=remi install php70-php-devel
[sudo] gouchaoer 的密码：
已加载插件：fastestmirror, langpacks
remi                                                     | 2.9 kB     00:00     
remi/primary_db                                            | 1.9 MB   00:06     
Loading mirror speeds from cached hostfile
 * base: mirrors.aliyun.com
 * epel: mirrors.tongji.edu.cn
 * extras: mirrors.aliyun.com
 * remi: mirror.innosol.asia
 * remi-safe: mirror.innosol.asia
 * updates: mirrors.aliyun.com
软件包 php70-php-devel-7.0.23-1.el7.remi.x86_64 已安装并且是最新版本
无须任何处理
[gouchaoer@localhost swoole-src-2.0.9]$ phpize
bash: phpize: 未找到命令...

```

**Comment by remicollet** [comment]
Of course it is there, but I think you are confuse by SCL usage.

Read: https://blog.remirepo.net/pages/English-FAQ#scl
Also https://blog.remirepo.net/post/2016/04/16/My-PHP-Workstation

```
$ scl enable php70 phpize
Configuring for:
PHP Api Version:         20151012
Zend Module Api No:      20151012
Zend Extension Api No:   320151012
```
> [gouchaoer@localhost swoole-src-2.0.9]$ phpize

BTW, if you need swoole, extension, probably much more simpler to install tha available RPM.
`yum install php70-php-pecl-swoole2
`
See the available extension list: https://blog.remirepo.net/pages/PECL-extensions-RPM-status

**Comment by gouchaoer** [comment]
i got it. thx.
as php70 is installed as multi version, i need to use  /opt/remi/balabala/phpize to do it.
