### ISSUE TITLE
php71-php-imap graceful crash on EL7

### ISSUE THREAD

**Issue by spiderr** [remicollet/remirepo#83]
On RHEL 7 (.3 or .4) the php71-php-imap package causes the following error.

I tried many ways to debug this, and the simple answer is loading the imap module seg faults apache graceful. I confirmed this on php 7.1.7 and 7.1.9 on EL7.3 and EL7.4

[Sun Sep 24 14:46:03.618545 2017] [mpm_prefork:notice] [pid 13215] AH00171: Graceful restart requested, doing restart
[Sun Sep 24 14:46:03.689546 2017] [auth_digest:notice] [pid 13215] AH01757: generating secret for digest authentication ...
[Sun Sep 24 14:46:03.696509 2017] [ssl:warn] [pid 13215] AH02292: Init: Name-based SSL virtual hosts only work for clients with TLS server name indication support (RFC 4366)
[Sun Sep 24 14:46:03.721323 2017] [core:notice] [pid 13215] AH00060: seg fault or similar nasty error detected in the parent process

PS I am long time fan, first time to caller ;-) Your work on PHP is fantastic!

**Comment by remicollet** [comment]
Are you able to provide any small reproducer ?
Or a backtrace ?

**Comment by spiderr** [comment]
Hi Remi,

I will look into getting CoreDumpDirectory wired up and a backtrace for you. Here is the simple steps:

1. Base RHEL 7.4 install + distro httpd (httpd-2.4.6-67.el7_4.2.x86_64)
2. Add remi .repo and enable php71, aka http://rpms.remirepo.net/enterprise/7/php71/x86_64/
3. yum install php71-runtime php71-php-pear php71-php-devel php71-php-intl php71-php-pdo php71-php-mcrypt php71-php-ldap php71-php-json php71-php-oci8 php71-php-pspell php71-php-process php71-php-pecl-zip php71-php-common php71-php-mysqlnd php71-php-fpm php71-php-mbstring php71-php-cli php71-php-xml php71-php php71-php-gd
4. systemctl start httpd (life is good in error_log)
5. apachectl graceful (life is good in error_log)
6. yum install php71-php-imap-7.1.7-1.el7.remi.x86_64 
7. apachectl graceful (segfault in error_log)

**Comment by remicollet** [comment]
Just tried on a fresh CEntOS 7.4 install, and saddly, cannot reproduce, no segfault... (php 7.1.10, freshly released)

BTW, you should Notice: 
> Add remi .repo and enable php71..
> yum install php71...

You don't need remi-php71 repository if you use the SCL which is in remi-safe, read [FAQ](https://blog.remirepo.net/pages/English-FAQ#scl) or the [Wizard](https://rpms.remirepo.net/wizard/)

**Comment by remicollet** [comment]
I forgot the disclaimer about the **imap** extension: this extension shoud be avoid, it rely on a terribly old and not maintained library (libc-client). Most of projects don't use it anymore (roundcubemail, horde, ...).

It was even discussed to remove it from PHP (but this fail by only 1 vote...)
