### ISSUE TITLE
vips-tools segfaults on EL7

### ISSUE THREAD

**Issue by kleisauke** [remicollet/remirepo#85]
See https://github.com/jcupitt/libvips/issues/764 for more details. Just tested with ` yum --enablerepo=remi-test install ImageMagick6` but that doesn't seem to solve the problem (I think vips will need a rebuild).

**Comment by remicollet** [comment]
Can you please confirm you have test with ImageMagick 6.9.9.17**-2** ?

**Comment by kleisauke** [comment]
I've just tested it with `ImageMagick 6.9.9.17-2` and everything seems to work! :tada:

Thanks for fixing this. When can we expect this fix in `remi`?

**Comment by remicollet** [comment]
Thanks for the test.

Will be in "remi" with next build (IM have weekly update, so, should be quick)

**Comment by remicollet** [comment]
I just push new version of IM 6.9.9.18-1 with the fix in the repository

**Comment by kleisauke** [comment]
I'm willing to test! Although I'm not sure if it will fix it because poppler on EL7 still [depends on openjpeg v1](https://git.centos.org/blob/rpms!poppler.git/9ae3ca254da24c1399b584df398bcae96417502c/SPECS!poppler.spec#L76
).

**Comment by remicollet** [comment]
Indeed, my first thinking is that new version was ok, but reading my comments in the spec file, I prefer to keep the static library, so I have close this issue again.
