### ISSUE TITLE
Bug in php-pecl-memcache on remi-php71

### ISSUE THREAD

**Issue by odoucet** [remicollet/remirepo#86]
I cannot find where the source for package php-pecl-memcache-0.7.20161124gitdf7735e.el7.remi.7.1 can be found ... There is a pending bug on it preventing Memcache to be used as session manager.

Patch is available here : https://github.com/websupport-sk/pecl-memcache/issues/23#issuecomment-327702906

**Comment by remicollet** [comment]
As explain in the README file

=> https://git.remirepo.net/cgit/rpms/php/pecl/php-pecl-memcache.git/

**Comment by odoucet** [comment]
How can I provide a pull request to have this fix included in RPM ? This is a one-liner fix but quite important.

**Comment by remicollet** [comment]
As explained on https://git.remirepo.net/cgit/?p=about

**Comment by remicollet** [comment]
Don't know why this was closed,

BTW, fixed by https://git.remirepo.net/cgit/rpms/php/pecl/php-pecl-memcache.git/commit/?id=d43f1e8fe272487815100b016da44e9dfe6c3404
