### ISSUE TITLE
 broken dependency php-spl(x86-64) is missing is remi-safe and remi

### ISSUE THREAD

**Issue by unnilennium** [remicollet/remirepo#87]
Hi Remi,

here is a small issue, if you could provide spl or change the dependecy of the spl-type if it is already include in the core

# yum install  php*-php-pecl-spl-types  --enablerepo=remi,remi-safeModules complémentaires 
[..]
Résolution des dépendances
--> Lancement de la transaction de test
---> Package php54-php-pecl-spl-types.x86_64 0:0.4.0-6.el6.remi will be installé
--> Traitement de la dépendance : php-spl(x86-64) pour le paquet : php54-php-pecl-spl-types-0.4.0-6.el6.remi.x86_64
---> Package php55-php-pecl-spl-types.x86_64 0:0.4.0-6.el6.remi will be installé
--> Traitement de la dépendance : php-spl(x86-64) pour le paquet : php55-php-pecl-spl-types-0.4.0-6.el6.remi.x86_64
---> Package php56-php-pecl-spl-types.x86_64 0:0.4.0-6.el6.remi will be installé
--> Traitement de la dépendance : php-spl(x86-64) pour le paquet : php56-php-pecl-spl-types-0.4.0-6.el6.remi.x86_64
--> Résolution des dépendances terminée
Erreur : Paquet : php55-php-pecl-spl-types-0.4.0-6.el6.remi.x86_64 (remi)
             Requiert : php-spl(x86-64)
Erreur : Paquet : php54-php-pecl-spl-types-0.4.0-6.el6.remi.x86_64 (remi)
             Requiert : php-spl(x86-64)
Erreur : Paquet : php56-php-pecl-spl-types-0.4.0-6.el6.remi.x86_64 (remi)
             Requiert : php-spl(x86-64)
 Vous pouvez essayer d'utiliser --skip-broken pour contourner le problème
 Vous pouvez essayer d'exécuter : rpm -Va --nofiles --nodigest

**Comment by remicollet** [comment]
Indeed, looks like a packaging issue... missing SCL prefix.

**Comment by remicollet** [comment]
Strangely, was already fixed in -7 release which was not pushed to the repository (my fault)

A simple rebuild (-8) will fix this issue, and is now available in the repository

Please check.

**Comment by remicollet** [comment]
Please notice than [SPL_Types](https://pecl.php.net/package/SPL_Types) is a dead extension, only provided for some legacy applications, and not compatible with recent PHP versions (7+)

**Comment by unnilennium** [comment]
not fixed. showing here only php56 but the same for 54 and 55


# yum clean all --enablerepo=remi,remi-safe

# yum install --enablerepo=remi-safe  php56-php-pecl-spl-types
Modules complémentaires chargés : changelog, fastestmirror, smeserver
Configuration du processus d'installation
Loading mirror speeds from cached hostfile
 * base: mirror.its.sfu.ca
 * smeaddons: mirror.canada.pialasse.com
 * smecontribs: mirror.canada.pialasse.com
 * smeextras: mirror.canada.pialasse.com
 * smeos: mirror.canada.pialasse.com
 * smeupdates: mirror.canada.pialasse.com
 * updates: mirror.calgah.com
Résolution des dépendances
--> Lancement de la transaction de test
---> Package php56-php-pecl-spl-types.x86_64 0:0.4.0-8.el6.remi will be installé
--> Traitement de la dépendance : php-spl(x86-64) pour le paquet : php56-php-pecl-spl-types-0.4.0-8.el6.remi.x86_64
--> Résolution des dépendances terminée
Erreur : Paquet : php56-php-pecl-spl-types-0.4.0-8.el6.remi.x86_64 (remi-safe)
             Requiert : php-spl(x86-64)
 Vous pouvez essayer d'utiliser --skip-broken pour contourner le problème
 Vous pouvez essayer d'exécuter : rpm -Va --nofiles --nodigest

# yum install --enablerepo=remi  php56-php-pecl-spl-types
Modules complémentaires chargés : changelog, fastestmirror, smeserver
Configuration du processus d'installation
Loading mirror speeds from cached hostfile
 * base: mirror.its.sfu.ca
 * smeaddons: mirror.canada.pialasse.com
 * smecontribs: mirror.canada.pialasse.com
 * smeextras: mirror.canada.pialasse.com
 * smeos: mirror.canada.pialasse.com
 * smeupdates: mirror.canada.pialasse.com
 * updates: mirror.calgah.com
Résolution des dépendances
--> Lancement de la transaction de test
---> Package php56-php-pecl-spl-types.x86_64 0:0.4.0-8.el6.remi will be installé
--> Traitement de la dépendance : php-spl(x86-64) pour le paquet : php56-php-pecl-spl-types-0.4.0-8.el6.remi.x86_64
--> Résolution des dépendances terminée
Erreur : Paquet : php56-php-pecl-spl-types-0.4.0-8.el6.remi.x86_64 (remi)
             Requiert : php-spl(x86-64)
 Vous pouvez essayer d'utiliser --skip-broken pour contourner le problème
 Vous pouvez essayer d'exécuter : rpm -Va --nofiles --nodigest

**Comment by remicollet** [comment]
Grrr... 

Should be "really" fixed by https://git.remirepo.net/cgit/rpms/php/pecl/php-pecl-spl-types.git/commit/?id=d4cd1d100fd6d3588212a11ba1224c3c9e5d6f95 (in -9 release)

**Comment by unnilennium** [comment]
confirmed as fixed

Remi, I want to thank you for all your work !

**Comment by remicollet** [comment]
:)
