### ISSUE TITLE
package php-ext brotli

### ISSUE THREAD

**Issue by mboeru** [remicollet/remirepo#88]
Since this very good  up and  coming generic-purpose lossless compression algorithm it would be nice to have have it packaged for PHP and install it as a module for rpms in remirepos.

libbrotli is available right now only in fedora, so probably it would need to be packaged for CentOS as well.
The project embeds google's brotli library right now, 

https://github.com/kjdev/php-ext-brotli/

**Comment by remicollet** [comment]
Waiting for upstream feedback on https://github.com/kjdev/php-ext-brotli/pull/6

**Comment by remicollet** [comment]
Fixed by https://git.remirepo.net/cgit/rpms/php/php-brotli.git/commit/?id=e4055c16c0de103b2893290b36e5aa815e4d0186

Fedora >= 25 packages will use system brotli library
Others will use bundled copy

Feedback very welcome

**Comment by remicollet** [comment]
Any news ?

**Comment by remicollet** [comment]
Closing without feedback :(

**Comment by mboeru** [comment]
Sorry for the late reply. The module works great in our dev envs, and was pushed last week into our integration environment (no issues so far)
We'll add it into production next week.

Many thanks for this!
