### ISSUE TITLE
APCu for PHP 7.2 compiled DLL

### ISSUE THREAD

**Issue by SailorMax** [remicollet/remirepo#90]
Can you prepare APCu for PHP 7.2 with Windows DLL file?
Or whom I have to ask?

thank you.

**Comment by remicollet** [comment]
Unrelated to this repository.

AFAIK, rebuid of pecl extension for windows and php 7.2 is "Work in Progress"

**Comment by remicollet** [comment]
=> https://pecl.php.net/package/APCu/5.1.8/windows
