### ISSUE TITLE
Not exist php-pear in remi-php72

### ISSUE THREAD

**Issue by warmwinter** [remicollet/remirepo#91]
In the remi-php72 repository, php-pear isn't exist.
But in remi-safe,  php72-php-pear.noarch exists.
Need fix?

OS: CentOS 7 x86_64

**Comment by remicollet** [comment]
Have you miss it ?
See https://rpms.remirepo.net/enterprise/7/php72/x86_64/repoview/php-pear.html

**Comment by warmwinter** [comment]
`yum list --enablerepo=remi-php72 php-pear` cann't list it

**Comment by remicollet** [comment]
Have you read the [FAQ / No package found](https://blog.remirepo.net/pages/English-FAQ#priority) ?
(especially about priority)

```
# LANG=C yum list --disablerepo=remi* --enablerepo=remi-php72 php-pear
Available Packages
php-pear.noarch                       1:1.10.5-2.el7.remi                           remi-php72

```

**Comment by warmwinter** [comment]
I uninstall the php-pear from remi-php71, then list it.
Thanks

**Comment by remicollet** [comment]
btw, version are the same ;)

**Comment by remicollet** [comment]
and, do you really still use "pear" packages ?
(as pecl command is usually unneeded, as nearly all extension are also packaged)

**Comment by warmwinter** [comment]
Only use it in docker env ;)

Thanks for your answer!
