### ISSUE TITLE
Could not retrieve mirrorlist?

### ISSUE THREAD

**Issue by beheerderdag** [remicollet/remirepo#94]
Since yesterday yum update is showing the following error: 

 `Could not retrieve mirrorlist
 http://rpms.remirepo.net/enterprise/7/php56/mirror error was 
14: HTTP Error 503 - Service Unavailable`

Is the repo not available currently? Should we point to a different address?

**Comment by remicollet** [comment]
Primary server is under maintenance...

Sorry for the inconvenience, I hope it will be back online very soon

More information will be post on https://twitter.com/RemiRepository

**Comment by HHawk** [comment]
Hope so... Now I understand that you need to have alternatives. Over 2 hours down already unfortunately.
Anyways, wish you the best and hope it will be back up soon.

**Comment by remicollet** [comment]
Back online
