### ISSUE TITLE
Improve mirrorlist availability

### ISSUE THREAD

**Issue by remicollet** [remicollet/remirepo#95]
After recent outage (13h on 2018-01-09 and 6h on 2018-01-10) we need to improve mirrorlist availability.

Having a single point of failure on this URI, make the repository mostly unusable, despite we have [>30 mirrors around the world](https://umap.openstreetmap.fr/en/map/remi-repository-mirrors-map_106530#2/21.8/17.9).

BTW: first real issue in 10 years using this hosting company, so availability still > 99%

**Comment by remicollet** [comment]
Step 1:

* move the mirrorlist to cdn.remirepo.net with a round-robin on 2 servers, in 2 different datacenters.

This is now working, **feedback welcome**

Easy way to switch

```
# backup configuration file
tar cf /root/remi.tgz /etc/yum.repos.d/remi*repo
# switch to cdn
sed -e '/mirrorlist/s/rpms.remirepo.net/cdn.remirepo.net/' -i /etc/yum.repos.d/remi*repo`
```

Thanks to Philippe for the second server.

**Comment by trasher** [comment]
Laptop switched yesterday => no problem.
Just switched my server => no problem.

Thank you! 👍

**Comment by kapouik** [comment]
It work on my server : getting your repolist was never so fast :)

**Comment by remicollet** [comment]
Step 2: 
* publish new remi-release package for Fedora 26/27

Fixed in https://git.remirepo.net/cgit/rpms/remi-release.git/commit/?id=019e41c567494589bfef17cc6a3e0117a689505c

(remi-release-26-3.fc26.remi and remi-release-27-2.fc27.remi)

**Comment by remicollet** [comment]
**Step 3:**
* publish new remi-release package for EL 6/7

Fixed in https://git.remirepo.net/cgit/rpms/remi-release.git/commit/?id=1b543c43299e2a2286333a07734ad1e8c69af914

(remi-release-7.4-1.el7.remi.noarch.rpm and remi-release-6.9-2.el6.remi.noarch.rpm)

**Comment by remicollet** [comment]
Everything seems OK

Step 3 will be to have a new server, with full content, and https acces, but this have some budget impact. Current situation seems enough for now.

**Comment by remicollet** [comment]
Closing as everything is ok for a while now
