### ISSUE TITLE
Impossible to install php-sodium

### ISSUE THREAD

**Issue by galvao** [remicollet/remirepo#97]
Fedora 27
Remi's Repo: http://rpms.remirepo.net/fedora/$releasever/debug-php72/$basearch/

While trying to install php-sodium it complains about the lack of libsodium, even after installing libsodium, libsodium-static and libsodium-devel.
```bash
[zaphod@magrathea ~]$ sudo dnf install php-sodium
Last metadata expiration check: 0:00:43 ago on Mon 19 Feb 2018 03:48:44 AM -03.
Error: 
 Problem: conflicting requests
  - nothing provides libsodium.so.23()(64bit) needed by php-sodium-7.2.1-3.fc27.remi.x86_64
  - nothing provides libsodium.so.23()(64bit) needed by php-sodium-7.2.2-1.fc27.remi.x86_64
```

**Comment by remicollet** [comment]
You need libsodium23 from "remi" repository (remi-php72 is not enough, because of such common dependencies)

**Comment by remicollet** [comment]
Notice, in remi-php72.repo file

     # WARNING: If you enable this repository, you must also enable "remi"

**Comment by galvao** [comment]
Thank you, @remicollet, I wasn't aware of that. And yes, just saw that on the .repo file.
Incidentally, shouldn't the wizard in https://rpms.remirepo.net/wizard/ contain that information?

**Comment by remicollet** [comment]
> Incidentally, shouldn't the wizard in https://rpms.remirepo.net/wizard/ contain that information?

Indeed.

**Comment by remicollet** [comment]
Fixed by https://git.remirepo.net/cgit/web/rpms.git/commit/?id=11b2dd0d6c8a02ebe5a615fdd96c3957cde069c1

**Comment by pepper1231** [comment]
Thank you. That script saved my life. I was losing my mind. Always something wasnt working, or always was missing. As sodium was missing. Even from manual install. That was pain tbh.
