### ISSUE TITLE
Correct memcached for listen on local (like CentOS 6)

### ISSUE THREAD

**Issue by unreturned** [remicollet/remirepo#98]
```
diff --git memcached.spec memcached.spec
index 7877458..8c6800d 100644
--- memcached.spec
+++ memcached.spec
@@ -154,7 +154,7 @@ PORT="11211"
 USER="%{username}"
 MAXCONN="1024"
 CACHESIZE="64"
-OPTIONS=""
+OPTIONS="-l localhost"
 EOF
 
 # Constant timestamp on the config file.
diff --git memcached.sysv memcached.sysv
index 19e5a12..efb18e3 100644
--- memcached.sysv
+++ memcached.sysv
@@ -16,7 +16,7 @@ PORT=11211
 USER=memcached
 MAXCONN=1024
 CACHESIZE=64
-OPTIONS=""
+OPTIONS="-l localhost"
 
 if [ -f /etc/sysconfig/memcached ];then 
        . /etc/sysconfig/memcached
```

Thanks

**Comment by remicollet** [comment]
The package in my repository is only a backport of Fedora official one

This option have been enabled in Fedora 25, and I keep previous configuration in other distro to not break existing installation / configuration.

**Comment by remicollet** [comment]
On security side, indeed, listening on localhost seems better

On real usage... a network service not available on the network... doesn't really make sense ;)

**Comment by unreturned** [comment]
Thanks for your reply!

Unfortunately, modern administrators absolutely do not want to configure the services that they install, and the default configuration of memcached allows you to conduct an amplified attack

https://translate.google.ru/translate?sl=ru&tl=en&js=y&prev=_t&hl=ru&ie=UTF-8&u=https%3A%2F%2Fhabrahabr.ru%2Fcompany%2Fqrator%2Fblog%2F350074%2F&edit-text=&act=url

It would be cool to try and minimize such cases.

**Comment by remicollet** [comment]
> Unfortunately, modern administrators absolutely do not want to configure the services that they install

_[sic]_

**Comment by remicollet** [comment]
Official RPM in RHEL/CentOS base repository don't have this option, and I want to keep the same behavior to not break on update.

If Red Hat choose to change the option, I will follow.

**Comment by unreturned** [comment]
Thanks!
