### ISSUE TITLE
Teradata PHP RPM

### ISSUE THREAD

**Issue by cjsfj** [remicollet/remirepo#99]
Seems like there is a niche need for a really good implementation of php support for teradata ODBC connections.

I've cobbled something together for my own usage, but it requires a recompile of the entire PHP every time there is a revision. Would be awesome to have an RPM to do this, but that's a little outside my expertise.

Happy to contribute my knowledge to this, but wanted to get this conversation started and see if this is even a good idea before a brain dump.

Thanks!

**Comment by remicollet** [comment]
The php-odbc extensions should be enough to connect to any database, when the ODBC driver exists. PHP is not even aware of available drivers.

So I don't understand why you have to rebuild anything.

**Comment by cjsfj** [comment]
I thought that php-odbc uses unixODBC. Teradata is a datadirect-based driver so as far as I know the regular odbc connectivity doesn’t work for teradata. 

However I’ll do some more testing and see if I’m missing something.

**Comment by cjsfj** [comment]
Thanks for keeping this issue open. Should have some more information tomorrow regarding the viability of using the php-odbc extension for connections to Teradata servers.

**Comment by cjsfj** [comment]
I've been unable to connect to Teradata using unix ODBC. However I have found the following docs Teradata outlining how to compile support into PHP:

https://developer.teradata.com/blog/odbcteam/2016/02/php-with-teradata-odbc

Not too old, but not new either. As I can tell it seems that the Teradata drivers require the Kourne shell (ksh) and specific compile parameters to work properly.

I can understand if this is too specific to include in this repo, but just wanted to give an update.

Thanks,

CJ
